### ISSUE TITLE
v1.1.0

### ISSUE THREAD

**Issue by jbnicolai** [chalk/chalk#100]
Let's try to get out `v1.1.0`.

Some tasks that needs to be done before hand (please fill in if I left out something):

 

- [ ] Anything feature wise we're missing?
- [ ] Changelog
- [ ] Some manual testing with popular consumers like Bower, Gulp.
- [ ] A name for the release

// @sindresorhus @Qix-

**Comment by sindresorhus** [comment]
There are breaking changes in master, and the plan was to get out a 2.0.0 release. Nothing really pressing other than the 16m color support. We need to resolve the open issue about that first.

**Comment by Qix-** [comment]
Yep, 16m was the big one for the next major.

**Comment by Qix-** [comment]
~~ housekeeping ~~
