### ISSUE TITLE
Is there anyway to detect if the terminal BG is light or dark?

### ISSUE THREAD

**Issue by juanmnl** [chalk/chalk#102]
Hello everyone! i'm trying to make [my first cli-app](https://github.com/juanmnl/gitano-cli) and added some chalk.js sweetness but i have a problem with the rendering on different terminal apps.  
Is there a workaround to support all of them with different bg's?  

Thanks :D 

Left: iterm2 V3
right: osx terminal Version 2.6.1 (361.1)
<img width="1435" alt="screenshot 2016-03-11 09 03 46" src="https://cloud.githubusercontent.com/assets/699945/13704395/ae5fc954-e769-11e5-9d99-667fedcce065.png">

**Comment by sindresorhus** [comment]
I don't think there's a way to detect the terminal background color.

// @Qix-

**Comment by juanmnl** [comment]
There's a kind workaround by using the `inverse` method. It's not exactly what I wanted but it works on every terminal. :D  I'll try to dig more, to see if there's a better way of doing this.  
<img width="1262" alt="screenshot 2016-03-11 14 44 30" src="https://cloud.githubusercontent.com/assets/699945/13713658/1e849f24-e798-11e5-947e-898badda01de.png">

**Comment by Qix-** [comment]
Nope, unfortunately nothing that is cross-platform. Terminals are generally a one-way means of interaction in terms of styling.

**Comment by juanmnl** [comment]
@sindresorhus @Qix- Thanks for the quick replies! :D  
I'll stick to the inverse method until i find how to style it better.  
Thanks again!
