### ISSUE TITLE
Question: theme name for colors in README

### ISSUE THREAD

**Issue by galambalazs** [chalk/chalk#103]
What is the name of the theme used for the screenshot inside README?

![screenshot](https://cloud.githubusercontent.com/assets/309987/13725069/d6b3fd24-e897-11e5-92f1-c01a5826b322.png)

**Comment by sindresorhus** [comment]
[Tomorrow Night Eighties](https://github.com/chriskempson/tomorrow-theme) theme with the [Droid Sans Mono](http://www.google.com/webfonts/specimen/Droid+Sans+Mono) font (15pt).
