### ISSUE TITLE
Bump ansi-style dependency to ^2.2.0

### ISSUE THREAD

**Issue by chuym** [chalk/chalk#105]
The dependency to ansi-styles is `^2.1.0`
After the unpublish of `ansi-style@2.2.0` as result of this issue: https://github.com/chalk/ansi-styles/issues/15 chalk fails to build.

Please upgrade package.json to take the steps described in the post mortem: https://github.com/chalk/ansi-styles/issues/15#issuecomment-202589714

**Comment by bradvogel** [comment]
+1

**Comment by Qix-** [comment]
Hi - I can do this, but it shouldn't be failing.

What errors are you facing?

**Comment by chuym** [comment]
@Qix- Thanks for looking into it. It was actually our shrinkwrap that was broken. No need to upgrade.

Closing this

**Comment by Qix-** [comment]
Aha yeah, I think that's what's going to cause issues.

chalk/ansi-styles#17 addresses shrinkwrap. I've also released a new patch version with the updated dependency (landed in a838948dcbf2674dd28adfbb78e791900ae741e9).
