### ISSUE TITLE
[fixed] Breaking change in v1.1.2: removes `chalk.stripColor`, `chalk.hasColor`

### ISSUE THREAD

**Issue by roblg** [chalk/chalk#106]
Our `npm install` started picking up the new versions of chalk, and failing at, e.g. `node_modules/eslint/lib/formatters/stylish.js:71:34` with this error: `TypeError: chalk.stripColor is not a function`

**Comment by Qix-** [comment]
Ugh. Okay. Just a second.

**Comment by Qix-** [comment]
@roblg Could you re-install (`rm -r node_modules && npm i`) and see if that fixes it?

It should be pulling chalk v1.1.3, which is just v1.1.1 + [this line's change](https://github.com/chalk/chalk/commit/a838948dcbf2674dd28adfbb78e791900ae741e9#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L48).

**Comment by madole** [comment]
I was seeing this too... your latest change fixes it. Thanks :+1:

**Comment by Qix-** [comment]
@madole Thank you for letting me know.

**Comment by Qix-** [comment]
Side note, we're going to be doing major releases tomorrow >.> I'm tired of having breaking changes in master and having this shit happen.

**Comment by CodySchaaf** [comment]
Fastest github issue resolution. Thanks!

**Comment by Qix-** [comment]
Keeping open for discovery.
