### ISSUE TITLE
Error Chalk has no method 'grey' after update

### ISSUE THREAD

**Issue by fernando-nery** [chalk/chalk#107]
After chalk was updated last night with version 1.1.3, I started having troubles with fancy-log, as npm is requiring this version:

```
├─┬ fancy-log@1.2.0 
│ ├─┬ chalk@1.1.3 
│ │ ├── escape-string-regexp@1.0.5 
│ │ └─┬ strip-ansi@3.0.1 
│ │   └── ansi-regex@2.0.0 
```

The error output shows the following:

```
/node_modules/fancy-log/index.js:9
return '['+chalk.grey(timestamp('HH:mm:ss'))+']';
                    ^

TypeError: Object #<Chalk> has no method 'grey'
at getTimestamp (node_modules/fancy-log/index.js:9:20)
at log (node_modules/fancy-log/index.js:13:14)
at module.exports (node_modules/gulp-util/lib/log.js:11:14)
at Object.module.exports.logError (node_modules/gulp-notify/lib/extra_api.js:20:3)
at logError (node_modules/gulp-notify/lib/notify.js:91:11)
at node_modules/gulp-notify/lib/notify.js:63:7
at module.exports (node_modules/gulp-notify/lib/report.js:37:12)
at DestroyableTransform._flush (node_modules/gulp-notify/lib/notify.js:62:5)
at DestroyableTransform.<anonymous> (node_modules/gulp-notify/node_modules/readable-stream/lib/_stream_transform.js:135:12)
at DestroyableTransform.g (events.js:180:16)
Process exited with code 8 
```

The line where the error is reported is really straightforward:

```
var chalk = require('chalk');
var timestamp = require('time-stamp');

function getTimestamp(){
  return '['+chalk.grey(timestamp('HH:mm:ss'))+']';
}
```

**Comment by Qix-** [comment]
Strange. Ill take a look soon (I'm on the road at the moment).

As a temporary workaround you can do `chalk.grey = chalk.gray`. That should fix it.

**Comment by Qix-** [comment]
Huh. This is strange. Tests are passing, and we have a test for this.

I can investigate further; however, could you nuke your node_modules and re-install? This is an ansi-styles thing and I wonder if it's not updated correctly.

**Comment by fernando-nery** [comment]
Hey @Qix-,

Just did so and the problem persists. Actually, who caught it up was our CI that cleans everything (including cache) and re-installs it. In my local env I am not getting any errors with version 1.1.1.

But, since we ran a build yesterday afternoon before these releases, I can confirm everything was working solid before it. Any other tests we may run on our side?

**Comment by Qix-** [comment]
Very strange. Can you confirm the versions of `ansi-styles` and `chalk` being pulled on the CI's side?

**Comment by fernando-nery** [comment]
Yes it is very strange.
I manually deleted the node_modules and ran: `npm cache clear` and `npm install` again.

This is what I get:
```
ansi-styles: 1.1.0
chalk: 1.1.
fancy-log: 1.2.0
npm: 3.8.0
bower: 1.7.7
gulp: 3.9.1
```

Tried running gulp and the problem above persisted.

Then, I manually edited fancy-log adding the line you requested before, so it looks like:

```
function getTimestamp(){
  chalk.grey = chalk.gray
  return '['+chalk.grey(timestamp('HH:mm:ss'))+']';
}
```

And the problem was solved!

**Comment by Qix-** [comment]
The wrong version of ansi-styles is being pulled. Should be at least 2.1.0.

**Comment by fernando-nery** [comment]
Hey @Qix- , I was able to solve the problem by forcing the ansi-styles to 2.1.0 on my packages.json file.

Thank you very much for the help, and sorry about this trouble.

**Comment by Qix-** [comment]
No problem! Glad it was resolved :dancers:
