### ISSUE TITLE
How to use chalk without console.log?

### ISSUE THREAD

**Issue by sangdth** [chalk/chalk#108]
I saw chalk's document and it can write without console.log, but when I tried to apply it into my Krakenjs project, it does not work. Should I do something else to get it works?

I'm using Mac OS X.

**Comment by Qix-** [comment]
You can't. All Chalk does is generate ANSI escape sequences that only work in terminals - hence `console.log()`.

**Comment by sangdth** [comment]
Thanks Qix, I misunderstood the usage.

**Comment by Qix-** [comment]
No problem :dancer:
