### ISSUE TITLE
Allow manual selection of color level via API

### ISSUE THREAD

**Issue by neophob** [chalk/chalk#109]
Currently Chalk Color modes can be enforced by setting env variables (TERM, FORCE_COLOR...) or using parameters. However it would be more straightforward if chalk would support a global setting to force a particular color mode.

I use chalk to send out colored statistics via express, so the user can fetch a nice colored output via ```curl http://youname.it/url``` - so it make no sense to rely on local ENV variables (in this use case).

what do you think?

**Comment by Qix-** [comment]
I'm game. Wouldn't mind having something like

```js
chalk.level(1).rgb(143, 11, 199)('hello');
```

to force all subsequent calls to 16 colors (level 1).

**Comment by Qix-** [comment]
While it's not 'pretty', you're certainly able to do

```javascript
var chalkForced = new chalk.constructor({enabled: true});
console.log(chalkForced.red('This should be red'));

var chalkDisabled = new chalk.constructor({enabled: false});
console.log(chalkDisabled.red('This should be default colored'));
```

**Comment by neophob** [comment]
Thanks Qix for the quick response. So this means instead the FORCE_COLOR env variable I'm able to replace ```const chalk = require('chalk');``` with ```const chalk = new chalk.constructor({enabled: true})```?

If so, I'm happy and you can close this ticket ;)

**Comment by Qix-** [comment]
Yeah that would work assuming it’s already required. :)
