### ISSUE TITLE
Out of sync

### ISSUE THREAD

**Issue by Martii** [chalk/chalk#110]
Greetings. Cool project you have here... with one current exception.

This project seems to be out of sync with npmjs.com e.g. [`2653218`/package.json#L3](https://github.com/chalk/chalk/blob/2653218312383882256dd2b9217b74bfc4a5dd01/package.json#L3) shows 1.1.1 and npm shows [![chalk shield](https://img.shields.io/npm/v/chalk.svg?style=flat)](https://www.npmjs.com/package/chalk)

Will there be an update somewhere to fix this?

Thanks so much.

**Comment by sindresorhus** [comment]
https://github.com/chalk/chalk/commits/1.1.3

**Comment by Martii** [comment]
I did see that there is [a branch](https://github.com/chalk/chalk/tree/1.1.3) [with 1.1.3](https://github.com/chalk/chalk/blob/0d8d8c204eb87a4038219131ad4d8369c9f59d24/package.json#L3) but the repo doesn't appear to be set to default to that.

**Comment by Martii** [comment]
So the issue shouldn't be closed.

**Comment by tunnckoCore** [comment]
@Martii what's the problem? In any way you get latest version - 1.1.3, and as you can see the diffs between are just bump of one dep.

**Comment by Martii** [comment]
Well it's a little confusing that I had to go diving for a branch to verify things are still aok for dep updates... would be nice to have it mentioned in the README.md. Even the [releases](https://github.com/chalk/chalk/releases) show 1.1.1.

**Comment by tunnckoCore** [comment]
> Even the releases show 1.1.1.

Good point.

> verify things are still aok 

they are okey, that's a patch bump - no breaking changes or new features.

**Comment by sindresorhus** [comment]
@Martii It's common to create separate release branches for patch/minor versions of older major versions. Master is currently targeting a 2.0.0 release.

**Comment by Qix-** [comment]
`1.1.3` is a roll back from the botched release `1.1.2`. It was an [emergency situation](https://github.com/chalk/ansi-styles/issues/15#issuecomment-202589714) that led to a few things being wonky for a while. The next time we release, things should be synced up.

Further, npm has been doing weird things lately with the whole unpublish/Azer/left-pad stuff. I've seen strange behavior being reported all over the internet about it - especially caching problems. I also have text alerts set up for them when things go awry and lately there have been a _lot_ of outages and 2spooky4me stuff going on.
