### ISSUE TITLE
How to keep call stack?

### ISSUE THREAD

**Issue by screendriver** [chalk/chalk#112]
If I got an error with a call stack, how can I keep it with chalk?

```js
foo(function(err, data) {
  if (err) {
    console.error(chalk.red(err));
  }
});
```

At the moment I only see the call stack when I **don't** use chalk.

**Comment by sindresorhus** [comment]
Unrelated to Chalk. `console.error` smartly handles error object passed to it. You can do the same with `console.error(chalk.red(require('util').inspect(err));

**Comment by Qix-** [comment]
Or use `err.stack`.
