### ISSUE TITLE
"Bold" versions of background colors?

### ISSUE THREAD

**Issue by mhkeller** [chalk/chalk#114]
To get more flexibility in color choices, is it possible to use the "bold" versions of colors as background colors? My use case that the default `bgBlue` makes some text illegible for some people on my team but there's more consistency in contrast levels across "bold blue" colors.

**Comment by Qix-** [comment]
@sindresorhus I thought we had this? How was this missed? O.o

I think one of the problems that was (previously) faced in `ansi-styles` was that, while foreground had a "bright" flag, backgrounds didn't and require the render modes `100`-`107` to be used instead.

The next major version of chalk should fix this.

**Comment by sindresorhus** [comment]
I think I left them out initially as I didn't see the point and wanted to keep it simple. Does the bold background colors work in most terminals? Can you provide an example of how you would use it? Just curious.

**Comment by mhkeller** [comment]
By how one would use it, do you mean the syntax? Perhaps `chalk.bgBlue.bgBold('my text to bold')` would be the most consistent. I'll let other terminal experts speak to consistency across terminals...

**Comment by Qix-** [comment]
> Does the bold background colors work in most terminals?

Yea, for the most part.

> Perhaps `chalk.bgBlue.bgBold('my text to bold')`

lgtm.

**Comment by Qix-** [comment]
I realize why, now. There is no code for bold backgrounds. Instead, you have to use the non-standard bright background codes `100` - `107`. This would require doing some extra processing on the chalk end. I might get to this after #140 lands and release it as a minor version :)
