### ISSUE TITLE
It's not working on my mac (10.11.5)

### ISSUE THREAD

**Issue by ir-fuel** [chalk/chalk#115]
This is my code:

```
const chalk = require('chalk');

console.log(chalk.red('TOTOTOTOT'));
console.log(chalk.blue('Hello world!'));
```

It just prints white text in iTerm and Terminal

package.json
```
"chalk": "^1.1.3",
```

What am I doing wrong here?

Thanks

**Comment by dthree** [comment]
Probably a bad install or dependency mix-up or something.

Do this and tell me what prints:

```js
const util = require('util');
console.log(util.inspect(chalk.red('foobar')));
```

**Comment by ir-fuel** [comment]
'foobar' (in white)

here is my package.json

```
  "dependencies": {
    "aws-sdk": "^2.3.14",
    "axios": "^0.11.1",
    "babel-polyfill": "^6.9.0",
    "body-parser": "^1.15.1",
    "chalk": "^1.1.3",
    "co": "^4.6.0",
    "express": "^4.13.4",
    "express-routeloader": "^2.0.0",
    "le_node": "^1.3.1",
    "moment": "^2.13.0",
    "mongoose": "^4.4.19",
    "mysql": "^2.10.2",
    "mysql-promise": "^3.0.0",
    "source-map-support": "^0.4.0",
    "superagent": "^1.8.3"
  },
  "devDependencies": {
    "assert": "^1.4.0",
    "babel-cli": "^6.9.0",
    "babel-core": "^6.9.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-stage-1": "^6.5.0",
    "babel-watch": "^2.0.2",
    "mocha": "^2.5.1",
    "mongodb": "^2.1.19"
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-1"
    ]
  }
```

**Comment by Qix-** [comment]
Please show me the output of the following commands:

```console
$ echo $TERM
$ echo $SHELL
$ echo $TERM_PROGRAM
$ [ -t 1 ] && echo yes || echo no
```

**Comment by ir-fuel** [comment]
```
echo $TERM
xterm
echo $SHELL
/bin/bash
echo $TERM_PROGRAM
iTerm.app
[ -t 1 ] && echo yes || echo no
yes
```

**Comment by Qix-** [comment]
When you run your script, run it like this:

```console
$ FORCE_COLOR=1 node /path/to/your/script.js
```

Does it output color?

**Comment by ir-fuel** [comment]
yes it does!

**Comment by Qix-** [comment]
What command line are you using to invoke your program when it only shows white?

**Comment by ir-fuel** [comment]
is it maybe because I spawn a node process that spawns another node child process, and that it's the second process that does the logging?

**Comment by Qix-** [comment]
Yes. The child process is piped to the parent process which makes `isatty()` return `0` (false) within the child process.

Pass an [`env` entry](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) with `FORCE_COLOR=1` to the child.

Some *pseudo-code*:

```
child_process = ...

if chalk.supportsColor then
    child_process.env.FORCE_COLOR = '1'
endif
```

**Comment by ir-fuel** [comment]
thanks!

**Comment by PierBover** [comment]
I'm not spawning any child process but I'm not getting any output from Chalk. No errors either.

I've tried `console.log(chalk.supportsColor)` and I get `true`.

I'm on 10.11.6 using either iTerm or Terminal.

I'm launching my script with NPM, nothing fancy here.

packages.json
```
  "scripts": {
    "do-something": "node something.js",
  }
```
Then on the terminal:
```
npm run do-something
```

**Comment by Qix-** [comment]
Chalk is working just fine in that case. Something is wrong with your terminal. Please update it :)

**Comment by PierBover** [comment]
I'm using the latest versions of both apps.

**Comment by Qix-** [comment]
Does `printf "\u001b[31mHello\u001b[m"` work?

**Comment by PierBover** [comment]
Nope

 iTerm
![image](https://cloud.githubusercontent.com/assets/226483/18189022/899732f0-707c-11e6-8b35-b1cf00fb1630.png)

Apple Terminal
![image](https://cloud.githubusercontent.com/assets/226483/18189028/990e2e14-707c-11e6-8294-a7b3ef84d6ea.png)

**Comment by Qix-** [comment]
I'm not sure what to tell you. For the chalk problem, I'd have to see the output. For the above problem, it appears whatever implementation of `printf` you have doesn't escape strings.

What version of OS X are you running?

**Comment by PierBover** [comment]
`node <<< "console.log('\x1b[31mhello\x1b[m')"` outputs hello in red.

I'm on 10.11.6 and using Node 6.3.0

**Comment by Qix-** [comment]
Btw `printf` is a builtin and `sh` doesn't support escapes so that might explain it.

So the node snippet works. Does `node <<< "require('chalk').red('hello')"` work?

**Comment by PierBover** [comment]
Yes, that does indeed work...

Oh god I'm an idiot. Do I have to use `console.log()` with chalk?

I completely missed the message in the docs:

> Here without console.log for purity.

I'm really sorry for wasting your time.

**Comment by simonstewart** [comment]
@PierBover made the same mistake.
The sample code on npm does imply you can just do:
`chalk.blue('Hello');`
Instead of: 
`console.log(chalk.blue('Hello');`
