### ISSUE TITLE
AWS log without colors

### ISSUE THREAD

**Issue by kikar** [chalk/chalk#117]
I'm using chalk for my custom logs, but I use morgan for routes logs on my server.
The server is deployed on AWS with Elastic Beanstalk, and when I check the logs from the command line  (`eb logs`) Morgan logs come out colorful, while chalk comes out white.
Is there a way to improve this?

**Comment by Qix-** [comment]
`FORCE_COLOR=1` environment variable didn't work?

**Comment by kikar** [comment]
Shall I set that in Elastic Beanstalk configuration?

**Comment by kikar** [comment]
It works, thank you

**Comment by xpolb01** [comment]
FORCE_COLOR=1 worked for me too
