### ISSUE TITLE
Support multiline strings

### ISSUE THREAD

**Issue by leobalter** [chalk/chalk#12]
It would be nice if chalk support strings with multiple lines (`\n`).

Meanwhile the workaround would something like: 

``` javascript
function formatMessage( str ) {
    return String( str ).split( "\n" ).map(function( s ) {
        return chalk.magenta( s );
    }).join( "\n" );
}
```

It would be better to only use `chalk.magenta( str );` and get all the color on all the string lines

**Comment by sinedied** [comment]
When using tagged template literals, `\n` does not work => `n` is output and there is no line break.

**Comment by Qix-** [comment]
@sinedied yeah we're using the raw form of template literals. Please either use real line breaks in your code or open a separate issue for it as it's unrelated to this.
