### ISSUE TITLE
npm ERR! Error: No compatible version found: chalk@'^1.0.0'

### ISSUE THREAD

**Issue by bellaj** [chalk/chalk#123]
I am trying to install chalk but i get this error (for windows 10) 
npm ERR! Error: No compatible version found: chalk@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.2.0","0.2.1","0.3.0","0.4.0","0.5.0","0.5.1","1.0.0","1.1.0","1.1.1","1.1.2","1.1.3"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:685:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:607:10
npm ERR!     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

**Comment by Qix-** [comment]
Wut. That seems like a bug in NPM, not chalk (it's showing you're requesting any 1.x.x version and even shows multiple versions there that should match that).

Can you post your package.json and your NPM version? Have you tried blowing away `node_modules/` and re-installing?

**Comment by bellaj** [comment]
even i delete the node_modules folder and reinstalling the problem occure
npm version :  1.2.18
This is my json file : 

{
  "version": "3.10.6",
  "name": "npm",
  "description": "a package manager for JavaScript",
  "keywords": [
    "install",
    "modules",
    "package manager",
    "package.json"
  ],
  "preferGlobal": true,
  "config": {
    "publishtest": false
  },
  "homepage": "https://docs.npmjs.com/",
  "author": {
    "name": "Isaac Z. Schlueter",
    "email": "i@izs.me",
    "url": "http://blog.izs.me"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/npm/npm"
  },
  "bugs": {
    "url": "https://github.com/npm/npm/issues"
  },
  "directories": {
    "bin": "./bin",
    "doc": "./doc",
    "lib": "./lib",
    "man": "./man"
  },
  "main": "./lib/npm.js",
  "bin": {
    "npm": "./bin/npm-cli.js"
  },
  "dependencies": {
    "abbrev": "~1.0.9",
    "ansicolors": "~0.3.2",
    "ansistyles": "~0.1.3",
    "aproba": "~1.0.4",
    "archy": "~1.0.0",
    "asap": "~2.0.4",
    "chownr": "~1.0.1",
    "cmd-shim": "~2.0.2",
    "columnify": "~1.5.4",
    "config-chain": "~1.1.10",
    "dezalgo": "~1.0.3",
    "editor": "~1.0.0",
    "fs-vacuum": "~1.2.9",
    "fs-write-stream-atomic": "~1.0.8",
    "fstream": "~1.0.10",
    "fstream-npm": "~1.1.0",
    "glob": "~7.0.5",
    "graceful-fs": "~4.1.4",
    "has-unicode": "~2.0.1",
    "hosted-git-info": "~2.1.5",
    "iferr": "~0.1.5",
    "inflight": "~1.0.5",
    "inherits": "~2.0.1",
    "ini": "~1.3.4",
    "init-package-json": "~1.9.4",
    "lockfile": "~1.0.1",
    "lodash._baseuniq": "~4.6.0",
    "lodash.clonedeep": "~4.3.2",
    "lodash.union": "~4.4.0",
    "lodash.uniq": "~4.3.0",
    "lodash.without": "~4.2.0",
    "mkdirp": "~0.5.1",
    "node-gyp": "~3.4.0",
    "nopt": "~3.0.6",
    "normalize-git-url": "~3.0.2",
    "normalize-package-data": "~2.3.5",
    "npm-cache-filename": "~1.0.2",
    "npm-install-checks": "~3.0.0",
    "npm-package-arg": "~4.2.0",
    "npm-registry-client": "~7.1.2",
    "npm-user-validate": "~0.1.5",
    "npmlog": "~3.1.2",
    "once": "~1.3.3",
    "opener": "~1.4.1",
    "osenv": "~0.1.3",
    "path-is-inside": "~1.0.1",
    "read": "~1.0.7",
    "read-cmd-shim": "~1.0.1",
    "read-installed": "~4.0.3",
    "read-package-json": "~2.0.4",
    "read-package-tree": "~5.1.5",
    "readable-stream": "~2.1.4",
    "realize-package-specifier": "~3.0.3",
    "request": "~2.72.0",
    "retry": "~0.9.0",
    "rimraf": "~2.5.3",
    "semver": "~5.1.0",
    "sha": "~2.0.1",
    "slide": "~1.1.6",
    "sorted-object": "~2.0.0",
    "strip-ansi": "~3.0.1",
    "tar": "~2.2.1",
    "text-table": "~0.2.0",
    "uid-number": "0.0.6",
    "umask": "~1.1.0",
    "unique-filename": "~1.1.0",
    "unpipe": "~1.0.0",
    "validate-npm-package-name": "~2.2.2",
    "which": "~1.2.10",
    "wrappy": "~1.0.2",
    "write-file-atomic": "~1.1.4"
  },
  "bundleDependencies": [
    "abbrev",
    "ansi-regex",
    "ansicolors",
    "ansistyles",
    "aproba",
    "archy",
    "asap",
    "chownr",
    "cmd-shim",
    "columnify",
    "config-chain",
    "debuglog",
    "dezalgo",
    "editor",
    "fs-vacuum",
    "fs-write-stream-atomic",
    "fstream",
    "fstream-npm",
    "glob",
    "graceful-fs",
    "has-unicode",
    "hosted-git-info",
    "iferr",
    "imurmurhash",
    "inflight",
    "inherits",
    "ini",
    "init-package-json",
    "lockfile",
    "lodash._baseindexof",
    "lodash._baseuniq",
    "lodash._bindcallback",
    "lodash._cacheindexof",
    "lodash._createcache",
    "lodash._getnative",
    "lodash.clonedeep",
    "lodash.restparam",
    "lodash.union",
    "lodash.uniq",
    "lodash.without",
    "mkdirp",
    "node-gyp",
    "nopt",
    "normalize-git-url",
    "normalize-package-data",
    "npm-cache-filename",
    "npm-install-checks",
    "npm-package-arg",
    "npm-registry-client",
    "npm-user-validate",
    "npmlog",
    "once",
    "opener",
    "osenv",
    "path-is-inside",
    "read",
    "read-cmd-shim",
    "read-installed",
    "read-package-json",
    "read-package-tree",
    "readable-stream",
    "readdir-scoped-modules",
    "realize-package-specifier",
    "request",
    "retry",
    "rimraf",
    "semver",
    "sha",
    "slide",
    "sorted-object",
    "strip-ansi",
    "tar",
    "text-table",
    "uid-number",
    "umask",
    "unique-filename",
    "unpipe",
    "validate-npm-package-license",
    "validate-npm-package-name",
    "which",
    "wrappy",
    "write-file-atomic"
  ],
  "devDependencies": {
    "deep-equal": "~1.0.1",
    "marked": "~0.3.5",
    "marked-man": "~0.1.5",
    "npm-registry-couchapp": "~2.6.12",
    "npm-registry-mock": "~1.0.1",
    "require-inject": "~1.4.0",
    "sprintf-js": "~1.0.3",
    "standard": "~6.0.8",
    "tacks": "~1.2.1",
    "tap": "~6.1.1"
  },
  "scripts": {
    "dumpconf": "env | grep npm | sort | uniq",
    "prepublish": "node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make doc-clean && make -j4 doc",
    "preversion": "bash scripts/update-authors.sh && git add AUTHORS && git commit -m \"update AUTHORS\" || true",
    "tap": "tap --reporter=classic --timeout 300",
    "tap-cover": "tap --coverage --reporter=classic --timeout 600",
    "test": "standard && npm run test-tap",
    "test-coverage": "npm run tap-cover -- \"test/tap/*.js\"",
    "test-tap": "npm run tap -- \"test/tap/*.js\"",
    "test-node": "\"$NODE\" \"node_modules/.bin/tap\" --timeout 240 \"test/tap/*.js\""
  },
  "license": "Artistic-2.0",
  "man": [
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-access.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-adduser.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-bin.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-bugs.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-build.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-bundle.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-cache.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-completion.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-config.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-dedupe.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-deprecate.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-dist-tag.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-docs.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-edit.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-explore.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-help-search.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-help.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-init.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-install-test.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-install.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-link.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-logout.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-ls.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-outdated.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-owner.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-pack.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-ping.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-prefix.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-prune.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-publish.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-README.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-rebuild.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-repo.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-restart.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-root.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-run-script.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-search.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-shrinkwrap.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-star.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-stars.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-start.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-stop.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-tag.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-team.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-test.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-uninstall.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-unpublish.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-update.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-version.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-view.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm-whoami.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man1\\npm.1",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man5\\npm-folders.5",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man5\\npm-global.5",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man5\\npm-json.5",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man5\\npmrc.5",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man5\\package.json.5",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man7\\npm-coding-style.7",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man7\\npm-config.7",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man7\\npm-developers.7",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man7\\npm-disputes.7",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man7\\npm-index.7",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man7\\npm-orgs.7",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man7\\npm-registry.7",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man7\\npm-scope.7",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man7\\npm-scripts.7",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man7\\removing-npm.7",
    "C:\\Users\\Tera_pc\\AppData\\Roaming\\npm-cache\\npm\\3.10.6\\package\\man\\man7\\semver.7"
  ],
   
  "_id": "npm@3.10.6",
  "_from": "npm@"
}

**Comment by Qix-** [comment]
I don't see chalk in there at all, which package is using it that's failing?

**Comment by sindresorhus** [comment]
Your npm version is ancient. Upgrade.

**Comment by Qix-** [comment]
Oh good catch, didn't even see that - yuhhh *ancient* is the correct term here.

**Comment by bellaj** [comment]
even i upgrade and i cleared the cache the problem persists

**Comment by Qix-** [comment]
Which version of NPM are you up to now? Which version of Node? Which build of windows 10? This looks an awful lot like an NPM bug to me if you're up to date.

**Comment by sindresorhus** [comment]
The error is because of an older version of npm not supporting `^` versions. I've seen it too many times. Pretty sure you have multiple npm versions now on your system. Try https://github.com/felixrieseberg/npm-windows-upgrade

For further npm support, use the npm issue tracker: https://github.com/npm/npm/issues

-

Locking this issue as it's not related to chalk and to limit future noise ;)
