### ISSUE TITLE
Remove __proto__ and replace it with an alternative?

### ISSUE THREAD

**Issue by CosmicWebServices** [chalk/chalk#124]
http://stackoverflow.com/questions/7509831/alternative-for-the-deprecated-proto

http://stackoverflow.com/questions/10476560/proto-when-will-it-be-gone-alternatives

**Comment by sindresorhus** [comment]
Already explained in the code why it's needed: https://github.com/chalk/chalk/blob/835ca3d9503fa987725bde711b97ca4be2386221/index.js#L40-L41

Happy to accept a PR for a better solution that doesn't hurt performance, but I doubt anyone will be able to.

**Comment by CosmicWebServices** [comment]
OK
