### ISSUE TITLE
Switch from ANSI-styles to ANSI-256-colors

### ISSUE THREAD

**Issue by ev1stensberg** [chalk/chalk#126]
https://github.com/jbnicolai/ansi-256-colors

Would it be convenient  to switch to using ansi 256 in order to have more colors provided?

**Comment by sindresorhus** [comment]
[ansi-styles](https://github.com/chalk/ansi-styles) already supports 256 colors and more. We just need to find time to do a new release and use it in Chalk.

**Comment by ev1stensberg** [comment]
Ooh, great. Any expected time? 1mth or so?

**Comment by ev1stensberg** [comment]
FWIW -- Instead of options, perhaps something like `chalk.customconfig.with.lots.of.dots(...)` we could do `chalk.extend()` and let them extend the module ( or similar ) ?
