### ISSUE TITLE
Reset order when nested

### ISSUE THREAD

**Issue by mhkeller** [chalk/chalk#127]
I was confused by the behavior of reset when nesting different styles. 

<img width="372" alt="screen shot 2016-09-02 at 4 11 20 pm" src="https://cloud.githubusercontent.com/assets/498744/18216952/f2e408ea-7127-11e6-82c8-869a0e30c27d.png">

I would expect `chalk.reset(chalk.red('hey'))` to be the normal color, similar to how `stripColor` works. However, instead it shows up as red. I would expect `chalk.red(chalk.reset('hey'))` to be red, instead of the normal color.

This change seems to be related https://github.com/chalk/chalk/issues/41

**Comment by Qix-** [comment]
Think about it.

---

> `chalk.red('hey')`

**`red`**`hey`**`/red`**

> `chalk.reset(...)`

**`reset`**`red``hey``/red`**`/reset`**

Which tells the emulator to:

1. Reset
2. Red On
3. _Hey_
4. Red Off
5. Reset

---

> `chalk.reset('hey')`

**`reset`**`hey`**`/reset`**

> `chalk.red(...)`

**`red`**`reset``hey``/reset`**`/red`**

Which tells the emulator to:

1. Red On
2. Reset (Red Off)
3. _Hey_
4. Reset
5. Red Off

---

Given the semantics, think of calls to Chalk as _wrap the input with an instruction_. If you read your calls from left to right, the output begins to make sense.

This is why the calls `chalk.red.reset(...)` will appear normal (make it red, then reset everything), whereas `chalk.reset.red(..)` will appear red (first reset everything, then make it red) -- as one might expect.
