### ISSUE TITLE
"Here without console.log for purity."

### ISSUE THREAD

**Issue by Qix-** [chalk/chalk#128]
I think this is what is throwing people off. A large portion of our tickets (and things I see on StackOverflow) are people misunderstanding how to use chalk. I think they expect `chalk.red("hello")` to output something.

The readme states `Here without console.log for purity.` which a lot of people miss (even though there's a usage block _right above it_). It might be worthwhile to just include `console.log` (or even `var log = console.log; log(...)`) in there to illustrate that chalk only returns strings with escape sequences, nothing more.

Just a thought.

**Comment by sindresorhus** [comment]
Sure. `const log = console.log; log(...` sounds good to me.
