### ISSUE TITLE
Unreadble output in one special case

### ISSUE THREAD

**Issue by fearphage** [chalk/chalk#131]
The content of this post is in reference to `xo`, but I believe that chalk is the source of the problem/issue. This was spotted as an xo issue (sindresorhus/xo#145). I traced that back to sindresorhus/eslint-formatter-pretty and now chalk.

### Copy and pasted below

I'm not sure what's special about the output from xo, but it's the only thing that seems to be affected. I cannot read the output without copying and pasting it somewhere. Here are a few screenshots:

## Normal Output

![selection_2016-09-29_170518](https://cloud.githubusercontent.com/assets/23887/18974228/71a45afa-8667-11e6-86bd-4afb5f12f4cf.png)

## Highlighted Output

![selection_2016-09-29_170539](https://cloud.githubusercontent.com/assets/23887/18974245/82eb435a-8667-11e6-84be-b7da2b53e506.png)

I've been copying the highlighted output my editor to read it. Any idea what xo is doing that's unique in this way? I've used hundreds of other cli tools including the underlying ESLint without any problems. I've used dozens of other programs that use chalk to print colorized output. I've even tried changing my local color profiles to no avail. Any help would be greatly appreciated.

## For Reference 

`xo | tee` makes the output visible although not colorized.

This is the content of the hidden output in both screenshots:

```shell
➜  ava git:(add-test-run-duration) xo

  api.js:183:2
  ⚠  183:2  Unexpected todo comment.                                          no-warning-comments

  lib/assert.js:15:1
  ⚠   15:1  This function has too many parameters (5). Maximum allowed is 4.  max-params

  lib/logger.js:94:2
  ⚠   94:2  Unexpected todo comment.                                          no-warning-comments

  lib/reporters/mini.js:178:4
  ⚠  178:4  Unexpected todo comment.                                          no-warning-comments
  ⚠  305:1  Unexpected todo comment.                                          no-warning-comments

  lib/test.js:42:2
  ⚠   42:2  Unexpected todo comment.                                          no-warning-comments

  test/cli.js:96:3
  ⚠   96:3  Unexpected todo comment.                                          no-warning-comments
  ⚠  141:3  Unexpected todo comment.                                          no-warning-comments

  test/promise.js:129:1
  ⚠  129:1  Unexpected todo comment.                                          no-warning-comments

  9 warnings
```

## System Information

OS: Ubuntu 16.04 x64
Terminal: Byobu terminal
`$TERM`: `screen-256color`
`$SHELL`: `/usr/bin/zsh`
`[ -t 1 ] && echo yes || echo no`: `yes`

**Comment by Qix-** [comment]
This is most definitely a bug in your terminal emulator (Byobu). Please file a bug with them.

**Comment by sindresorhus** [comment]
Yeah, looks like your terminal can not handle `chalk.hidden.dim.gray()`, probably the `hidden` part: https://github.com/sindresorhus/eslint-formatter-pretty/blob/d5961796a238c463fd5d2b3b1ac8d5208d34e44e/index.js#L99

**Comment by fearphage** [comment]
Thanks for the input!

Do you know if this works in other 256 color environments?

**Comment by Qix-** [comment]
Yes, it definitely does.

**Comment by fearphage** [comment]
Excellent! Thanks again.

**Comment by gunar** [comment]
@fearphage did you get this fixed? I'm having the same problem on `zsh + termite +  tmux`.

**Comment by gunar** [comment]
In case anyone else finds this post, first test your terminal emulator.
```
echo -e "Normal \e[8mHidden \e[28mNormal"
```
should print
![hidden style](http://misc.flogisoft.com/_media/bash/colors_format/vt100_format_28_reset_hidden.png)

[source](http://misc.flogisoft.com/bash/tip_colors_and_formatting)

**Comment by paulmolluzzo** [comment]
> In case anyone else finds this post, first test your terminal emulator.
> 
> echo -e "Normal \e[8mHidden \e[28mNormal"

For anyone who's made it this far down the rabbit hole and is seeing only the first `Normal` in the test listed above, see [this Q/A for fixes](http://unix.stackexchange.com/questions/1045/getting-256-colors-to-work-in-tmux#1098).

It took some playing for me to get this working, and in the end I aliased `tmux` to `TERM=screen-256color-bce tmux`. I already had `set -g default-terminal "screen-256color"` in my .tmux.conf file.
