### ISSUE TITLE
"Unresolved function or method" inspection in WebStorm/PHPStorm IDE (JetBrains IntelliJ IDEA)

### ISSUE THREAD

**Issue by Alcotana** [chalk/chalk#132]
There is a weak warning in PHPStorm when using colors:  "Unresolved function or method...". Maybe you should use JSDoc in your source code to fix this or define these methods somehow. Do something, please!
____________________________
![screenshot_117](https://cloud.githubusercontent.com/assets/1378484/19235886/089b9124-8efd-11e6-8ec8-3c17fa6f26d2.png)
![screenshot_118](https://cloud.githubusercontent.com/assets/1378484/19235892/0da5c306-8efd-11e6-9b7d-b8cce94fbbb0.png)

**Comment by sindresorhus** [comment]
Open an issue on WebStorm. It seems like a weakness in their JavaScript analysis. Libraries shouldn't have to adapt to WebStorm.

**Comment by Alcotana** [comment]
Temp fix:
![screenshot_119](https://cloud.githubusercontent.com/assets/1378484/19236639/241d364c-8f01-11e6-9235-5fadd1ed133a.png)

**Comment by sindresorhus** [comment]
You should still open a WebStorm issue so other people don't have to get hit by this in the future.

**Comment by alexvicegrab** [comment]
I have opened an issue here, if anyone else wants to contribute, feel free:

https://youtrack.jetbrains.com/issue/WEB-27212

**Comment by zeeshanu** [comment]
Require the chalk library like this:
```
const chalk = require('chalk').default;
```

**Comment by mblpz** [comment]
> Require the chalk library like this:
> 
> ```js
> const chalk = require('chalk').default;
> ```
how great. any insights on this topic, is it a fix for webstorm or a fix for node, ts, etc?

**Comment by Chiff** [comment]
> Require the chalk library like this:
> 
> ```js
> const chalk = require('chalk').default;
> ```

it works. can you explain why?

**Comment by ziishaned** [comment]
@Chiff see the following [file](https://github.com/chalk/chalk/blob/master/index.js) which is exporting everything as default. Because of that, we have to call 'default' property on require function.

**Comment by mishuvs** [comment]
For me the `.default` property isn't working for the latest version of chalk (which is 3.0.0 at the time of this comment).
For the version 2.4.1 it does work correctly but Webstorm shows the lint warning: `Method expression is not a function type`.

**Comment by pastuh** [comment]
Funny how this bug still not fixed.. 
"The smartest JavaScript IDE"..

it should be Webstorm 2000 , not 2019 ...

**Comment by bytekoder** [comment]
Wow... Can't believe that adding the default keyword actually worked. Thanks!!

**Comment by Sotatek-HoangNguyen2** [comment]
![image](https://user-images.githubusercontent.com/76962626/108819046-e59dfc80-75ec-11eb-8a13-ca8db6934ee4.png)
Still the code run

**Comment by Qix-** [comment]
That error message has nothing to do with Chalk.
