### ISSUE TITLE
Bright colours

### ISSUE THREAD

**Issue by simon-p-r** [chalk/chalk#134]
Hi

Just wondering whether you plan to support bright colours, in particular red is illegible on Windows.

Thanks
Simon

**Comment by Qix-** [comment]
Does `chalk.bold.red('hello')` not work for you?

**Comment by simon-p-r** [comment]
Yes it is brighter, just wondering why api is like that is more verbose than just ```chalk.boldRed```?

**Comment by sindresorhus** [comment]
@simon-p-r It's **one** extra character and the same amount of key presses.

**Comment by simon-p-r** [comment]
Sure but it is not intuitive

**Comment by Qix-** [comment]
Because `bold` can exist on its own, and on Windows bold directly influences the text color.

**Comment by simon-p-r** [comment]
Please pardon my ignorance but what does that mean?

**Comment by Qix-** [comment]
Meaning you can do `chalk.bold(...)` by itself. On Windows, the bold flag is the thing that makes the colors brighter.
