### ISSUE TITLE
`chalk@1.1.3` does not include commits from `chalk@1.1.2`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [chalk/chalk#135]
[The commits for 1.1.3](https://github.com/chalk/chalk/commits/v1.1.3) don't seem to include all of [the commits for 1.1.2](https://github.com/chalk/chalk/commits/v1.1.2).  I think that's why the package from npm seems to pull `supports-color@2.0.0`.

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/chalk/chalk/issues/110.

**Comment by wtgtybhertgeghgtwtg** [comment]
Sorry about that.
