### ISSUE TITLE
Isn't there a Blink?

### ISSUE THREAD

**Issue by florianb** [chalk/chalk#139]
I was searching for a blink modifier. Is there a reason why Chalk isn't providing a `.blink`-modifier?

Thanks in advance! 😄  💐

**Comment by sindresorhus** [comment]
Yes, it's intentionally left out as it's annoying for the user.

See: https://github.com/chalk/ansi-styles/pull/6

**Comment by florianb** [comment]
Thanks a lot - I could have expected that! 😃

**Comment by Qix-** [comment]
Also, it's pretty much a dead render mode. Blink isn't supported many places at all, and indeed it's incredibly annoying for the user.
