### ISSUE TITLE
Not working on cygwin

### ISSUE THREAD

**Issue by souravray** [chalk/chalk#141]
Chalk styling on cygwin is not getting applied.

**Comment by sindresorhus** [comment]
Cygwin is not officially supported by Node.js, nor this module.

**Comment by souravray** [comment]
Thanks Sindre, for letting me know. What I understand is Node.js support for Cygwin is completely a different issue, you don't need to refer it to justify your modules limitations.

**Comment by sindresorhus** [comment]
@souravray No, it's exactly that. It's a limitation in Node.js: https://github.com/chalk/supports-color/issues/36

**Comment by souravray** [comment]
Thanks. Don't understand the issuecompletely, though.
What is the possible workaround?  ANSI escape codes seems to work on Cygwin.

**Comment by Qix-** [comment]
nodejs/node#3006

Detecting that the terminal supports color is not easy. Cygwin cheats with its use of PTY's (from what I gather from that thread) and thus makes Node think it's not a real terminal.

Keep updating Cygwin and hope that they fix it, or switch to MinGW.

Closing to keep the chatter down; feel free to browse the two issues we linked :)
