### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 'chalk.blue('Hello world!')')  I get this on docker ( ubuntu ) 

### ISSUE THREAD

**Issue by jpca999** [chalk/chalk#144]
/var/www/simple_casper/node_modules/chalk/index.js:8
  /var/www/simple_casper/node_modules/chalk/index.js:117
TypeError: 'undefined' is not a function (evaluating 'chalk.blue('Hello world!')')

![image](https://cloud.githubusercontent.com/assets/1026325/24075462/7f237ec0-0bf2-11e7-915e-e5054212a6d8.png)

**Comment by Qix-** [comment]
Looks like a super outdated version of Chalk. There aren't 117 lines in the current version of Chalk anymore :)

**Comment by jpca999** [comment]
@Qix- 
I installed it via terminal , npm install --save chalk
my package json says: 
    "chalk": "^1.1.3",

is this good enough ?

**Comment by Qix-** [comment]
Chalk doesn't work in the browser. IIRC Casper is a headless browser, no?

**Comment by sindresorhus** [comment]
As @Qix- said, Chalk is for Node.js.

**Comment by jpca999** [comment]
thx
