### ISSUE TITLE
[FIX INBOUND] chalk.bold does not reset on Windows

### ISSUE THREAD

**Issue by alancnet** [chalk/chalk#145]
![image](https://cloud.githubusercontent.com/assets/2042102/24083248/e836bda2-0c90-11e7-9485-2b27df35848f.png)

**Comment by Qix-** [comment]
Which version of Windows are you running?

**Comment by sindresorhus** [comment]
And what terminal app?

**Comment by alancnet** [comment]
Windows 10, cmd.exe:

![image](https://cloud.githubusercontent.com/assets/2042102/24174161/7dfaf85a-0e4c-11e7-905f-9f90828852d3.png)

**Comment by Qix-** [comment]
Could you please run `require('util').inspect(chalk.bold('during'))` on each of those?

**Comment by alancnet** [comment]
cmd.exe:

```
> require('util').inspect(require('chalk').bold('during'))
'\'\\u001b[1mduring\\u001b[22m\''
```

powershell:

```
> require('util').inspect(require('chalk').bold('during'))
'\'\\u001b[1mduring\\u001b[22m\''
```

Bash on Ubuntu on Windows:

```
> require('util').inspect(require('chalk').bold('during'))
'\'\\u001b[1mduring\\u001b[22m\''
```

XTerm on Bash on Ubuntu on Windows:

```
> require('util').inspect(require('chalk').bold('during'))
'\'\\u001b[1mduring\\u001b[22m\'
```

**Comment by Qix-** [comment]
@sindresorhus I wonder if the new windows ANSI escapes don't support `22m`.

**Comment by bluelovers** [comment]
this bug need use styles.reset = \u001B[0m

we can maybe can use close = \u001B\[0;22m 
or use \u001B[0m wrap bold => \u001B[0m + bold + \u001B[0m


![20170324-180604-4](https://cloud.githubusercontent.com/assets/167966/24290074/9f2f3d64-10be-11e7-8f22-520678d7165b.png)

```javascript
const chalk = require('chalk');

function cb(...argv)
{
	console.log(...argv);
	//console.log(`\n-----------------------`);

	let line1 = '';
	let line2 = '';

	for (let i = 1 ; i <= 7 ; i++)
	{
		line1 += `\u001b[3${i}m 3${i} \u001b[39m`;
		line2 += `\u001b[9${i}m 9${i} \u001b[39m`;
	}

	console.log(line1);
	console.log(line2);

	//console.log(`-----------------------`);
};

// no bug
cb(1, `no bug`);

console.log(`\n@@@ bug start\n`);
console.log(chalk.bold(`chalk.bold`), chalk.bold._styles);
process.stdout.write(`\n`);

cb(2, `bugged`);

// bug start
process.stdout.write(`\n`);
console.log(chalk.blue(`chalk.red`), chalk.blue._styles);
process.stdout.write(`\n`);

cb(3, `bugged`);

process.stdout.write(`\n`);
console.log(chalk.yellow.bold(`chalk.yellow.bold`), chalk.yellow.bold._styles);
process.stdout.write(`\n`);

// bug end
console.log(`@@@ bug end\n`);

// no bug
process.stdout.write(chalk.styles.reset.open);

cb(4, `@@@ no bug`);

process.stdout.write(chalk.styles.reset.close);

```

**Comment by sindresorhus** [comment]
> I wonder if the new windows ANSI escapes don't support 22m.

If it's only an issue with Bash on Windows it should be reported here: https://github.com/Microsoft/BashOnWindows If this is the case, I don't think we should fix to pressure them to fix it soon.

**Comment by Qix-** [comment]
Agreed. Using `[0m` would break things anyway.

**Comment by alancnet** [comment]
It's not only an issue with Bash on Windows. You'll see my first example was standard regular windows command prompt. My second example was powershell.

**Comment by Qix-** [comment]
@alancnet what does `echo %TERM%` give you in the command prompt? Anything?

**Comment by fr-esco** [comment]
![image](https://cloud.githubusercontent.com/assets/4931297/25338984/63e7be74-2901-11e7-8089-bf49d8cf9196.png)
![image](https://cloud.githubusercontent.com/assets/4931297/25339000/7835380c-2901-11e7-8354-b17dccba0489.png)

I'm using 
![image](https://cloud.githubusercontent.com/assets/4931297/25339018/8803e364-2901-11e7-849b-786347e587a6.png)

**Comment by Qix-** [comment]
Do you happen to have a C (MSVC) compiler on hand?

Could you try the following if you do?

```c
#include <stdlib.h>
#include <io.h>
#include <windows.h>

int main(void) {
    puts("Before: \x1b[1mbold\x1b[21m nobold");
    HANDLE hOut = GetStdHandle(fd == 1 ? STD_ERROR_HANDLE : STD_OUTPUT_HANDLE);
    DWORD dwMode = 0;
    GetConsoleMode(hOut, &dwMode);
    dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
    SetConsoleMode(hOut, dwMode);
    puts("After: \x1b[1mbold\x1b[21m nobold");
    return 0;
}
```

I haven't tried that, but I remember doing some research for my build system and coming across your _specific_ version of windows:

- If before build **10586**, no color is supported.
- Between **10586** up to (not including) build **14393**, virtual terminal processing was turned on by default.
- Starting build **14393**, virtual terminal processing was off by default and needed to be turned on.

I literally have code in there that selects this specific version - thanks for thinking to post it.

**Comment by ViceIce** [comment]
Hi,

I have the same problem (using powershell). 

![image](https://cloud.githubusercontent.com/assets/1798109/26542125/0af9b768-4459-11e7-84f9-2852a06e1988.png)

![image](https://cloud.githubusercontent.com/assets/1798109/26542082/dd2dc90a-4458-11e7-9634-a705384135c9.png)

**Comment by ViceIce** [comment]
The code 21 and 22 seems be be ignored by cmd /powershell

![image](https://cloud.githubusercontent.com/assets/1798109/26545628/a15b6dd4-4466-11e7-80bc-5e666708ca08.png)

**Comment by ViceIce** [comment]
Can we implement some workaround for that?
Something like https://gist.github.com/ViceIce/56f7662b74fba4ea12a48650c23f81f0

**Comment by ViceIce** [comment]
Here is a list [Console Virtual Terminal Sequences](https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032.aspx) of supported codes.

**Comment by Qix-** [comment]
Tbh I'm not sure how to support this without breaking _chalk_. It's Microsoft's ~~ignorance~~ responsibility, ultimately.

I'll submit a ticket and see how fast they'll be able to turnaround on this, but there really isn't a way to support this without re-writing Chalk to output a _ton_ of escapes and be ridiculously stateful.

**Comment by sindresorhus** [comment]
Closing as we're not going to work around the usual Microsoft brokenness. Follow https://github.com/Microsoft/BashOnWindows/issues/2174 instead.

**Comment by ViceIce** [comment]
Ok, for now the only workaround is to use legacy console mode. :-(

**Comment by Qix-** [comment]
Re-opening for visibility.

### A fix for this issue is inbound on Microsoft's end and an update will be pushed within the next few weeks.

Thanks for reporting this and for everyone's involvement. I will close this sometime after the Fall Creator's update.

:heart:

**Comment by Qix-** [comment]
This has landed in the Fall Creator's Update - thanks again for everyone's involvement and massive hat-tip to @zadjii-msft for the continued prompt responses!

**Comment by xPaw** [comment]
I'm on latest Windows 10 insider build (17110) and it still appears that bold/dim are not handled correctly both in cmd and powershell.

Here's what I'm seeing:
![02-173210979](https://user-images.githubusercontent.com/613331/36912788-8c25e772-1e50-11e8-8dd8-321b91a446eb.png)

**Comment by Qix-** [comment]
Closing as this has been resolved for a while now. Thanks to the Microsoft team for an all-things-considered quick and painless resolution.
