### ISSUE TITLE
Remove ANSI colors using Chalk

### ISSUE THREAD

**Issue by Nihilivin** [chalk/chalk#147]
Hi there! Thanks for this nice module.

I have a program writing to stdout using ANSI colors, and I use its output in a node program. The stdout I get from my exec contains the colors when I log it. Is it possible to use chalk to remove all ANSI styles from my string?

Thank you

**Comment by sindresorhus** [comment]
https://github.com/chalk/strip-ansi

**Comment by Nihilivin** [comment]
Yeah right, and I found too tons of solutions to do it. But wouldn't be better if this was included in the Chalk module directly?

**Comment by Qix-** [comment]
I believe it used to be, but it's not used enough to warrant the expansion of scope/violation of single responsibility principles.

**Comment by sindresorhus** [comment]
Exactly

**Comment by basickarl** [comment]
strip-ansi library does not strip the colors which are appended by chalk. Have yous tested it?
