### ISSUE TITLE
TypeScript type definition

### ISSUE THREAD

**Issue by Jameskmonger** [chalk/chalk#148]
It would be good to have the typings for chalk distributed with the npm package:

- Easier to use with TypeScript (no [external dependencies](https://www.npmjs.com/package/@types/chalk) needed)
- Easier to ensure that the typings are in sync with the library
- Easier for users to be more confident that the typings are in sync

**Comment by sindresorhus** [comment]
I usually don't do this, for reasons outlined in https://github.com/sindresorhus/ama/issues/439, but since Chalk is one of the most popular packages on npm, I'm gonna accept it if you or someone else can commit to maintain it.

**Comment by basedjux** [comment]
Since I write quite a bit of TypeScript, I could write a typing for Chalk and maintain it... That wouldn't be an issue.

**Comment by sindresorhus** [comment]
@basedjux That would be awesome. Pull request welcome :)

**Comment by basedjux** [comment]
@sindresorhus cool! 
I'll get working on that 😄

**Comment by basedjux** [comment]
Never mind @sindresorhus, looks like someone beat me to it writing a definition: 
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/chalk

**Comment by sindresorhus** [comment]
That one is very outdated.

**Comment by basedjux** [comment]
Ah yeah it is, 3 months.
Okay I'll write the updated one.

**Comment by sindresorhus** [comment]
It's based on a more than 2 year old Chalk version.

**Comment by basedjux** [comment]
Yeesh yeah that's scary outdated.

**Comment by Jameskmonger** [comment]
@basedjux @sindresorhus Is this going to be distributed **with** the npm package? I think that's the best way to create a seamless experience.

**Comment by sindresorhus** [comment]
Yes

**Comment by Qix-** [comment]
@basedjux We just bumped to v2 by the way :)

**Comment by basedjux** [comment]
@Qix- Yeah, I saw the tweet! 
I'll be looking at those API changes.

**Comment by sindresorhus** [comment]
This was added in [v2.2.0](https://github.com/chalk/chalk/releases/tag/v2.2.0).
