### ISSUE TITLE
Yellow + Bold not working

### ISSUE THREAD

**Issue by jacc** [chalk/chalk#149]
My code, `${Chalk.yellow.bold(`[WARN] =>`)}`, does not work. It defaults to the bold gray. Everything else (underline, etc.) works with yellow.

**Comment by Qix-** [comment]
Code? Screenshot? Operating system? Terminal program (iTerm, terminal.app, command prompt)?

The fact millions of people use our package every day without any problems doesn't help us narrow down your specific problem without _much_ more information.

**Comment by jacc** [comment]
Code:
```js
client.log = function log(text, type) {
  if (!type) console.log(`${Chalk.cyan(`[${moment().format('YYYY-MM-DD HH:mm:ss')}]:`)} ${Chalk.bold(`[INFO] =>`)} ${text}`);
}
```

Screenshot: https://owo.solutions/ebb3d3.png (first pic is underline, second is bold.)

MacOS.

iTerm2.

**Comment by Qix-** [comment]
I'm on iTerm2 and Mac os. Works fine for me.

<img width="757" alt="screen shot 2017-04-30 at 1 03 05 pm" src="https://cloud.githubusercontent.com/assets/885648/25567562/6a6f36de-2da5-11e7-9df2-f84c1275f778.png">

Could you try creating a new iTerm2 profile (just an empty one, don't duplicate it) and trying you test again?

Also, could you do `FORCE_COLOR=1 node /path/to/your/program.js | cat -v` and show the output here?

**Comment by jacc** [comment]
```js
^[[36m[2017-04-30 16:11:36]:^[[39m ^[[33m^[[1m[WARN] =>^[[22m^[[39m Ready.
`
That's what force color returns.

Seems like using Solarized Dark is what messed me up.
