### ISSUE TITLE
dim and bold do not play together nicely...

### ISSUE THREAD

**Issue by 0phoff** [chalk/chalk#156]
I am creating a small CLI to manage todo lists, and I am using your package to output the data!
I use chalk.dim to print out the description and it works, but there is a strange bug when you mix dim and bold strings:
```javascript
console.log( chalk.dim('this is dim ' + chalk.bold('and bold') + ' not bold' );
```
the 'not bold' part is still displayed bold (see picture)...
Not too sure if its a chalk issue or if it is my terminal, and I also dont know how to view the raw escape codes to try and debug this! I tried piping the output to a file, but then chalk doesnt use color codes.. 🤡 
Let me know what I can do to help debug this!

![chalk_error2](https://user-images.githubusercontent.com/11853089/27051557-d2f9c4ac-4fb6-11e7-96c8-dc1a5e385d83.png)

ps: I am using bash inside the gnome-terminal 😸

**Comment by Qix-** [comment]
Unfortunately, `dim` and `bold` are antonyms in the world of TTY styling. They are both shut off with the code `22m`. Unfortunately, there's very little Chalk can do about this.

If you were on windows, you'd see even worse effects 💃 I recommend using colors instead of `dim` in this case.

Good question :)

**Comment by 0phoff** [comment]
Aha ok thanks for the answer man!! I will change it to a color instead of using dim!
Do you know of any way you can see the color escape codes in the output? (like, is there a chalk debugging mode or so?) That way, if I ever have another weird thing happening, I can debug it myself with the escape codes! 👍

**Comment by Qix-** [comment]
```
FORCE_COLOR=1 node ./your/script.js | cat -v
```
