### ISSUE TITLE
Windows colour workaround breaking...on Windows

### ISSUE THREAD

**Issue by atrauzzi** [chalk/chalk#157]
I only happened upon this because the systemjs babel plugin is using chalk.  See this ticket here: https://github.com/systemjs/plugin-babel/issues/80

Looks like `undefined.open` isn't a thing.

**Comment by Qix-** [comment]
I don't see anything in that stack trace that has anything to do with Chalk. Could you post the relevant code?

**Comment by guybedford** [comment]
The issue here was SystemJS builder support for the pattern in ansiStyles:

```js
Object.defineProperty(module, 'exports', {
  get: createExports();
});
```

I've managed to find a workaround for the underlying use case for now at least.

**Comment by Qix-** [comment]
@sindresorhus why were we doing this again?

**Comment by sindresorhus** [comment]
@Qix- It's to make immutable. You're the one that added it: https://github.com/chalk/ansi-styles/pull/12 😛
