### ISSUE TITLE
chalk.bgHex is not a function

### ISSUE THREAD

**Issue by dschinkel** [chalk/chalk#158]
I must be missing something really dumb but:

```
const chalk = require('chalk'),
  _ = require('lodash'),
  info = chalk.yellow,
  green = chalk.green,
  script = chalk.bgHex('#ebd2f8')
```

**Error**: `chalk.bgHex is not a function`

????  why?

"chalk": "^1.1.3", is set in my package.json and the others work (green, info, work fine).

**Comment by sindresorhus** [comment]
Because it's not released yet.

**Comment by dschinkel** [comment]
hmm then why is it in the docs?

**Comment by Qix-** [comment]
@dschinkel It's not released on NPM. It's been merged onto master on Github, however. If you check NPM, it is absent on their (as of this writing) since it hasn't been released onto NPM yet.

Give us a few hours, we're making tweaks to many parts of Chalk right now.

**Comment by dschinkel** [comment]
ok thanks...I am thinking though next time maybe wait till npm resolves the update before updating the readme...just a suggestion.

**Comment by Qix-** [comment]
@dschinkel You have to update the readme before you publish to NPM. This has been standard practice across thousands of modules for years now.

**Comment by dschinkel** [comment]
got it!...thanks!
