### ISSUE TITLE
Doesn't work in Git Bash on Windows.

### ISSUE THREAD

**Issue by wzup** [chalk/chalk#162]
Here is an original issue https://github.com/facebook/jest/issues/3877

[Jest ](https://github.com/facebook/jest)uses your plugin to color output. 
But option `{ "colors": true }` doesn't work when set in their config file. Only as command line `--colors`. Why is it so? How to make it work from a config file?

**Comment by Qix-** [comment]
Like you said yourself, it's _their_ configuration file. I have no idea why _their_ code isn't working like you expect it to.

They explained very well why `--colors` works like it does. However, for the configuration problem, please take it up with them.

**Comment by wzup** [comment]
LOL. They claim that it is `chalk` issue and refer to this repo. You claim that it is their issue.
No worries both. I fixed it already.

**Comment by Qix-** [comment]
No, they told you exactly what the problem was. _You_ decided to bring the issue here.

I'm glad you fixed the problem.
