### ISSUE TITLE
Flow type definition

### ISSUE THREAD

**Issue by sindresorhus** [chalk/chalk#165]
Same as #148, we would be happy to bundle a [Flow](https://flow.org) type definition if anyone wants to do a PR.

**Comment by sindresorhus** [comment]
We now have a TypeScript type definition, so it should be pretty easy to port it to Flow.

**Comment by 0vidiu** [comment]
Hello,

I'm getting these error messages from Typescript:
```TS2339: Property 'inverse' does not exist on type```
```TS2339: Property 'bgHex' does not exist on type```

Maybe those are omitted by mistake from the type definitions or I'm using it wrong.
