### ISSUE TITLE
Couldn't find any versions for "chalk" that matches "^2.0.1"

### ISSUE THREAD

**Issue by greygatch** [chalk/chalk#166]
Trying to deploy a project, and I see this error. I notice that >2.0.0 was released ~18 hours ago. Does not appear to locate most recent releases.

> Please choose a version of "chalk" from this list: (Use arrow keys)
> ❯ 1.1.3 
>   1.1.2 
>   1.1.1 
>   1.1.0 
>   1.0.0 
>   0.5.1 
>   0.5.0

**Comment by Qix-** [comment]
Not sure how this is the case. Please check whatever it is you're using to deploy. If you're behind a package cache for your company, please make sure it's pulling. Chalk is definitely released on NPM.
