### ISSUE TITLE
Not working with double slash

### ISSUE THREAD

**Issue by gempain** [chalk/chalk#170]
Hello,

I cannot seem to succeed chalking strings that contain `//`... (tested on Windows).

```
chalk.red('http://test')
```

Won't be red for me. Any idea how to escape these chars ?

Cheers;

**Comment by sindresorhus** [comment]
Tested on both Windows and macOS and seems to work fine. Submit a failing test and we'll look into it.

**Comment by gempain** [comment]
Well, you are right, the problem was in Webstorm (2017.1.3). The embedded terminal will not show colors when the string contains `//`.
