### ISSUE TITLE
Can not color URLs?

### ISSUE THREAD

**Issue by JasonBoy** [chalk/chalk#172]
I want to color a url on terminal, like `chalk.green('http://127.0.0.1:3000')`, but looks like it did not work, and I tried some others, it seems that once you have a string which "looks like" a url with domain, chalk won't color that.
Is this by design, or I did not use it properly? :(

Thx for the help

**Comment by Qix-** [comment]
Without any other code, I have no idea what your problem might be. Could you post some more context? Remember you have to actually print out the code. `console.log(chalk.green(...))`, as is evident by [the README on the front of this repository](/chalk/chalk#readme).

**Comment by JasonBoy** [comment]
Looks like the problem is with the WebStorm terminal that I used, I wrote a demo and directly run that on iterm terminal, it works.
on Iterm:
<img width="244" alt="screen shot 2017-07-10 at 2 48 15 pm" src="https://user-images.githubusercontent.com/2911620/28005734-d17b9050-657e-11e7-9550-c19c153bb172.png">
on WebStorm terminal:
<img width="205" alt="screen shot 2017-07-10 at 2 48 06 pm" src="https://user-images.githubusercontent.com/2911620/28005744-ddbf9fa0-657e-11e7-9bf5-ee7d23b3e79b.png">

**Comment by Qix-** [comment]
Because webstorm probably doesn't use a peudoterminal and thus making chalk think it's being piped, disabling chalk. Try `FORCE_COLORS=1 node chalk.js`.

**Comment by JasonBoy** [comment]
Still did not work for webstorm, but anyway this is a webstorm issue, not chalk.

**Comment by sindresorhus** [comment]
https://www.jetbrains.com/help/webstorm/reporting-issues-and-sharing-your-feedback.html#d151698e123 ;)

**Comment by JasonBoy** [comment]
thx, already fired an issue for them: [WEB-27701](https://youtrack.jetbrains.com/issue/WEB-27701)

**Comment by davidhellmann** [comment]
PHPStorm same problem :D
