### ISSUE TITLE
Error occurs from Webpack's UglifyJs plugin

### ISSUE THREAD

**Issue by wellyshen** [chalk/chalk#173]
Hi I upgraded chalk to V2. And I get the following error from the UglifyJs plugin of Webpack :

> ERROR in vendor.97eed5df.js from UglifyJs
Unexpected token: punc (,) [./node_modules/chalk/templates.js:6,0][vendor.97eed5df.js:12371,8]

And I found issue is because of some `.js` files of chalk are wrote by es6, however after I included the following files into the process of `babel` transforming as following, then the issue is fixed. Does any suggestion for it?

```javascript
// ...
{
        test: /\.jsx?$/,
        // exclude: /node_modules/,
        include: [
          path.join(process.cwd(), './src'),
          path.join(process.cwd(), './node_modules/chalk'),
          path.join(process.cwd(), './node_modules/ansi-styles/index.js'),
        ],
        loader: 'babel',
        options: {
          cacheDirectory: isDev,
          babelrc: false,
          presets: [['es2015', { modules: false }], 'react', 'stage-0'],
          plugins: ['react-hot-loader/babel'],
        },
      }
// ...
```

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/ama/issues/446

Check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by Qix-** [comment]
Also uglify just isn't great. Use `babili` Instead, or what Sindre suggested.

Uglify doesn't work with the new ES6/ES7 syntax.
