### ISSUE TITLE
Newline character (\n) in tagged template literals becomes "n"

### ISSUE THREAD

**Issue by nazrhyn** [chalk/chalk#177]
From the comment here: https://github.com/chalk/chalk/issues/12#issuecomment-315685346
> When using tagged template literals, `\n` does not work => `n` is output and there is no line break.

I just ran into this myself, so I figured I'd do as @Qix- asked.

------

It looks like part of your processing is eating the `\`. Multi-line template literals (or anything similar in other languages) always seem like a cool idea until you have code like this...

```js
function run() {
	if (something) {
		if (somethingElse) {
			console.log(`this is the first line
			this is the second`);
		}
	}
}
```

...producing the output...

```
this is the first line
			this is the second
```

...which isn't optimal. You could pull the second line all the way to the margin, but that'd never fly with formatters or linters.

Maybe there's a better way for chalk to detect character escapes (certain character escapes) and not eat them?

As a workaround, it is possible to do something like this, though it's not very attractive:

```js
console.log(chalk`{red NO} but...${'\n'}really, {green YES}`);
```

**Comment by Qix-** [comment]
I know exactly why this happens and I agree it's not optimal.

@sindresorhus thoughts about this? I can fix it but I'm worried about how we'd release.

**Comment by nazrhyn** [comment]
Interestingly, while using your library even more (the first _good_ use of tagged template literals I've ever seen -- so slick and clean :+1:), I found out some more constraints for that workaround:

If a color block precedes it, it works:
```js
> console.log(chalk`testing {blue hi}${'\n'}there`)
testing hi
there
```

If a color block follows it, it eats the `\n`:
```js
> console.log(chalk`testing hi${'\n'}{blue there}`)
testing hithere
```

Probably doesn't matter if you know how you think you'd like to change it; but, I thought I'd mention it anyway.

**Comment by sindresorhus** [comment]
> thoughts about this? I can fix it but I'm worried about how we'd release.

It would be a patch release, it's a bug fix.

**Comment by jtenner** [comment]
Hey guys. Just contributing what I can:

![image](https://user-images.githubusercontent.com/3761339/28528047-9171798e-705a-11e7-9f8e-ad0abbf85f0d.png)

This converts to:

![image](https://user-images.githubusercontent.com/3761339/28528063-a05f789c-705a-11e7-84de-5301f1395061.png)

As you can see it strips out the newline character. I verified it goes into the function and is stripped out when it returns. Is there any way I can help?

**Comment by LitoMore** [comment]
```javascript
const a = '\\'
chalk`{blue ${a}}`
```
Chalk will crash in this case.
