### ISSUE TITLE
Strange characters in file transport

### ISSUE THREAD

**Issue by dland512** [chalk/chalk#179]
I'm using chalk with [electron-log](https://github.com/megahertz/electron-log) and it works really well in the terminal window. Super cool.

The problem is that I also have my logs going out to a file and in that case I'm seeing weird characters apparently related to the colors.

```
var chalk = require('chalk');
var log = require('electron-log');
log.error('logging without chalk');
log.error(chalk.red('logging with chalk'));
```

> [2017-07-20 14:14:23:0186] [error] logging without chalk
> [2017-07-20 14:14:23:0189] [error] [31mlogging with chalk[39m

Is this just a limitation of the system?

**Comment by sindresorhus** [comment]
Chalk is IMHO doing the correct thing here. It can't possibly know that you're also going to save the output to a file. It's up to `electron-log` to remove ansi escape codes (the `�[31m`). Open an issue on `electron-log`. It could use [`strip-ansi`](https://github.com/chalk/strip-ansi).

**Comment by dland512** [comment]
Makes sense, thanks for the info.

**Comment by sindresorhus** [comment]
No, I think `electron-log` should handle that.
