### ISSUE TITLE
Move to AVA for testing

### ISSUE THREAD

**Issue by sindresorhus** [chalk/chalk#181]
Let's move all testing related things into a `test` directory. The current Mocha test groups should just be separate test files.

**Comment by sindresorhus** [comment]
// @kevva, in case you're interested.

**Comment by tdeschryver** [comment]
Hi, if its OK for both of you I would like to take this one. (Wanna get familiar with `ava` :smile:)

**Comment by sindresorhus** [comment]
@tdeschryver Go ahead :)

**Comment by kevva** [comment]
Oh, sorry. I've already finished up, lol. But go ahead and I can review your PR later.

**Comment by sindresorhus** [comment]
@kevva If you already did it, you can just submit it. No point in having double work done.

**Comment by tdeschryver** [comment]
No problem! I'll just take a look at your PR.

**Comment by kevva** [comment]
Alright, I'll do a PR then.

**Comment by sindresorhus** [comment]
@tdeschryver Some other project that needs to be converted from Mocha to AVA if you're interested:

- https://github.com/yeoman/stringify-object
- https://github.com/yeoman/update-notifier
- https://github.com/yeoman/insight
- https://github.com/sindresorhus/string-length

**Comment by tdeschryver** [comment]
@sindresorhus I'll try to send a PR a day :)
