### ISSUE TITLE
The {} placeholder removes the linebreak that's just before it

### ISSUE THREAD

**Issue by vibl** [chalk/chalk#184]
In a multiline chalk template string, the {} placeholder removes the linebreak that's just before it (i.e. if it is at the beginning of any line).

So for example:
``` 
chalk`The first line
{red The second line in red}`
```
produces:
```
The first lineThe second line in red
```
when it should produce:
```
The first line
The second line in red
```

This bug does not happen if the {} placeholder is located anywhere after the beginning of a line.

I don't know if this is related to #177 or #12 but at first glance this seems like a distinct bug to me.

**Comment by jtenner** [comment]
I had to fix this by replacing all the `\n`  and `\r\n` characters with `\r` in order for my code to work properly, but it was easy enough. 

Definitely want a fix for this.

**Comment by nazrhyn** [comment]
May be distinct, but I suppose we'll have to see where the fix for the other one goes. I think the comment I made in #177 is what you're saying here.

https://github.com/chalk/chalk/issues/177#issuecomment-316553329
