### ISSUE TITLE
Extend chalk tagged template string behavior

### ISSUE THREAD

**Issue by k15a** [chalk/chalk#185]
Hey,

I would like to extend the behavior of the new tagged template string feature of chalk. I was hoping that I can call `chalk.apply()` with the arguments of my own tag and transform the output even more. Unfortunately, this is not working because there is no apply method on the chalk object. Do you know any way I can still get my desired functionality?

```js
'use strict'

const chalk = require('chalk')

function format() {
	const args = Array.from(arguments)

     // This is not working:
	const string = chalk.apply(chalk, args)

	const match = args[0].join('').match(/^[ \t]*(?=\S)/gm)

	if (!match) {
		return string
	}

	const indent = Math.min.apply(Math, match.map(line => line.length))
	const regex = new RegExp(`^[ \\t]{${indent}}`, 'gm')

	const dedentedString = indent > 0 ? string.replace(regex, '') : string

	return dedentedString.trim()
}

module.exports = format
```

**Comment by kevva** [comment]
What's your arguments? You can use `apply` on something like `chalk.cyan.apply(...)`.

**Comment by Qix-** [comment]
I'm not sure what you're trying to achieve here.

```javascript
// 1. This needs to have chalk as the `this` object
const string = chalk.apply(chalk, args)

// 2. chalk() by itself will always return whatever is passed to it.
console.log(chalk('hello', 'there')); //-> "hello there"
```

What are you trying to achieve?

**Comment by k15a** [comment]
@Qix- chalk.apply is what I need. Unfortunately, it's undefined for whatever reason. I want to have the normal
```js
chalk`{red hello world}`
```
behavior but with some additional functionality like stripping the indents.

The format function of the post above is used like:
```js
console.log(format`
    {red hello world}
`)
```

And the output should be `hello world` in red. But instead of the output, I get the following error:
```
/Users/konsch/Development/tmp/chalk-tag/index.js:5
	const string = chalk.apply(chalk, args)
	                     ^

TypeError: chalk.apply is not a function
    at format (/Users/konsch/Development/tmp/chalk-tag/index.js:5:23)
    at Object.<anonymous> (/Users/konsch/Development/tmp/chalk-tag/index.js:20:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by Qix-** [comment]
Oh I see.

This is going to change later on I suspect, but do this:

```javascript
const args = Array.from(arguments)
args[0].raw = arguments[0].raw;

// then...

const string = Function.prototype.apply.call(chalk, chalk, args)
```

Keep in mind this will almost definitely change (even at the patch level) so I highly advise pinning your version of chalk (i.e. don't use `^` or `~` or any prefixes when specifying a chalk version) and write lots of tests :)

**Comment by k15a** [comment]
Hey, thanks for this solution. I should have come up with this as well^^

> Keep in mind this will almost definitely change (even at the patch level) so I highly advise pinning your version of chalk (i.e. don't use ^ or ~ or any prefixes when specifying a chalk version) and write lots of tests :)

To which extent will this change? The `chalk` tag needs to be implemented as a function so Function.prototype.apply.call should always work if I am not wrong?

**Comment by Qix-** [comment]
@k15a template literals have been improved with the latest minor release. Might double check to make sure nothing broke on your end.

**Comment by clintwood** [comment]
Not sure if this is off-topic _but_ I have found it hugely useful in a logger utility to directly use `chalk/templates.js` to effectively give me the template processing that is available for tagged literals.
I'm not sure if I've missed if this is already possible but this is (a very summarized version of) what I'm doing:
```javascript
// logger.js
const chalk = require('chalk');
const chalkTemplates = require('chalk/templates');

function log(msg) {
  console.log(chalkTemplates(chalk, msg));
}
module.exports.log = log;

// some-other-file.js
const logger = require('./logger');

const msg = 'here';
logger.log(`Some {red text} right {green ${msg}}!`);


// I'm fully aware you could import chalk and do
console.log(chalk`Some {red text} right {green ${msg}}!`);
```
So it would be very nice to formally expose `chalk/templates.js` via chalk's api - something like `chalk.transform`.

PS  I am aware of ES2015 tagged template literal syntax however this didn't work for me in my case since string literals are primarily used in the calling site/code.  Also doing it this way means chalk is restricted to the logger.  Lastly it would be great to be able to detemplatize a string to strip out color templates `chalk.strip('Some {color text}'); => Some text`.

**Comment by k15a** [comment]
@clintwood That's exactly what I tried to do. Both versions seem to work but I am not sure which one is better. Both are relying on chalks internal structure which is not ideal.

**Comment by Qix-** [comment]
@sindresorhus thoughts on this? I'm impartial, personally.

**Comment by clintwood** [comment]
@Qix- Just in case there is a misunderstanding, for my case I'm not really looking to extend the syntax as perhaps @k15a is, but rather to simply use templates as they are.  So my call is to make that transformation API (exported by `chalk/templates.js`) formally available on chalk (which would small code change).

It's extremely useful to use the color templates in your code (say for logging) and have the transformation of those templates done in a single place (say in the logger).

The _remove template thing_ was just a nice to have if not a huge refactor.

Thanks for looking at this!

**Comment by jrencz** [comment]
I found this issue and I'd like to add my use case where I found lack of `{}` processing inside tagged template literal slot limitting.


I have a module that defines a class. I want for this module to have no dependencies.
I'd like to use chalk syntax in there like this.

```js
class A {
  constructor({
    logger
  }) {
    this.logger = logger;
  }

  doSomething() {
    this.logger.log('{green Success!} I did something');
  }
}
```

I hoped that defining a logger like this:

```js
import A from './A';

const a = new A({
  logger: {
    log: (...args) => {
      console.log(...args.map(arg => chalk`${ arg }`));
    }
  }
})
```

will do the job, but it doesn't.

To achieve what I wanted I'd have to manually prepare the input for `chalk.template` but without knowing what slots it has inside it's not doable.

**Comment by Qix-** [comment]
@jrencz 

```javascript
const chalk = require('chalk');
const chalkTemplate = require('chalk/templates');

class A {
  constructor({
    logger
  }) {
    this.logger = logger;
  }

  doSomething() {
    this.logger.log('{green Success!} I did something');
  }
}

const a = new A({
  logger: {
    log: (...args) => {
      console.log(chalkTemplate(chalk, args.join('')));
    }
  }
})

a.doSomething();
```

<img width="155" alt="image" src="https://user-images.githubusercontent.com/885648/41262162-7e5578ce-6d9c-11e8-8901-d1b90f8b3fce.png">


That's the only way to make what you want do-able. Otherwise, you'd probably be interested in something like this:

```javascript
const chalk = require('chalk');
const chalkTemplate = require('chalk/templates');

class A {
  constructor({
    logger
  }) {
    this.logger = logger;
  }

  doSomething(thing) {
    this.logger.log('{green Success!} I did {keyword("orange") %s}', thing);
  }
}

const a = new A({
  logger: {
    log: (fmt, ...args) => {
      console.log(chalkTemplate(chalk, fmt), ...args);
    }
  }
})

a.doSomething('something');
a.doSomething('something else');
```

<img width="184" alt="image" src="https://user-images.githubusercontent.com/885648/41262167-87df967c-6d9c-11e8-9d61-a8dd8b1f4948.png">

Otherwise, you'd have to write an API that is "slot" (argument, usually the `${}` in template literals) aware and just escape the `{`, `}` and `\` characters (see https://github.com/chalk/chalk/blob/master/index.js#L217-L218) in each "slot" before passing the whole string to the template function.

Hope that helps.

**Comment by Qix-** [comment]
Closing this as I feel there are a sufficient amount of template-related solutions to the various out-of-the-box needs and this is becoming a bit of a kitchen-sink issue.

If you have a case that is not covered here, please open a new ticket with **detailed information** about what you're trying to achieve.
