### ISSUE TITLE
Should we match console.log(fmt, ...) formatting with chalk?

### ISSUE THREAD

**Issue by Qix-** [chalk/chalk#189]
Right now, we do a simple `.join(' ')` on arguments. While this covers most cases, this isn't 100% analogous to `console.xxx()` functions.

Under the hood, the `console.xxx()` functions use [`util.format()`](https://nodejs.org/api/util.html#util_util_format_format_args).

Should we be using it?

// cc @sindresorhus

**Comment by sindresorhus** [comment]
Big 👎 . The goal was never to imitate `console.log`. Multiple argument support was just added for convenience before we had template literals. This functility would add a lot of overhead and complications for little gain. Users can just use `util.format()` if they need that kind of functionality. Template literals should be enough for most.

**Comment by Qix-** [comment]
:+1: fair enough.
