### ISSUE TITLE
Add the ability to append custom styles to chalk

### ISSUE THREAD

**Issue by Qix-** [chalk/chalk#190]
Similar to #186, but separate as this is a little more involved of a change.

It'd be kind of nice to be able to do

```javascript
chalk.rose = chalk.hex('#F69D9D');
console.log(chalk.bold.rose('hello!'));
```

You can currently add styles no problem, but they can't be prepended with any other styles.

I haven't tested, but I believe `chalk.rose.bold()` would work in the above example, but not the other way around.

Thoughts?

**Comment by sindresorhus** [comment]
Wouldn't this add those styles globally for anything using Chalk? That doesn't sound like a great idea. Lots of potential for conflicts.

**Comment by Qix-** [comment]
If they did it on the chalk object itself, sure. But they can do that right now anyway. It'd be more for those that use custom contexts.

**Comment by sindresorhus** [comment]
Your above example *is* on the chalk object itself, though. If it's meant for custom contexts, we could only allow it there then?

**Comment by Qix-** [comment]
I mean we could definitely freeze the main chalk object, if that's what you want. Otherwise, there's no way to prevent someone from adding stuff to the main chalk object.

**Comment by sindresorhus** [comment]
Almost anything can be modified in JS. That doesn't mean anything you can do is officially supported. For that reason, I don't see the need to freeze Chalk, but I also don't think we should officially support or document this as it's too easy to accidentally abuse. I meant that we only support it on custom contexts.

**Comment by Qix-** [comment]
Oh sure, absolutely.

**Comment by Qix-** [comment]
Closing since this can be achieved using `const chalk2 = chalk.constructor(); chalk2.customStyle = chalk2.foo.bar`.

Please re-open if that's not sufficient.
