### ISSUE TITLE
Add .visible()

### ISSUE THREAD

**Issue by Qix-** [chalk/chalk#192]
Just ran into the use case where it'd be quite useful to have something like `chalk.visible(...)`, where the contents are only emitted if chalk is enabled and has a non-zero level.

This is particularly for borders and whatnot that are purely cosmetic and thus don't need to even appear if chalk is not outputting things.

In the event chalk is disabled, a call to `visible()` returns an empty string.

Thoughts?

**Comment by sindresorhus** [comment]
👍
