### ISSUE TITLE
executing a script with babel-node doesn't show chalk colors 

### ISSUE THREAD

**Issue by thesimpledesigners** [chalk/chalk#196]
i'm using babel-cli to run some scripts in order to be transpiled before executed this scripts have some chalk colors but that doesn't show on the cli 
here is a simple example 
**test.js**
```
const chalk = require('chalk');

console.log(chalk.blue('Hello world!'));
```

**CLI "'im using git bash"**
`node_modules/.bin/babel-node ./test.js`

**output** 
![screenshot_3](https://user-images.githubusercontent.com/9967336/29140830-2b662c4e-7d4c-11e7-9b1b-ce90b637b4f7.png)

**Comment by thesimpledesigners** [comment]
the colours also doesn't show when executing a script from the npm scripts directive
example : 
```json
{
  "name": "demo",
  "version": "1.0.0",
  "description": "demo",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "devDependencies": {
    "chalk": "^2.0.1"
  }
}
```
```bash 
> npm start 
```

**Comment by Qix-** [comment]
Duplicate of #195
