### ISSUE TITLE
Not outputting in color

### ISSUE THREAD

**Issue by dotspencer** [chalk/chalk#197]
It is no longer showing color in the console after upgrading to version 2.0.0. Upon inspecting the string I found that it isn't adding the ansi codes.

Output from v1.1.3:

    console.log(util.inspect(chalk.red('hello')));
    '\u001b[31mhello\u001b[39m'

Output from v2.1.0

    console.log(util.inspect(chalk.red('hello')));
    'hello'

**Comment by dotspencer** [comment]
Uninstalling and reinstalling chalk has fixed the problem.

**Comment by Qix-** [comment]
Glad you got it working :)
