### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by caesar** [chalk/chalk#198]
Please add an explicit CHANGELOG file, rather than relying on notes in the GitHub Releases page.

See: http://keepachangelog.com/

**Comment by Qix-** [comment]
All of the breaking and functional changes made to Chalk are available via the Releases page on Github.

**Comment by caesar** [comment]
Exactly – I did mention that! ;-) The point of a changelog file, though, is that it is a standard location where this information can be found, and that it is independent from the Github website so that, for example, I can see the changes in a checked out copy of the repo on my computer or in a package I have `npm install`ed.

**Comment by Qix-** [comment]
We wouldn't include it in NPM anyway since it's not required for using the module. As well, the only official repository for Chalk is here on Github, which is clearly defined in the `package.json`. I am strongly against changelogs as they are way too easily desynchronized from the actual content of the repository and thus (to me) completely useless.

And not to mention annoying to maintain.

**Comment by caesar** [comment]
If you have a strong opinion I probably wont be able to change your mind, but I'll try... ;-)

Your point about being annoying to maintain and (as a result) too easily desynchronized from the actual content of the repository is *exactly* why a changelog file is better than the Github Releases page. The releases page is only updated once with each release. The changelog file is kept up top date with every commit, adding changes to the "Unreleased" section at the top which is then renamed to the current version number when a release is cut.

Even if it doesn't change your mind, I strongly encourage you to have a look at the information at http://keepachangelog.com/ which makes a very compelling case for keeping a changelog and explains clearly why it is important.

**Comment by Qix-** [comment]
@caesar We diff the previous tag with the current tag to generate changes and document them appropriately. As well, we employ semantic versioning and we keep modules small to reduce broad-stroking changes to the code base. None of these things are really remedied by a changelog file.

**Comment by caesar** [comment]
Alright, you have clearly made up your mind, so I won't waste more of both of our time by trying to convince you otherwise.

While I'm here: thanks for this awesome project! 👍

**Comment by leo** [comment]
https://github.com/zeit/release
