### ISSUE TITLE
Semantic API

### ISSUE THREAD

**Issue by fuchao2012** [chalk/chalk#199]
As describe in title.

Can we add some semantic API like `link`, `title` `comment` ...

```
chalk.link = chalk.blue.bold.underline
```

**Comment by Qix-** [comment]
There's nothing stopping you from doing this. What's the problem you're facing?

**Comment by Qix-** [comment]
Also, this is a duplicate of #190.

**Comment by Qix-** [comment]
Duplicate of #190.
