### ISSUE TITLE
Yellow and Magenta do not display in powershell

### ISSUE THREAD

**Issue by danielchatfield** [chalk/chalk#2]
I'm not sure what should be done about this, if anything.

Yellow isn't too much of a problem since it displays as white but `magenta` actually displays as the same colour as the powershell background which isn't exactly ideal.

The two options, as far as I can see, are:
1. leave it up to developers to use what is supported
   -  In this case I think a notice about platform compatibility should be added to the readme
2. Use the 'intense' versions of these colours (they work)
   - Possibility of only using if on windows (although that will make `chalk` messy which is something I think you are very keen to avoid)
   - changes `'\x1b[35m'` to `'\x1b[95m'`

In addition to those colours `italic`, `underline`, `inverse` and `strikethrough` do not work on windows so I think something in the readme should note that.

**Comment by gluons** [comment]
But if I use `chalk.bold`, PowerShell will display as yellow. lol :joy:

**Comment by domhayez-dev** [comment]
still going strong
