### ISSUE TITLE
Add chalk.pipe()

### ISSUE THREAD

**Issue by LitoMore** [chalk/chalk#200]
How about add a new feature `chalk.pipe()`?

It's an idea comes from my project [Nofan](https://github.com/LitoMore/nofan/blob/master/src/util.js#L120).

![nofan-colors](https://user-images.githubusercontent.com/8186898/29614054-403b85ac-883b-11e7-8b99-84430569170e.gif)

It's very convenient for create a color scheme.

### Example

```javascript
const magical = chalk.pipe('#ff69b4.bold')
magical('unicorn') // \u001b[38;2;255;105;180m\u001b[1municorn\u001b[22m\u001b[39m
```

`chalk.pipe('dim.#ff99cc.italic')` is equivalent to `chalk.dim.hex('#ff99cc').italic`

`chalk.pipe('blue.pink.underline')` is equivalent to `chalk.blue.keyword('pink').underline`

`chalk.pipe('bgRed.bgPink.bg#ffffff')` is equivalent to `chalk.bgRed.bgKeyword('pink').bgHex('#ffffff')`

**Comment by Qix-** [comment]
I don't think so, sorry. You're welcome to write a module that does the parsing, though :) I'd be happy to include it in the readme.

**Comment by LitoMore** [comment]
OK, thanks!
