### ISSUE TITLE
Chalk not working in GitLab runner terminal

### ISSUE THREAD

**Issue by basickarl** [chalk/chalk#203]
```
const str1 = 'str1';

console.log(str1, str1.length); // clean
const str2 = chalk.red('str2');
console.log(str2, str2.length); // chalk styled

console.log(str1, str1.length); // clean
const str3 = '\x1b[42mstr3\x1b[0m';
console.log(str3, str3.length); // my styled

console.log(str1, str1.length); // clean

process.exit(0);
```
The above code resutls in the below two results.

My local computer terminal (working):
![screen shot 2017-08-24 at 14 44 01](https://user-images.githubusercontent.com/10507098/29667032-26eca70c-88db-11e7-9445-3b25291e1796.png)

GitLab runner (not working):
<img width="262" alt="screen shot 2017-08-24 at 14 44 23" src="https://user-images.githubusercontent.com/10507098/29667037-311ae00e-88db-11e7-8bbb-b3b66f6a09f7.png">

**Comment by basickarl** [comment]
This is probably related to: https://github.com/chalk/supports-color/issues/65

**Comment by CyberiumShadow** [comment]
This seems more like a duplicate issue to #195 
@Qix- can confirm I believe
@basickarl try using the environment variable `FORCE_COLOR=1` and see if it works in GitLab Runners

**Comment by basickarl** [comment]
@CyberiumShadow Ah indeed you are correct, that link perfectly summed up what was wrong.

I fixed the issue adding this to my `.gitlab-ci.yml` if anyone else stumbles upon this:
```
variables:
    FORCE_COLOR: '1'
```
Thanks again!
