### ISSUE TITLE
Blue = orange?

### ISSUE THREAD

**Issue by cameronlockey** [chalk/chalk#204]
I am using chalk in a NodeJS script, outputting to the Terminal. For some reason when I use `chalk.blue` and `chalk.blueBright`, they appear orange and light orange, respectively. Am I missing something? Is there possibly a difference in the way my Terminal interprets colors? Other basic color methods seem to work fine.

Example:

```
const chalk = require('chalk');

console.log(chalk.blue('Hello, World!'));
console.log(chalk.blueBright('Hello, World!'));
```

[Screenshot](https://pasteboard.co/GHsFAku.png)

**Comment by Qix-** [comment]
Seeing as how there's no such thing as orange in the original color schemes to begin with, this is most definitely a problem with your terminal emulator's palette configuration and has nothing to do with chalk.

Check your terminal's settings :)
