### ISSUE TITLE
Usage example code execution error

### ISSUE THREAD

**Issue by palashmon** [chalk/chalk#206]
Hi Everyone,

I was trying to execute this 2nd code in [usage](https://github.com/chalk/chalk#usage) section on my local after installing `chalk`, just to check the use cases:

```js
// ES2015 tagged template literal
log(chalk`
CPU: {red ${cpu.totalPercent}%}
RAM: {green ${ram.used / ram.total * 100}%}
DISK: {rgb(255,131,0) ${disk.used / disk.total * 100}%}
`);
```

and got an error in cli like:

```sh
ReferenceError: cpu is not defined
```

Though its a minor issue, but I think example codes should have been error free. I hope you will agree with me.

Regards!

**Comment by palashmon** [comment]
**F.Y.I.**

I fixed this issue on my local like:

```js
// ES2015 tagged template literal
const totalPercent = 95;
const ramPercent = 60;
const diskPercent = 80;
log(chalk`
CPU: {red ${totalPercent}%}
RAM: {green ${ramPercent}%}
DISK: {rgb(255,131,0) ${diskPercent}%}
`);
```

**Comment by Qix-** [comment]
Hi - we expect the average user can deduce the usage of the library via the examples. I don't think it's fair to expect a copy-paste-able example that is only a few lines long, especially when it's clear `cpu` doesn't exist in the scope of the example.
