### ISSUE TITLE
TypeError: Cannot read property 'bold' of undefined => bgBlack?

### ISSUE THREAD

**Issue by ORESoftware** [chalk/chalk#208]
I swear bgBlack is available

but when I do this:

`chalk.bgBlack.white.bold()`

I get:

`TypeError: Cannot read property 'bold' of undefined`

**Comment by Qix-** [comment]
Hey there, I can't reproduce this.

```javascript
> chalk.bgBlack.white.bold('hello')
'\u001b[40m\u001b[37m\u001b[1mhello\u001b[22m\u001b[39m\u001b[49m'
```

**Comment by sindresorhus** [comment]
Which npm version are you using? Make sure you're using the latest one.

**Comment by ORESoftware** [comment]
weird, thx, let me re-investigage

**Comment by LitoMore** [comment]
@ORESoftware `Cannot read property 'bold' of undefined` means that `chalk.bgBlack.white` is `undefined`, **NOT** `chalk.bgBlack` is `undefined`.

You need to swear `chalk.bgBlack.white` is available. :)

**Comment by ORESoftware** [comment]
@LitoMore thaz true

**Comment by sindresorhus** [comment]
Closing as it's most likely an npm issue.

**Comment by sandip2224** [comment]
In my case I had forgotten this statement: 
```
const colors=require('colors')
```
This solved my issue.

**Comment by j-dogcoder** [comment]
Also having this issue

**Comment by Qix-** [comment]
Please open a new issue then with all relevant information. This is a 5 year old issue about a very old version of Chalk.
