### ISSUE TITLE
Easier (elegant) way to set chalk.styles in 2.0.0?

### ISSUE THREAD

**Issue by KayLeung** [chalk/chalk#209]
It's harder to get and set color styles in 2.0.0

In 1.x.x:
`require('chalk').styles.blue.open = '\u001b[34m';
`

In 2.0.0: Pushed options into an ARRAY
`require('chalk').blue._styles[0].open = '\u001b[34m';
`

Is it an expected change between v1 and v2?  The extra ARRAY seems unnecessary.

Thanks!

**Comment by sindresorhus** [comment]
That's just an implementation detail. You shouldn't modify the internals.

**Comment by sindresorhus** [comment]
If https://github.com/yarnpkg/yarn/pull/4482/files#diff-2e782def01f9e8121ea62a611401b8b9R31 is still an issue in Chalk, it should be fixed here, but you should first check if it hasn't already been fixed in v2.

**Comment by KayLeung** [comment]
Do you mean v2 implementation expected we could access  `chalk.bold.close` directly?

**Comment by Qix-** [comment]
This was an issue in Windows that I submitted an issue for a while back and it has since been fixed - see Microsoft/WSL#2174.

Closing as this is no longer an issue (last message here occurred before the fix was pushed out).
