### ISSUE TITLE
Demo all built-in styles

### ISSUE THREAD

**Issue by borekb** [chalk/chalk#210]
Something like `chalk.demo()` with output similar to the screenshot in README would be a great dynamic cheat sheet.

![image](https://user-images.githubusercontent.com/101152/41272440-6410b770-6e15-11e8-868b-f0e8cfed244b.png)

**Comment by khirayama** [comment]
@borekb Your screenshot url is dead link 😢 
You might better to close this issue or update the link 👍

**Comment by borekb** [comment]
I've updated the link and also posted the screenshot directly to the OP, thanks for pointing that out.

**Comment by Qix-** [comment]
@borekb Not seeing either of those edits you mention. I'm also not a fan of cruft like that - might be better as a separate script (see how we build up the screenshots in the readme).

Feel free to PR as I agree the old 16-colors-only screenshot is outdated.

**Comment by borekb** [comment]
@Qix- Thanks for pointing out that the screenshot is still missing – not sure how that happened but I've re-uploaded.

You mean [this example](https://github.com/chalk/chalk/blob/a6ad9454525c0af602931049155cc51eccc72bb4/examples/screenshot.js) as a way to generate all the possible combinations? Yes that's probably what I wanted, it was just not very convenient to run it :) I'm now thinking that maybe it would fit better into the [chalk-cli](https://github.com/chalk/chalk-cli) project, e.g., `chalk --demo`. What do you think? cc @sindresorhus

**Comment by Qix-** [comment]
Yeah that sounds great :)

**Comment by borekb** [comment]
Thanks, I'll try to submit a PR to chalk-cli later this week and then write back here.

**Comment by sindresorhus** [comment]
@borekb Still interested in doing this? :)

**Comment by borekb** [comment]
Sorry, won't have time. Those promises.. :)

**Comment by wcastand** [comment]
hello, i can work on this if that's still something we want :)

**Comment by Qix-** [comment]
@wcastand https://github.com/chalk/chalk-cli :)

**Comment by wcastand** [comment]
Ahah I see, thanks. I feel dumb right now 🤣 I'll go make the demo there then thanks again :)
