### ISSUE TITLE
Colors don't show up when piping stdout between processes

### ISSUE THREAD

**Issue by ORESoftware** [chalk/chalk#212]
Say I have this:

```js
//colors.js
const chalk = require('chalk');
console.log(chalk.red('foobar'));
```

node colors.js | cat

In all the cases I have seen, the colors won't show up. Does anyone know why? Is there a way to get the colors to show up? Am I do something wrong?

**Comment by ORESoftware** [comment]
![alt text](https://www.dropbox.com/s/c7nio89gc0372sw/Screenshot%202017-10-13%2023.48.10.png?dl=0 "Colors and their discontents")

**Comment by ORESoftware** [comment]
I could not upload a screenshot here, but here is a good example:
https://stackoverflow.com/questions/46741639/terminal-styling-control-chars-using-the-chalk-npm-module

**Comment by ORESoftware** [comment]
Ok I figured this out, use either `FORCE_COLOR=1` or `--color`

**Comment by Qix-** [comment]
Yes - that's on purpose :) Piping disables chalk.
