### ISSUE TITLE
FORCE_COLOR=0 does *not* disable

### ISSUE THREAD

**Issue by ORESoftware** [chalk/chalk#213]
I did some simple experiments, and FORCE_COLOR=0 does *not* disable colors.

For example:

```js
// a.js
const chalk = require('chalk');
console.log(chalk.red('foobar'));
```

```js
//b.js
process.stdin.resume().pipe(process.stdout);
```

```bash
#!/usr/bin/env bash
FORCE_COLOR=0 node a.js | node b.js
```

color will be used in b.js, whether it's `FORCE_COLOR=1` or `FORCE_COLOR=0`

**Comment by ORESoftware** [comment]
Even if I do this, it still still doesn't work as documented:

<img width="640" alt="screenshot 2017-10-14 13 53 36" src="https://user-images.githubusercontent.com/11139560/31579257-29646e64-b0e7-11e7-9deb-68a0e96aaea2.png">

**Comment by Qix-** [comment]
Which version of chalk are you using?

**Comment by the1mills** [comment]
v1.1.3

**Comment by Qix-** [comment]
`FORCE_COLOR=0` was not introduced until v2 IIRC.

**Comment by ORESoftware** [comment]
ok got it thx

**Comment by Qix-** [comment]
We had a lengthy discussion over at chalk/supports-color#31. :) You're welcome to go see some of the discussion and decision making there.

**Comment by ORESoftware** [comment]
thanks yeah, seems like it's a noisy room over there so I will let it go :)
