### ISSUE TITLE
missing module => 'color-convert'

### ISSUE THREAD

**Issue by ORESoftware** [chalk/chalk#214]
On occasion I after a clean NPM install, I see:

```
 Error: Cannot find module 'color-convert'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman-debug/node_modules/ansi-styles/index.js:2:22)
```

when I run `npm la color-convert` I see:

```
└─┬ chalk@2.1.0
  │ Terminal string styling done right
  │ git+https://github.com/chalk/chalk.git
  │ https://github.com/chalk/chalk#readme
  └─┬ ansi-styles@3.2.0
    │ ANSI escape codes for styling strings in the terminal
    │ git+https://github.com/chalk/ansi-styles.git
    │ https://github.com/chalk/ansi-styles#readme
    └── UNMET DEPENDENCY color-convert@^1.9.0

npm ERR! missing: color-convert@^1.9.0, required by ansi-styles@3.2.0

```
I think maybe chalk should talk to ansi-styles and tell ansi-styles to fix their ship?

**Comment by sindresorhus** [comment]
This has nothing to do with Chalk. It's an issue with npm. Make sure you're on the latest Node.js and npm version. Use the npm issue tracker for support.

**Comment by mizzao** [comment]
@ORESoftware I just got this same error after installing something with `chalk` as a dependency. It's strange because everything else about the build was working fine so far. Did you end up figuring out what was causing it?
