### ISSUE TITLE
doesnt work when referenced from another file

### ISSUE THREAD

**Issue by galki** [chalk/chalk#218]
system: windows 10
shell: powershell
folder structure:
```
- mainBuild.js
- package.json (contains chalk just in case)
- folder
  - subBuild.js
  - package.json (contains chalk)
```
i run `node mainBuild`, which itself runs `node subBuild` - and the chalk effect is gone

if i manually run `cd folder && node subBuild` in the terminal the chalk effect works

**Comment by Qix-** [comment]
Need _way_ more information to help you here. This is also not really a `chalk` problem per se.

What does your import look like?

**Comment by galki** [comment]
sorry, what do you mean by import?

**Comment by Qix-** [comment]
Either `import` or `require()`

**Comment by galki** [comment]
in mainBuild.js:
```
const program = require('commander')
const shell = require('shelljs')
```
in subBuild.js:
```
const chalk = require('chalk')
const shell = require('shelljs')
```

**Comment by danthegoodman** [comment]
> i run `node mainBuild`, which itself runs `node subBuild` - and the chalk effect is gone

Chalk by default only enables color when attached to a TTY (e.g. an interactive terminal).  It sounds like your subBuild process isn't passing the [`process.stdout.isTTY` check](https://github.com/chalk/supports-color/blob/master/index.js#L44). Try explicitly passing the color argument to the subBuild process like so: `node subBuild --color=true`

**Comment by galki** [comment]
that solved it - thank you!
