### ISSUE TITLE
2.2 appears to be a breaking changes version?

### ISSUE THREAD

**Issue by johnnyreilly** [chalk/chalk#219]
We upgrade ts-loader to Chalk 2.2 and upon release we started to get reports of errors: https://github.com/TypeStrong/ts-loader/issues/664

Is 2.2 actually breaking changes?

**Comment by Qix-** [comment]
Shouldn't be. The user on your issue sounds like they had some version mismatch. Pinning wouldn't have solved the problem if 2.2 was a breaking change.

**Comment by sindresorhus** [comment]
Duplicate of #215

**Comment by johnnyreilly** [comment]
We released v 3.0.5  of ts-loader which required 2.2 chalk as a minimum. Hopefully that should resolve all issues
