### ISSUE TITLE
1.1.3 empty in npm registry

### ISSUE THREAD

**Issue by erquhart** [chalk/chalk#225]
Requests for the latest 1.x release are now failing: https://unpkg.com/chalk@1.1.3/

Seems like some weird issue with the registry itself. Any chance you can publish 1.1.4 as a temporary workaround?

**Comment by arwineap** [comment]
I'm experiencing the same issue, but have noticed that 1.1.3 appears to be available in npm?

```
$ npm show chalk@* version
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.4
npm info attempt registry request try #1 at 7:39:15 PM
npm http request GET https://registry.npmjs.org/chalk
npm http 200 https://registry.npmjs.org/chalk
chalk@0.1.0 '0.1.0'
chalk@0.1.1 '0.1.1'
chalk@0.2.0 '0.2.0'
chalk@0.2.1 '0.2.1'
chalk@0.3.0 '0.3.0'
chalk@0.4.0 '0.4.0'
chalk@0.5.0 '0.5.0'
chalk@0.5.1 '0.5.1'
chalk@1.0.0 '1.0.0'
chalk@1.1.0 '1.1.0'
chalk@1.1.1 '1.1.1'
chalk@1.1.2 '1.1.2'
chalk@1.1.3 '1.1.3'
chalk@2.0.0 '2.0.0'
chalk@2.0.1 '2.0.1'
chalk@2.1.0 '2.1.0'
chalk@2.2.0 '2.2.0'
chalk@2.2.2 '2.2.2'
chalk@2.3.0 '2.3.0'
npm info ok

```

**Comment by recurrence** [comment]
I can curl the endpoint now, appears resolved?

**Comment by GrimTheReaper** [comment]
@recurrence I can do so too, but trying to install through `npm -i` always results in a 503.

**Comment by erquhart** [comment]
I think the inconsistencies are due to various caches.

**Comment by recurrence** [comment]
It was tracked down here to cloudflare, cloudflare claims the outage has ended.  https://github.com/yarnpkg/yarn/issues/4889#issuecomment-342936836

**Comment by erquhart** [comment]
Ah yep, Travis has it now, awesome. Thanks for the link!
