### ISSUE TITLE
Options to apply/not apply chalk to a specific string or character(s)

### ISSUE THREAD

**Issue by jmahc** [chalk/chalk#226]
Is there a way to only apply or not apply chalk to a certain string / character?

**Comment by Qix-** [comment]
This is really vague. Can you give an example?

**Comment by jmahc** [comment]
```
    const options = {
            bold: {
              apply: ['\\', '/', '|'],
              ignore: ['$']
            },
            green: {
              apply: ['$'],
              ignore: []
            },
            ...
          }
```

```
const chalkInstance = () => {
     const text =chalkWithOptions`
               {green $$\         $$\    $$$$$$\}
               {green $$ |        $$ |   \_$$  ___|}
               {green $$ |        $$ |      $$ |}
               {green $$$$$$$$ |       $$ |}
               {green $$   ___ $$ |       $$ |}
               {green $$ |       $$ |      $$ |}
               {green $$ |       $$ |   $$$$$$\}
                \__|         \__|    \________|
        `
}
```

So it would look at the options and for bold would ignore the `$`, and green apply it for `$`

**Comment by Qix-** [comment]
Nah sorry, that's not something we want to support. You're welcome to write your own module, though :)

**Comment by jmahc** [comment]
@Qix- Thanks for the quick responses!

Was writing some ASCII art from [here](http://patorjk.com/software/taag/) when the question formed.

Not too sure how much console logged ASCII are I will be doing in the future, though 😄
