### ISSUE TITLE
Property 'red' does not exist on type '{ enabled: any; }'.

### ISSUE THREAD

**Issue by dcsan** [chalk/chalk#228]
I'm using chalk with vscode and getting these warning errors below:

`Property 'red' does not exist on type '{ enabled: any; }'.`

it's a pretty simple thing i'm building:

```
const chalk = require("chalk")
let cmd = 'something'
console.log(chalk.yellow(cmd))
```

I wonder if there is some definition/typings file (for JS) or some other magic that's going on that is confusing the VSCode typechecking?

**Comment by Qix-** [comment]
To be clear, are you getting errors when _running_ or using some type-checking static analysis tool?

If it's the latter, please take it up with them. Chalk is valid Javascript - if they're going to try to stomach a static analyzer for a highly dynamic language then this is their problem, not ours.

**Comment by dcsan** [comment]
edit time, yes. 
using with VSCode.

OK, I'll take it up with them I guess! But wondering where that `'{ enabled: any; }'.` could be coming from. is `{enabled: {} }` some type of object you return from initialization? 

any is the default object type, but `{enabled: .. } looks like you're returning a specific field.

**Comment by Qix-** [comment]
I have no idea what `any` means. I'd imagine it's something similar to Flow typing where VSCode can't determine the type of the `enabled` flag. It's either truth-y or false-y, anyway.

Yes, please open an issue over there as this is room for them to improve. Our API is a corner case in that we make liberal use of property prototypes. Perhaps they could start reading Typescript definitions even for non-typescript source. Just a thought :)

Thanks for the question!

**Comment by dcsan** [comment]
> Perhaps they could start reading Typescript definitions even for non-typescript source

they do exactly that:
https://code.visualstudio.com/Docs/languages/javascript#_automatic-type-acquisition

Most common JavaScript libraries have type declaration files available. You can search for a library's type declaration file package using the TypeSearch site.
https://microsoft.github.io/TypeSearch/

It looks like someone created them for `chalk` but it's just a stub
https://www.npmjs.com/package/@types/chalk

@types/chalk 
This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!


VSCode seems to have a lot of momentum as a JS IDE, it would be nice to not have errors popup each time I open a file using chalk...

**Comment by Qix-** [comment]
@dcsan we have typescript defs that were created and verified by several typescript peeps (I don't know TS therefore I cannot comment on how accurate they are). However, those people are pretty smart and I would wager they're probably correct with their definitions.

In which case, it's very much VSCode's job to improve their code hinting functionality. They're also welcome to contribute better definitions.

There's nothing actionable on our end, however. If I'm wrong, let me know.

**Comment by dcsan** [comment]
any ideas how I could install those typedefs? It seems whatever is being pulled down by default, publicly registered is causing the problem.

```
➜  yarn install

warning @types/chalk@2.2.0: This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!
```

**Comment by felipellrocha** [comment]
+1 Any updates on this? I'm running into this exact issue

**Comment by joskuijpers** [comment]
tried using the following, which does work:

```ts
import chalk from 'chalk';
```

**Comment by ChristosChristofidis** [comment]
if you are using import * as chalk from 'chalk';

then `chalk.default.yellow(cmd)` will work
