### ISSUE TITLE
Typings only work when importing a default using older TS syntax

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [chalk/chalk#233]
In #169, it was mentioned that adding a default export solved for `import chalk from 'chalk';`. The way it's done now means we can't `import * as chalk from "chalk";`:

```typescript
import * as chalk from "chalk";

// Property 'blue' does not exist on type 'typeof "---/node_modules/chalk/types/index"'.'
chalk.blue("foo");
```

**Comment by sindresorhus** [comment]
This has been discussed at great lengths in https://github.com/chalk/chalk/issues/215. tl;dr It's working as intended and we're not going to change it.
