### ISSUE TITLE
It doesnt look right, confirmed by bold

### ISSUE THREAD

**Issue by malliapi** [chalk/chalk#236]
Hi All,

I've recently tried to incorporate chalk into my project, but it doesn't look like it works. The weird thing is that in the project i sourced the idea from it works fine but not in mine. I created a new project cleanly, and again it doesnt work there either. 

The below is what the output looks lie in bash:
<img width="580" alt="screen shot 2017-12-16 at 20 38 50" src="https://user-images.githubusercontent.com/9448752/34074174-852ff768-e2a1-11e7-864b-577904aedb30.png">

The code is soooo simple. see below:

const chalk = require('chalk');
const figures = require('figures');

const logger = {
  log: console.log,
  error: messages => console.error(chalk.red(figures.cross, ...messages)),
  info: messages => console.info(chalk.cyan(figures.info, ...messages)),
  success: messages => console.log(chalk.green(figures.tick, ...messages)),
  warn: messages => console.log(chalk.yellow(figures.warning, ...messages)),
};

logger.info(`Target application environment: ${chalk.bold('production')}`)

**Comment by sindresorhus** [comment]
You have typos: `messages =>` should be `(...messages) =>`. Right now you're spreading a string, which results in Chalk getting an array of characters and joins them with space.
