### ISSUE TITLE
Colored text is printed in white when command is invoked from globally installed package in ConEmu

### ISSUE THREAD

**Issue by another-guy** [chalk/chalk#237]
I'm writing an npm package which will be used as a cli command (similar to `ng`, or `yarn`, or other).

For some reason, there's no coloration when the command is invoked in ConEmu from a globally installed package. (`tspck init` is implemented in the TS-compiled `tspck-init.js` file of my `tspck` package).

![non-colorized](https://user-images.githubusercontent.com/5762340/34240711-0e578fee-e5c5-11e7-9ec2-9f88fb231ca1.png)

However, when I use `node run tspck-init.js` in ConEmu, it does work fine:

![colorized](https://user-images.githubusercontent.com/5762340/34240859-3818dff8-e5c6-11e7-952c-3a251a46ccaa.png)

If I run the command in `cmd` from a globally installed package, it works too:

![image](https://user-images.githubusercontent.com/5762340/34240865-3e2f1a92-e5c6-11e7-97c2-d97905c1c05a.png)

Should I be looking for the root cause of the issue in my source code, or somewhere else? Sorry for putting the question so broadly -- I don't even know where to start.

This is the reference to the specific file in my sources that uses *chalk* https://github.com/another-guy/tspck/blob/master/src/tspck-init.ts#L29.

---

chalk version: 2.3.0 (`"sha512-Az5zJR2CBujap2rqXGaJKaPHyJ0IrUimvYNX+ncCy8PJP4ltOGTrHUIo097ZaL2zMeKYpiCdqDvS6zdrTFok3Q=="`)
Windows Version: 1607 build 14393.1884
ConEmu version: 170819 [64] {Alpha}

---

P.S. I saw this one https://github.com/chalk/chalk/issues/161 , but I am very unsure whether they a related or not.

**Comment by another-guy** [comment]
Yet things are working on **another machine** fine (for a commend invoked from a globally installed package):

![image](https://user-images.githubusercontent.com/5762340/34269738-521598e6-e63a-11e7-881f-a3d1fac570ac.png)

ConEmu version is 161206 [64]

**Comment by Qix-** [comment]
Sounds like a local development environment issue. Further, ConEmu has **terrible** support for colors and has a lot of bizarre behavior.

Unless you can show me directly that Chalk is at fault here, there isn't much I can do - especially since it works fine from another machine.
