### ISSUE TITLE
Coloring issue with cmder

### ISSUE THREAD

**Issue by PolaEdward** [chalk/chalk#241]
While using cmder [http://cmder.net/] there's a styling issue that I can see while using react-native

Screenshots on a related issue here
https://github.com/cmderdev/cmder/issues/1568

**Comment by DentFuse** [comment]
I'm experiencing a colouring issue too, here are the screens:
![image](https://user-images.githubusercontent.com/25380286/38174617-97b26f5c-35ed-11e8-8fc5-300b13292178.png) 
 CMDER
![image](https://user-images.githubusercontent.com/25380286/38174620-a47c9078-35ed-11e8-9a12-236760270054.png) 
CMD

Many of the colours are changed, any fix for this?

**Comment by sindresorhus** [comment]
@DentFuse Your issue is different. The "Orange" is red because CMDER doesn't seem to support more than 16 colors, so Chalk falls back to the closest supported color.

**Comment by DentFuse** [comment]
@sindresorhus Thank you for your quick reply :) Is this the reason for purple appearing blue and pink appearing purple too?

**Comment by sindresorhus** [comment]
Yes

**Comment by Qix-** [comment]
Nothing we can do here. This is affected entirely by how the terminal emulator (cmder in this case) consume escape sequences.
