### ISSUE TITLE
IE problem in dev mode

### ISSUE THREAD

**Issue by PatrikMatiasko** [chalk/chalk#245]
This console problem crash app on IE v 11 on react app in dev mode. In production it's ok.
console error : 
SCRIPT1053: Const must be initialized

problem code:  (line 55)
for (const key of Object.keys(ansiStyles)) { .... }

reason: 
According to https://kangax.github.io/compat-table/es6, "const in for-of loop iteration scope" is not supported in IE and not in Edge until version 14. It's the same with let btw. Basic for of loops, and basic const/let usage do work though. MDN is not the most accurate source for browser support.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
