### ISSUE TITLE
What to do with terminal having light background colours?

### ISSUE THREAD

**Issue by clemtrek** [chalk/chalk#249]
Kindly tell me if this is not the place where I should be creating this issue.

On terminals with a white background, colors don't look good (especially `yellow`, `cyan` and `other light colors`).

Is there a way to get the terminal's background color so that alternative colors could be used.

It would nice if `chalk` had support for complimentary colors to handle this issue with ease

**Comment by clemtrek** [comment]
@sindresorhus, @Qix-  Would you please look into this or just tell me something.

**Comment by Qix-** [comment]
1. There is no portable way to detect the current color scheme of the terminal
2. The basic 16 colors of the terminal (8 * 2 for dark/light) indicate intended color but not shade or tint (e.g. `31m` means "red", but the exact RGB value has never been specified). You can usually adjust the exact RGB values of each color in your terminal emulator's settings.
3. Color schemes are outside the scope of Chalk.
