### ISSUE TITLE
[Suggestion] Wrapper for effects and unprintable characters

### ISSUE THREAD

**Issue by felipenmoura** [chalk/chalk#253]
Hello.

I created a Pull request a few minutes ago adding a "wrapper" feature.

I'm working on an Open Source tool to setting the PS1 in your terminal, using node. But for that, I needed all the colours and effects to be wrapped into `\[` and `\]`.

I figured this could be an interesting addition for the chalk project as it can be used to "tokenise" the  styles, to identify and debug them, or help you out on different TTYs.

I hope this can be considered :)

**Comment by Qix-** [comment]
Hey - not really interested to be quite honest. Just do a search for `\x1b` and replace it with a character of your choosing (or remove it entirely) in the output.

For example,

```console
$ FORCE_COLOR=1 node your/chalk/app.js | tr -d "$(printf '\x1b')"
```

<img alt="image" src="https://user-images.githubusercontent.com/885648/41262606-0ad312d2-6d9f-11e8-90dd-e0767553e4ae.png">

**Comment by mnpenner** [comment]
For anyone else stumbling upon this, you can use @felipenmoura's [fork of chalk](https://www.npmjs.com/package/@nasc/chalk#chalkwrapper) like this:

```
const Chalk = require('@nasc/chalk');

const chalk = new Chalk.constructor({
  wrapper: {
    pre: '\1',
    post: '\2',
  }
});
```

Then use as normal. The escape codes are explained [here](http://mywiki.wooledge.org/BashFAQ/053).

**Comment by Qix-** [comment]
No, by you piping things, you're telling Chalk to disable itself. Did you try `FORCE_COLOR=1`?

**Comment by mnpenner** [comment]
I sure did. It was coming out colored, but some of the control characters were appearing in the output. Even without the pipe, I needed `FORCE_COLOR=1`.

**Comment by Qix-** [comment]
That means your terminal emulator doesn't support them and is improperly reporting its `TERM` variable. Which one are you using?
