### ISSUE TITLE
Add "bright black" and use "gray" as alias

### ISSUE THREAD

**Issue by nmschulte** [chalk/chalk#257]
For consistency, it would be good to have a `chalk.blackBright` for use.

Similarly, it'd be nice if there was a "background" color alias for gray: `chalk.bgGray`.

**Comment by Qix-** [comment]
Would otherwise close since this belongs over at [`ansi-styles`](/chalk/ansi-styles) but this also requires the "English" fix for `bgGrey`. That alias happens in `chalk` proper, so this issue will serve as that to-do.

**Comment by GeorgeGkas** [comment]
@Qix- is anything that needs to be done?

**Comment by Qix-** [comment]
Just need to update the version of `ansi-styles` we use, which is something we'll do (see #300)

**Comment by sindresorhus** [comment]
This is fixed in master and will be available in Chalk 3.
