### ISSUE TITLE
Direct access to template string formatting

### ISSUE THREAD

**Issue by laino** [chalk/chalk#258]
There doesn't appear to be a documented and clean way to run something through the template function.

AFAIK the best way to do it right now is:

```js
const chalk = require('chalk');
const chalkTemplate = require("chalk/templates");

const myString = "{red RED}";

console.log(chalkTemplate(chalk, myString));
```

But I've seen [other hacks](https://github.com/75lb/command-line-usage/blob/02c8b182ede7ae7d6f064f8c1d27bde14a89b395/lib/chalk-format.js).

There probably should be a documented way to do this that doesn't involve ugly hacks and won't break with an update...

**Edit:** 

```js
const chalk = require('chalk');

const string = "{red RED}";
const arr = [string];
arr.raw = [string];

console.log(chalk(arr));
```

**Comment by Qix-** [comment]
Nope, but here's a one-liner:

```javascript
const chalkTemplate = str => chalk(Object.assign([], {raw: [str]}));

const string = '{red RED}';
console.log(chalkTemplate(string));
```
