### ISSUE TITLE
Feature request: chalk.decode()

### ISSUE THREAD

**Issue by F1LT3R** [chalk/chalk#259]
It would be useful to be able to decode a string that was already written. 

For example:

```javascript
const str = chalk.green('Test')
const decoded = chalk.decode(str)
console.log(decoded)
// '\\u001b[32mTest\\u001b[39m'
```

Perhaps there's an easy way to do this already with JavaScript? I've looked around for about an hour and I can't find one/come up with one.

**Comment by F1LT3R** [comment]
Nevermind, I found a way to do this using `he`. I couldn't find another NPM package for this, so... https://github.com/F1LT3R/ansi-encode

**Comment by Qix-** [comment]
Here's a one-liner:

```javascript
const escapeAnsi = str => str.replace(/\u001b|\u009b/g, m => ['\\u009b', '\\u001b'][Number(m === '\u001b')]);
```

**Comment by F1LT3R** [comment]
Thanks @Qix- - also, I found this did what I needed:

```js
const encode = ansiStr => JSON.stringify(ansiStr).replace(/'/g, '\\\''))
```
