### ISSUE TITLE
"closing tag" as [39m or [0m

### ISSUE THREAD

**Issue by christopherreay** [chalk/chalk#263]
Im trying to help out a friend with a project (https://github.com/felixfbecker/cli-highlight) and I have an issue here.

when i use ansi2html.sh to convert from the output of cli-highlight to html, none of the html style tags ever close because ansi2html.sh considers `[39m` to be another new tag, whereas cli-highlight uses that to represent `plain`

What I am doing to get around this atm is s/[39m/[0m/g which is obviously naive, and not the best place to sort this out.

What part of this chain should be fixed? and what would be the best way to do that?

Thanks :)

Christopher

**Comment by christopherreay** [comment]
Im pretty sure that it is chalk that is outputting the terminal escape codes.

and Ive read issues on here with people discussing what [0m means... so aye, probably :)

**Comment by Qix-** [comment]
`[0m` means `reset everything`. `[39m` means `reset foreground color to default`.

**Comment by sindresorhus** [comment]
> because ansi2html.sh considers [39m to be another new tag

That's a bug in `ansi2html.sh` and should be reported there instead.

**Comment by sindresorhus** [comment]
Closing as Chalk is using ansi escape codes correctly, so there's nothing to do here.

**Comment by christopherreay** [comment]
Thank you so much for your time and expertise. 

:)

(in answer to your question, Im talking about ansi2html.sh from pixelbeat, processing log outputs that have colorized json in them. The pixel beat script is pretty old I think. In general I have found its output to be excellent for whatever reason.

cheers again )
