### ISSUE TITLE
Flow types don't work when using `require`

### ISSUE THREAD

**Issue by pranaygp** [chalk/chalk#264]
When using require:

```javascript
const chalk = require('chalk');
```

The flow types for `chalk` says:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/commands/login.js:34:42

Cannot call chalk.red because property red is missing in module chalk [1].

 [1]  4│ const chalk = require('chalk');
       :
     31│   if(!team) {
     32│     console.log('Failed to login')
     33│   } else {
     34│     console.log('Logged in as %s', chalk.red(team.name))
     35│   }
     36│
     37│   close()
```

and that's because the flow types expect you to explicitly require `default`. i.e.

```javascript
const chalk = require('chalk').default;
```

and only then does it work correctly. i.e. it seems like `index.flow.js` was built to support `import` but not `require`. @saadq could you take a look?

**Comment by saadq** [comment]
Opened a PR which should fix this [here](https://github.com/chalk/chalk/pull/265).

**Comment by sindresorhus** [comment]
This was fixed in https://github.com/chalk/chalk/commit/01cfb5c888481d044b90fcfebddb73defee602d7
