### ISSUE TITLE
chalk.bold does not work on macOS 10.12.6 and Node.JS 10

### ISSUE THREAD

**Issue by Tiendq** [chalk/chalk#270]
It's green but not **bold**.

```javascript
let chalk = require('chalk');
let log = console.log;

log(chalk.green.bold('### Listening on port %d in mode %s ###'), config.server.port, config.env.toUpperCase());
```

chalk ^2.4.1
macOS 10.12.6
NodeJS 10.0.0

<img width="595" alt="screen shot 2018-05-03 at 8 10 14 pm" src="https://user-images.githubusercontent.com/815910/39578329-18059402-4f0e-11e8-9760-2ec050a9124b.png">

**Comment by sindresorhus** [comment]
What terminal? You have probably turned off bold fonts:

<img width="337" alt="screen shot 2018-05-03 at 21 43 44" src="https://user-images.githubusercontent.com/170270/39583806-21543efc-4f1b-11e8-98e8-72f197e9b54e.png">

**Comment by Tiendq** [comment]
You're right, I was not aware of this Terminal option.

Thanks,
