### ISSUE TITLE
Destructuring `hex` not working

### ISSUE THREAD

**Issue by lauriejim** [chalk/chalk#271]
**Bug reporting**

It's not possible to destructure `hex` function.

**My code**

*Chalk version*: 2.3.2
*Node version*: 9.4

```js
const {hex} = require('chalk');
hex('#013370')('strapi');
```

**Error output**

```shell
TypeError: Cannot read property '_styles' of undefined
at ./node_modules/chalk/index.js:88:34
```

**Comment by Qix-** [comment]
This affects all `color-convert`-based styles.

**Comment by sindresorhus** [comment]
Closing per https://github.com/chalk/chalk/pull/282#issuecomment-408058327

**Comment by lauriejim** [comment]
@sindresorhus Okay, thank you for this information.

**Comment by bkuri** [comment]
@sindresorhus fyi I'm still experiencing this issue as of `v5.3.0` using ESM imports.

```js
import chalk from 'chalk'
const { bold, hex, red, yellow } = chalk
...

try {
  hex("#ffffff")
catch (error) {
  console.log(error)
}
```

returns:

```
TypeError: Cannot read properties of undefined (reading 'Symbol(STYLER)')
    at file:///.../node_modules/chalk/source/index.js:101:127
```
