### ISSUE TITLE
Accommodating dark/light terminals, specifically for `chalk.blue/chalk.white/chalk.black`

### ISSUE THREAD

**Issue by the1mills** [chalk/chalk#272]
I have this question on SO:
https://stackoverflow.com/questions/50027162/determine-terminal-tty-background-color-at-runtime/50205367

I am looking to figure out how to make `chalk.blue()` and `chalk.white()`/`chalk.black()` readable.

Right now, if the user is using a light colored terminal, `chalk.white()` is _gray_
And if the user is using a dark colored terminal, `chalk.black()` is _gray_.

I am looking for something where the color scheme is readable for all terminals, however I can do it.

**Comment by Qix-** [comment]
That's out of scope for this package. You can store the chalk functions in their own variables to use as color schemes if you'd like.

```javascript
const greyColor = isBackgroundDark() ? chalk.black : chalk.white;

console.log(greyColor("hello"));
```

**Comment by kentcdodds** [comment]
Anyone know of a definition for a `isBackgroundDark` function? How would one determine whether the background is dark (in a cross-platform way)?

**Comment by Qix-** [comment]
Hey @kentcdodds - none that I know of. Sorry for the bad news :/ Some terminals have their own programmatic access where they'll "reply" to control codes by sending information to stdin, but it's hacky and I've never really gotten it to work myself (not for lack of trying).

In my experience, it's best to treat the terminal as a one-way graphics device.

**Comment by kentcdodds** [comment]
Ok, thanks @Qix-!
