### ISSUE TITLE
Remove chalk after use

### ISSUE THREAD

**Issue by bennyn** [chalk/chalk#273]
In my application log statements are printed to the console and written to a log file. 

When the logs are printed to the console, I want them to be colorful (using chalk) but this has the side effect that statements in the log file are enclosed by special characters:

```bash
[32mThis text is green[39m and this text is not green.
```

Is there a good way of getting rid of the color placeholders (like `[32m` & `[39m`)?

**Comment by bennyn** [comment]
Ok, I found the solution. 😁 

To keep track of it:

```js
const ansiRegex = require('ansi-regex');
const text = '[32mThis text is green[39m and this text is not green.\n';
const withoutChalk = text.replace(ansiRegex(), '');
console.log('withoutChalk', withoutChalk);
```

**Comment by Qix-** [comment]
Yes, don't use chalk when logging to files.

**Comment by sindresorhus** [comment]
We have a module for this exact purpose: https://github.com/chalk/strip-ansi

**Comment by bennyn** [comment]
> We have a module for this exact purpose: https://github.com/chalk/strip-ansi

Even better!

But what do you think about making it a feature of `chalk` itself? I can think of something like a `on` and `off` method. Or even `clean` because sooner or later a "chalk" board needs to be cleaned. 😁
