### ISSUE TITLE
Color is not preserved when stdout is redirected 

### ISSUE THREAD

**Issue by aicioara** [chalk/chalk#274]
Hey, thank you for this package, it is really great. In one of my projects, I took a dependency on ink-quicksearch, which took a dependency on ink, which took a dependency on chalk, which brought me here. 

The issue I am facing is when I combine a npm script with pipes and redirrects, as that removes the color.

I have a repro below. To make it easier, I am printing to stderr and I am redirecting the stdout.

```jsx
#!/usr/bin/env node

const chalk = require('chalk');
console.error('\x1b[36m%s\x1b[0m', 'This text will be printed colorful');
console.error(chalk.blue('This text is white :('));
```

Then run as 

```bash
node main.jsx # This works as expected
node main.jsx > tmp.txt # Bug here 
```

Is this something easy to fix? If not, do you find this to be an issue or a feature? If it is an issue, I can invest time and fix it, just wanted to make sure it is not like this by design.

Thanks!

Edit: I am using `gnome-terminal`

**Comment by Qix-** [comment]
This is intended. Please read the readme.

**Comment by Qix-** [comment]
https://github.com/chalk/chalk#chalksupportscolor

**Comment by mrinalini-m** [comment]
Run `node main.jsx > tmp.txt --color` instead of `node main.jsx > tmp.txt` to preserve the log colors.

**Comment by jarraga** [comment]
> Run `node main.jsx > tmp.txt --color` instead of `node main.jsx > tmp.txt` to preserve the log colors.

that works for me, thanks you!
