### ISSUE TITLE
Can we get pink and purple?

### ISSUE THREAD

**Issue by julieturbina** [chalk/chalk#277]
You forgot pink and purple!
Girl in tech!!!

**Comment by sindresorhus** [comment]
You can get any color, including pink and purple, if your terminal supports more than 16 colors, which most terminals do today. See: https://github.com/chalk/chalk#256-and-truecolor-color-support

```js
const chalk = require('.');
console.log(chalk.keyword('pink')('Pink'), 'and', chalk.keyword('purple')('purple'));
```

<img width="267" alt="screen shot 2018-06-01 at 14 18 39" src="https://user-images.githubusercontent.com/170270/40827059-b79a504e-65a6-11e8-9f51-369389655325.png">
