### ISSUE TITLE
Style nesting does not work on windows

### ISSUE THREAD

**Issue by Dmitriy-kiselyov** [chalk/chalk#278]
I've tried an example from your readme and it worked incorrectly
```js
// Nest styles
log(chalk.red('Hello', chalk.underline.bgBlue('world') + '!'));
```
`Hello` was colored in red, but `word` was not.

I've thought this has to do something with broken nesting, but look what I have got changing arguments' places:
```js
chalk.red(chalk.underline.bgBlue('world') + '!', 'Hello')
```
![image](https://user-images.githubusercontent.com/25789153/40811339-7c88d696-6539-11e8-9523-dc2a4a684632.png)
I'm using Windows 10, WebStorm console window

**Comment by sindresorhus** [comment]
This looks like an issue with the WebStorm console. I would open an issue on the WebStorm project instead. This is not something can or should work around.
