### ISSUE TITLE
Error installing  in windows 10

### ISSUE THREAD

**Issue by brakdag** [chalk/chalk#279]
>npm i chalk
npm WARN saveError ENOENT: no such file or directory, open 'D:\test\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'D:\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ chalk@2.4.1
added 7 packages in 2.613s

Why it WARN?

**Comment by sindresorhus** [comment]
This is not related to Chalk at all.
