### ISSUE TITLE
Chalkie: browser support for Chalk

### ISSUE THREAD

**Issue by shawwn** [chalk/chalk#284]
In regards to #1 , I implemented [Chalkie](https://github.com/shawwn/chalkie#readme), which is Chalk for the browser.

Since #1 comes up in search results, would it be possible for me to post this comment there? I notice it's locked.

**Comment by shawwn** [comment]
(Mostly @Qix- )

**Comment by shawwn** [comment]
Good point about the uppercase. I’ll change that shortly.

The screenshot shows that chalkie is working correctly. You have to run it through AnsiHTML to get html, which chalkie also exposes. Try `AnsiHTML(Chalk.red(‘foo’))`

The idea is that I wanted a consistent way to style text both in terminal and on the web. Chalk is perfect since it simply generates ansi escape codes. The output of chalkie can be fed into xterm.js, converted to html using AnsiHTML, or stripped of ansi sequences (not provided).

To accomplish this, I manually set chalk.enabled to true and chalk.level to 2 after setting it globally. If you want plain text you can just set .enabled to false.

Thanks for the critique. Do you have any other suggestions before I open the PR?

**Comment by Qix-** [comment]
Nope :)

**Comment by sindresorhus** [comment]
Closing for lack of response and use-case.

**Comment by rayfoss** [comment]
> I don't understand the use-case for this. Why would you ever want to use Chalk to style HTML? I understand it could be a fun experiment, but what practical purpose does it serve? CSS is much better at styling than Chalk is. And Xterm.js already supports ansi escapes.

The use case: One interface for headless browser testing, continuous integration/deployment with more readable logs.
