### ISSUE TITLE
Error with index.js.flow:5

### ISSUE THREAD

**Issue by stephenotalora** [chalk/chalk#294]
Hi when running a build through `flow` either via `webpack` and/or `husky` my build fails on this line: https://github.com/chalk/chalk/blob/master/index.js.flow#L5

Error: 
```
node_modules/@babel/highlight/node_modules/chalk/index.js.flow:5
                         v--------
  5: export type Level = $Values<{
  6: 	None: 0,
  7: 	Basic: 1,
...:
 10: }>;
     -^ identifier `$Values`. Could not resolve name
```

anyone aware of this error? anyone available to help?
<img width="402" alt="screen shot 2018-09-03 at 8 03 36 am" src="https://user-images.githubusercontent.com/6519974/44993570-e8ee2b00-af4f-11e8-955d-de044cc6fb5e.png">

**Comment by stephenotalora** [comment]
closing as this is an issue with my local flow being behind.

**Comment by nitaking** [comment]
me too
