### ISSUE TITLE
TypeScript error when using --isolatedModules

### ISSUE THREAD

**Issue by robcresswell** [chalk/chalk#295]
Hi! Sorry to bother you, but your type definitions seem to be throwing an error when compiling TS:

```
$ tsc
node_modules/chalk/types/index.d.ts:4:19 - error TS1209: Ambient const
enums are not allowed when the '--isolatedModules' flag is provided.

export const enum Level {
                  ~~~~~
```

**Comment by strothj** [comment]
tsconfig.json:
```js
{
  "compilerOptions": {
    // Disallow features that require cross-file information for emit.
    "isolatedModules": true,
  }
}
```

The `isolatedModules` flag is recommended when using Babel 7 to transpile TypeScript. Some more information is available here:
https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/

**Comment by sindresorhus** [comment]
https://github.com/chalk/chalk/pull/296#issuecomment-418789492
