### ISSUE TITLE
Ts in the wrong report

### ISSUE THREAD

**Issue by MinaAndLuoXia** [chalk/chalk#297]
![webwxgetmsgimg 1](https://user-images.githubusercontent.com/42334571/45345043-c7d4ac80-b5d7-11e8-8d55-6258716328b6.jpg)
In ionic and angular

**Comment by Qix-** [comment]
I have no idea what this stacktrace or your issue mean. Could you please post some code?

**Comment by MinaAndLuoXia** [comment]
I didn't write chalk-related code, but I declared chalk errors at runtime, and I'm not really sure it's a chalk problem.

**Comment by Qix-** [comment]
Please try deleting any lockfiles you have, remove your `node_modules` folder and re-install your dependencies. I've seen something like this before.

**Comment by MinaAndLuoXia** [comment]
Thank you. I will try.
