### ISSUE TITLE
Support for outputting object content instead of `object [Object]`

### ISSUE THREAD

**Issue by JanisE** [chalk/chalk#298]
Please, add support for outputting object content instead of `object [Object]`!

For example, I can do this:
`console.log('Hello world!', 5, {sss: 0});`

I would love to be able to this, too:
`console.log(colors.info('Hello world!', 5, {sss: 0}));`
as opposed to the original:
`Hello world! 5 { sss: 0 }`

Currently, "Chalk" outputs ``.

I cannot use the "colors.js" package, too, because even though it outputs the content of objects, it outputs only the first argument and ignores all the rest.

**Comment by sindresorhus** [comment]
Chalk is meant to colorize strings. It's up to you to serialize it first. You could, for example, use `require('util').format()` for this. You could also use `console.log` string substitution: `console.log(chalk.green('Object: %O'), object);`, see: https://nodejs.org/docs/latest/api/console.html#console_console_log_data_args
