### ISSUE TITLE
Auto-detect support for `stderr`

### ISSUE THREAD

**Issue by langpavel** [chalk/chalk#301]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2480%20Funded-%2300A156.svg" />](https://issuehunt.io/r/chalk/chalk/issues/301)

I want use colors only on `console.error` calls which is typically terminal.
I suggest some API extension, very easy idea is chaining like this:
```js
const coloredOutput = chalk.stderr.red('RED ALERT');
```
This can be used more easily like this:
```js
const chalk = require('chalk').stderr;
const coloredOutput = chalk.red('RED ALERT');
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)
### Submitted pull Requests
- [#359 Add chalk.stderr and chalk.stderr.supportsColor](https://issuehunt.io/r/chalk/chalk/pull/359)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/chalk/chalk/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by langpavel** [comment]
If I write it correctly, workaround for this is pretty cumbersome now:
```js
const supportsColor = require('supports-color');
const chalk = require('chalk');
chalk.level = supportsColor.stderr.level;
chalk.enabled = chalk.level > 0;
```

**Comment by Qix-** [comment]
> `require('chalk').stderr;`

I don't mind this, really. I think it's the best solution API-wise, but implementation might look a bit like a hack - we'd want to lazy load which means a property getter.

Thoughts @sindresorhus?

**Comment by langpavel** [comment]
Property getter is really fine, really. I'm fine now with the hackish code above but I cannot recommend altering `chalk.level` and `chalk.enabled` globally.
I will be really happy with `require('chalk').stderr` because it don't need alter global state of chalk

**Comment by Qix-** [comment]
@langpavel you can already create a new Chalk instance.

https://github.com/chalk/chalk#chalklevel

```javascript
const chalkErr = new chalk.constructor(supportsColor.stderr.level);
```

**Comment by langpavel** [comment]
looks much better, thanks!

**Comment by Qix-** [comment]
I think we're still deciding. I try to allow @sindresorhus to comment on changes to API decisions before any sort of "help wanted" tag is added.

**Comment by langpavel** [comment]
I just published `chalk-stderr` with this package and `supports-color` as peer dependency.

**Comment by langpavel** [comment]
I can recommend something like:
```js
const cherr = require(`chalk/stderr`)
```

**Comment by Qix-** [comment]
I like that actually. @sindresorhus thoughts?

**Comment by sindresorhus** [comment]
Yeah, let's go with `const chalkStderr = require(`chalk/stderr`)`. PR welcome :)

**Comment by sindresorhus** [comment]
For anyone that wants to tackle this, see the previous attempt and the feedback: https://github.com/chalk/chalk/pull/317
