### ISSUE TITLE
Background + Bold + Black = Grey

### ISSUE THREAD

**Issue by KeironLowe92** [chalk/chalk#303]
When using a background colour, setting the text to black and bold makes the text grey instead. Screenshot attached of code and output. 

Using Hyper on OSX Mojave, although I know it happens on High Sierra as well. Doesn't seem to happen in normal terminal, so not sure if it's an issue with Hyper?

**Comment by KeironLowe92** [comment]
Closed as it looks like it's an issue with XTerm.js which Hyper uses, see [here](https://github.com/xtermjs/xterm.js/issues/484)

**Comment by Qix-** [comment]
Not an issue, really - xterm.js is following what most emulators do (including Windows). Bright black is a dark grey, which is (obviously) brighter than black and darker than the regular (non-bright) grey, which is (obviously) darker than bright grey, which is white.

If that was confusing (probably was), here's a better way of looking at it:

```
black -> bright black -> grey -> bright grey (white)
30       30;1 / 90       37      37;1 / 97
40       40;1 / 100      47      47;1 / 107

```
