### ISSUE TITLE
Possible error created in linux

### ISSUE THREAD

**Issue by AndrewRayCode** [chalk/chalk#31]
We are seeing this happen in `chalk`:

```
node_modules/gulp-ruby-sass/node_modules/chalk/node_modules/escape-string-regexp/index.js:4
throw new TypeError('Expected a string');
    ^
```

This was not previously happening. Appears to be related to the changes made 3 days ago. I cannot reproduce this in OSX

The command we're running is gulp sass, which apparently depends on chalk.

**Comment by netpoetica** [comment]
FWIW my team and I are seeing the exact same error, seems to be something to do with npm running test command, running mocha w/ ts-node runtime TypeScript compilation.

```
➜  node -v
v8.6.0
➜  npm -v
5.4.2
```

Will update here if we solve it. But this one is pretty nasty!
