### ISSUE TITLE
Support for console.table()

### ISSUE THREAD

**Issue by Recycling-Bin** [chalk/chalk#311]
When attempting to use `console.table(<Object>)` and chalk together, data represented is malformed: 
![image](https://user-images.githubusercontent.com/39171349/49264210-5e687b00-f41b-11e8-869c-b33a287faca1.png)
This is what it looks like without chalk usually:
![image](https://user-images.githubusercontent.com/39171349/49264235-7b9d4980-f41b-11e8-81ef-9430944e6c30.png)

I am using a constructor to create new objects inside of JSON arrays and returning the data to `console.table()` Chalk for some reason does not seem to support the use of the table method and neither does any other console styling package out there. I would like to see support for this (you know, if possible).

**Comment by Qix-** [comment]
I'm confused as to what's actually breaking. Could you provide some example code?

**Comment by lebster** [comment]
Hi, I am also having this issue. Here is an example code and details.

Node - v10.16.0
chalk -  "^2.4.2",

![image](https://user-images.githubusercontent.com/914433/65141476-8c787500-d9c5-11e9-9f99-ea3ac8b351e8.png)

`const chalk = require('chalk');

console.table([
    { "LEFT": chalk.blue('Hello'), "RIGHT": ' World' },
    { "LEFT": chalk.red('Hello'), "RIGHT": ' World' }
]);`

**Comment by Qix-** [comment]
This isn't chalk's fault, it's `console.table`'s. It's doing a `require('util').inspect()` on it. There's nothing chalk can do about that.

**Comment by lebster** [comment]
Ah okay, thank you!
