### ISSUE TITLE
Incorrect types for chalk in tagged template literal form

### ISSUE THREAD

**Issue by vanbujm** [chalk/chalk#314]
I am using chalk to do some logging and I noticed this issue.
```
chalk`{black.bold  Worker:${process.pid}: } {blue.bold job received}: ${job.id}`
```
In this case I am giving chalk two numbers instead of strings.
Typescript complains about this because chalk's tagged template literal form is defined as 
```
(text: TemplateStringsArray, ...placeholders: string[]): string;
```
In my case placeholders contains numbers. 

Now I could fix this by doing  
```
chalk`{black.bold  Worker:${`${process.pid}`}: } {blue.bold job received}: ${`${job.id}`}`
```
but that feels wrong.

Ideally it would be some type union of things easily parsed to string (<string>|<number>|etc etc)
```
(text: TemplateStringsArray, ...placeholders: ParseableToString[]): string;
```

**Comment by Qix-** [comment]
Yeah agreed, this is wrong. Can someone from the typescript community submit a fix? I don't know enough of it.

**Comment by Qix-** [comment]
The types you can interpolate are any type. We don't enforce anything.

**Comment by vanbujm** [comment]
The typing enforces that the values you interpolate are strings.
`index.d.ts:30` as seen above:
`(text: TemplateStringsArray, ...placeholders: string[]): string;`

Unless I am mistaken this line defines the tagged template literal.
where `text` will be your broken up input string around each `${}` and `placeholders` is an array of inputs that the user is trying to interpolate. 

ie: 
```
chalk`part1 ${foo} part2`
```
Would be `chalk( ["part1 ", " part2"], [foo] )`
If `foo` was anything other than a string, Typescript will complain saying "Argument <fooType> is not assignable to type string".

**Comment by Qix-** [comment]
And what I'm saying is we don't care what the placeholder types are...

**Comment by vanbujm** [comment]
Shall I submit a fix then with type `any`?

**Comment by Qix-** [comment]
Sure, but I'd like to get a confirmation that `any` is the correct thing to do here. Like I said, I have no idea how Typescript types work.

**Comment by sindresorhus** [comment]
Yes, it should be `any` or rather `unknown` would be even better.

**Comment by langpavel** [comment]
Ohh, sorry, reference from 317 is invalid (should be to 318 not to this 314). I fixed it but reference will stay :-\
