### ISSUE TITLE
'redBright' doesn't work when level 3 is detected.

### ISSUE THREAD

**Issue by ngbrown** [chalk/chalk#320]
The readme seems to imply that `chalk.keyword('redBright')('some text')` should always work.  However, it throws an exception when the console is detected as level 3 (16M colors).

It seems to be happening because `color-convert` doesn't have that color in it's `cssKeywords` list.

**Comment by Qix-** [comment]
```
chalk.redBright('some text')
```

As the readme states, `.keyword()` is for [CSS keywords](https://www.w3.org/wiki/CSS/Properties/color/keywords). You can't pass chalk property names into it - that's not what it's for.
