### ISSUE TITLE
Can I define my own RGB color definitions and use the assigned variable name?

### ISSUE THREAD

**Issue by davidkjackson54** [chalk/chalk#321]
I have searched the doc but not found a definitive answer to this. Apologies if I missed something obvious.
I want to create my own RGB color for example  - mycyan as RGB(77, 190, 218) and then use the mycyan variable within Chalk perhaps as chalk.rgb(mycyan) etc.    
Again, sorry in advance if this is a dumb question. I haven;t been able to fathom out if this is possible and have tried various attempts.

**Comment by Qix-** [comment]
```javascript
const myCyan = chalk.rgb(77, 190, 218);
console.log(myCyan("hi"));
```

Does that not work?

**Comment by davidkjackson54** [comment]
Yes of course... mental block on my part.  Many apologies.
