### ISSUE TITLE
chalk parser

### ISSUE THREAD

**Issue by lifeiscontent** [chalk/chalk#324]
I'd like to make my own React based terminal that supports ansi colors.

I was wondering if there was a way to parse a string with ansi in it to get all the stylistic rules like hex/rgb/bold/etc via chalk somewhere.

ideally this format would be something like:

`[{text: 'Hello', style: {color: '#ff0000', fontWeight: 'bold'}]`

any pointers would be much appreciated. Thanks!

**Comment by Qix-** [comment]
The wikipedia page is a good start. Just look for the CSI character and parse accordingly.

Keep in mind that there are lots of different codes, etc.

https://en.wikipedia.org/wiki/ANSI_escape_code

You're in for a long, winding rabbit hole :)
