### ISSUE TITLE
Chalk code completion not working

### ISSUE THREAD

**Issue by vanshu** [chalk/chalk#326]
IDE: visual studio code Version 1.31.1 (1.31.1)
Code completion not working when I use chalk library
```
const chalk=require('chalk')
```

I checked chalk version on rpm , it's 2.4.2, when typeit doesn't show the method like green() ,red(),blue() etc.

**Comment by sindresorhus** [comment]
You need to import it as `const chalk = require('chalk').default` to get type completion in JS.
