### ISSUE TITLE
Not working with Worker Threads

### ISSUE THREAD

**Issue by ofarukcaki** [chalk/chalk#327]
I'm using chalk with my code which uses [Worker Threads](https://nodejs.org/api/worker_threads.html#worker_threads_worker_workerdata), 

**log(chalk.blue("text"))**  is working inside main but not working inside child processes. Just prints my text without coloring.

**Comment by Qix-** [comment]
Because child processes are piping their output to a non-TTY file descriptor.

In your parent code, you can do:

```javascript
process.env['FORCE_COLOR'] = chalk.level.toString();
```

That _should_ fix it. Let me know if it doesn't.
