### ISSUE TITLE
Give some method to use original "blue" even under Windows

### ISSUE THREAD

**Issue by be5invis** [chalk/chalk#329]
I saw this in `index.js`

```js
// Use bright blue on Windows as the normal blue color is illegible
if (isSimpleWindowsTerm) {
	ansiStyles.blue.open = '\u001B[94m';
}
```

But sometimes we may need to explicitly use the original `blue` even if it is not legible.

**Comment by sindresorhus** [comment]
I don't see how that would work in other than your own scripts, as if you choose to use a method that gives you the original "blue", you'll make it unreadable for everyone with the default palette, which from experience, means most Windows users.

You work for Microsoft. Get them to fix the palette instead so we don't need this annoying workaround ;)

**Comment by sindresorhus** [comment]
> But sometimes we may need to explicitly use the original blue even if it is not legible.

When? Use-cases please.

**Comment by be5invis** [comment]
Dark text on a white background.

**Comment by be5invis** [comment]
The default palette should be changed during RS3? I did not remember.

**Comment by be5invis** [comment]
@sindresorhus The default colors did change in the past. Perhaps during RS3? I did not remember. Though the changes does not apply to upgrades (they apply to fresh installs only).

**Comment by be5invis** [comment]
@sindresorhus 
https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/
Yeah, RS3.
