### ISSUE TITLE
number to string casting (typescript: not assignable)

### ISSUE THREAD

**Issue by faeb187** [chalk/chalk#338]
```typescript
// PLS do number to string casting automatically
console.log(chalk`{yellowBright ${i.toString()} tries}`)
```
ATM it throws a not assignable error when using without .toString()

**Comment by Qix-** [comment]
This doesn't seem to have anything to do with chalk. Can you explain what's happening?

**Comment by marcelh-gh** [comment]
The code from the examples does not compile with TypeScript.
There must be a bug in the Chalk type definitions.

```
// ES2015 tagged template literal
log(chalk`
CPU: {red ${cpu.totalPercent}%}
RAM: {green ${ram.used / ram.total * 100}%}
DISK: {rgb(255,131,0) ${disk.used / disk.total * 100}%}
`);
```

This creates the compile error
`Argument of type 'number' is not assignable to parameter of type 'string'.ts(2345)`
with the values for `cpu.totalPercent` etc being numbers.

**Comment by Qix-** [comment]
Ah, that's more clear.

**Comment by sindresorhus** [comment]
This was fixed in https://github.com/chalk/chalk/commit/7f6e5630b0097774d6961e9c0921697a300fbd0f and will be available in Chalk 3.
