### ISSUE TITLE
Crash report, memory leak?

### ISSUE THREAD

**Issue by Somebi** [chalk/chalk#339]
<--- Last few GCs --->

[32702:0x3a44d00]  5534020 ms: Mark-sweep 1350.6 (1426.3) -> 1349.7 (1427.3) MB, 1112.6 / 0.0 ms  (average mu = 0.117, current mu = 0.013) allocation failure scavenge might not succeed
[32702:0x3a44d00]  5534992 ms: Mark-sweep 1350.6 (1427.3) -> 1349.6 (1427.3) MB, 964.2 / 0.0 ms  (average mu = 0.068, current mu = 0.008) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1cda774dc01d]
    1: StubFrame [pc: 0x1cda7748d608]
    2: StubFrame [pc: 0x1cda77a10642]
Security context: 0x3e06214c1eb9 <JSObject>
    3: build [0x27fff1f61641] [/var/local/project/node_modules/chalk/index.js:144] [bytecode=0x3713f8f4fa1 offset=119](this=0x2bfa501dafa9 <JSFunction Chalk.chalk.template (sfi = 0x2bfa501daa49)>,_styles=0x054a42aa9c21 <JSArray[1]>,_empty=0x02f6ea5826f1 <undefined>,key=0x2b0c1e39f809 <St...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8d1bc0 node::Abort() [node]
 2: 0x8d1c0c  [node]
 3: 0xb00bae v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb00de4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xeee2b2  [node]
 6: 0xeee3b8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xefa4e2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xefae14 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xefda81 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xec6fa4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x11660ce v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0x1cda774dc01d 
Aborted (core dumped)

**Comment by sindresorhus** [comment]
What Node.js version and OS version? Please also include a code snippet that reproduces the issue.

**Comment by Somebi** [comment]
Ubuntu 16.04, node latest

чт, 4 апр. 2019 г., 20:34 Sindre Sorhus <notifications@github.com>:

**Comment by Qix-** [comment]
Can you specify which version of node? Some people think they have latest but do not. Also, the more version changes frequently.
