### ISSUE TITLE
Template literals are unsupported for nested calls

### ISSUE THREAD

**Issue by ExE-Boss** [chalk/chalk#341]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/chalk/chalk/issues/341)

The following is unsupported despite it being allowed by the type system:
```ts
chalk.bold`Hello, {cyan.inverse ${name}!} This is a test. {green ${exclamation}!}`;
```
Produces:
```
Hello, {cyan.inverse ,!} This is a test. {green ,!} Sindre Neat
```
Instead of:
```
Hello, Sindre! This is a test. Neat!
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Submitted pull Requests
- [#392 Support for template literals for nested calls](https://issuehunt.io/r/chalk/chalk/pull/392)
- [#398 Support nested calls](https://issuehunt.io/r/chalk/chalk/pull/398)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/chalk/chalk/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by i-break-codes** [comment]
Just came to say this, I can't do the following, for example:

```
function test(message) {
  console.log(chalk`
    ${message}
  `);
}
test('There are {bold 5280 feet} in a mile. In {bold miles}, there are {green.bold feet}.')
```

Outputs as `There are {bold 5280 feet} in a mile. In {bold miles}, there are {green.bold feet}.`

Any solution to the above?

**Comment by Qix-** [comment]
@i-break-codes The OP is an entirely different issue. What you want is specifically not supported. You'll need to write a template literal wrapper, as template literals are not as simple as a function call.

**Comment by sindresorhus** [comment]
So what needs to be done here is to change the TypeScript types to not allow the template literal on chalk sub-properties like `chalk.bold`, correct?

**Comment by Qix-** [comment]
Correct.

**Comment by ExE-Boss** [comment]
I feel like fixing the TypeScript definition is not worth 40 bucks.

I’d much rather prefer if this was implemented so that:
```js
chalk.red`foo ${bar}`;
```
and
```js
chalk`{red foo ${bar}}`;
```
were equivalent.

That way, bugs like https://github.com/mdn/browser-compat-data/pull/4480 could be more easily avoided.

**Comment by sindresorhus** [comment]
I agree, would be better to actually support that.

**Comment by Qix-** [comment]
Supporting that is going to introduce more branching to the individual styles in order to check to see if the passed arguments match that of a tagged template invocation (since there's no quick way to check).

I **really** wish the folks at the tc39 thought about this; the design is horrendous. I really wish they had created a specified function property that was invoked instead, so you'd have

```javascript
function foo() {
    console.log('regular invocation');
}

foo.tag = function() {
    console.log('tagged invocation');
}

foo(); // regular invocation
foo`hello`; // tagged invocation
```

But alas, we have to check the existence of random properties and arrays.

**Comment by sindresorhus** [comment]
Let's fix the TypeScript definition for now, and we can look into allowing it later on, as long as the performance is not impacted (which seems hard).

**Comment by jsejcksn** [comment]
> as long as the performance is not impacted

Maybe the performance tradeoff will be worth it? Are there perf tests to inform a decision?

**Comment by toonijn** [comment]
I proposed a solution in #392 . The behavior of
![Selection_027](https://user-images.githubusercontent.com/9020072/78109429-737f6080-73f9-11ea-8c48-ae815e701b1d.png)
has not changed, so there is backwards compatibility without performance hit.

Only when the functions is called as a template literal, the template substitution will be evaluated:
![Selection_028](https://user-images.githubusercontent.com/9020072/78109472-8abe4e00-73f9-11ea-92b8-86a54d3a2c4e.png)

Note the difference between ``chalk.bold(`...`` and ``chalk.bold`...``

**Comment by Qix-** [comment]
> without performance hit

You cannot possibly assert this. There is no special function invocation for template literals aside from different argument types, so you'd have to do a branch (an `if` statement) in order to determine if you're being called as a literal.

Branches are very much overhead, and can be quite detrimental in tight loops if gone unchecked.
