### ISSUE TITLE
chaining is not working as expected

### ISSUE THREAD

**Issue by CGottschallJ** [chalk/chalk#345]
Hello Team,

This is my first time using the package, so it likely could be user error.  However, I am attempting to chain both green and bold but I am only having the bold show up.

Node: 8.11.3
NPM: 6.9.0
Chalk: 2.4.2

```
const chalk = require('chalk');

const msg = chalk.bold.green('success!');

console.log(msg);
```

![image](https://user-images.githubusercontent.com/27632563/58064020-917c0380-7b4e-11e9-873e-1a2633bdcdd4.png)

I have tried switching the two around to no avail.  Any ideas?

**Comment by Qix-** [comment]
- What terminal are you using? (e.g. iTerm2, ConEmu, Xterm, etc)
- What OS?
- What is the output of `echo $TERM`?

You're using chalk correctly, so I'd boil it down to your terminal emulator.

**Comment by CGottschallJ** [comment]
Thank you for the quick response!  I am not currently around my personal laptop but I can tell you that I am using iTerm 2 and that my operating system is mac os 10.10 Yosemite.

**Comment by Qix-** [comment]
I use iTerm2 as well and can safely say I'm not facing this issue. I'd check your TERM variable.

**Comment by CGottschallJ** [comment]
After sending the command `echo $TERM` i received `xterm-256color`

**Comment by Qix-** [comment]
This doesn't make much sense, iTeem2 is usually the last on the list in terms of emulator bugs. Try creating an entirely new terminal profile that uses all defaults.

Also, see if the following outputs green text:

```
printf '\x1b[32;1mhello\x1b[m`
```

**Comment by CGottschallJ** [comment]
Hey, It seems that it was the theme I was using.  I removed iTerm from my system, reinstalled, and chose a different theme.  Seems to be working now!  

Thank you for your help!
