### ISSUE TITLE
rgb color bug

### ISSUE THREAD

**Issue by xgqfrms** [chalk/chalk#346]
#  rgb color bug

![image](https://user-images.githubusercontent.com/7291672/58399927-4b61fb00-808c-11e9-9182-6d071fafba37.png)

```js
    // log(`${chalk.rgb(255, 0, 255).bgBlack("unknown type")}`);
    // log(chalk.rgb(255, 0, 255).bgBlack("unknown type"));
    // log(chalk.rgb(123, 45, 67).underline("unknown type"));
    log(chalk.rgb(255, 0, 0).bgBlack("unknown type"));
    log(chalk.rgb(0, 255, 0).bgBlack("unknown type"));
    log(chalk.rgb(0, 0, 255).bgBlack("unknown type"));

```

**Comment by xgqfrms** [comment]
# bold bug 

![image](https://user-images.githubusercontent.com/7291672/58400060-a267d000-808c-11e9-80aa-1a958faf2cbf.png)


```js

    log(chalk.rgb(255, 0, 255).bold("unknown type"));
    log(chalk.rgb(123, 45, 67).underline("unknown type"));

```

**Comment by Qix-** [comment]
This is most likely a problem with your editor. Namely when using .rgb(), there's nothing magical going on. This is usually a problem with your terminal emulator.

Please let me know if that's not the case.

**Comment by xgqfrms** [comment]
I'm using the terminal of build in VS Code

**Comment by Qix-** [comment]
I would say so, yes.
