### ISSUE TITLE
Bug: bracketed Unicode escapes not supported

### ISSUE THREAD

**Issue by j-f1** [chalk/chalk#349]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/chalk/chalk/issues/349)

Repro:

```js
// example.js
const chalk = require('chalk')

console.log(chalk`\u{2192} Running test {bold foo}...`)
```

Expected output:
<pre><code>&#x2192; Running test <strong>foo</strong>...</code></pre>

Actual output:
```
Error: Found extraneous } in Chalk template literal
    at node_modules/chalk/templates.js:109:11
    at String.replace (<anonymous>)
    at module.exports (node_modules/chalk/templates.js:99:6)
    at chalkTag (node_modules/chalk/index.js:221:9)
    at Chalk.chalk.template (node_modules/chalk/index.js:36:20)
    at Object.<anonymous> (example.js:3:17)
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($50.00)
### Submitted pull Requests
- [#350 Fix bracketed unicode escapes in template literals](https://issuehunt.io/r/chalk/chalk/pull/350)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/chalk/chalk/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Qix-** [comment]
TIL this existed. Thanks for the report :)
