### ISSUE TITLE
Random color picking function

### ISSUE THREAD

**Issue by arshadkazmi42** [chalk/chalk#353]
I feel, if chalk can expose a random function which will pickup any random color and print it that will be really useful.

Any thoughts?

**Comment by sindresorhus** [comment]
Useful for what? The bar for including new things in Chalk is very high. You need to be convincing.

**Comment by arshadkazmi42** [comment]
I have one use case which I need it for.
I have some logs which is not specific to any color, I just want it to be colored.
In this case, I can just use `chalk.random` and it will pickup any random color configured in chalk.

Right now this is the only use case I have.

**Comment by Qix-** [comment]
Why not write this function yourself? In the decade I have been writing colored console applications Ive never needed this once.

**Comment by arshadkazmi42** [comment]
Looks like its more my usecase then a general one.
I guess writing my own function would be a better option

**Comment by sindresorhus** [comment]
You could use https://github.com/sindresorhus/randoma#randomcolorsaturation and pass it to `chalk.hex`.
