### ISSUE TITLE
Jest + Chalk Snapshot test in normal vs CI run

### ISSUE THREAD

**Issue by ktalebian** [chalk/chalk#355]
I'm using `chalk` `v2.4.2`. If you run tests normally (i.e. `jest`) the snapshots generated would have the bash coloring. For example:

`[1m[32mDevelopment[39m[22m`

When you run in CI, (i..e `CI=true jest`), they do not, for example:

`Development`

To fix this, right now my package.json's script `"test": "CI=true jest"`. What's the fix so I can still get the nice coloring when running locally but not fail when running in CI?

**Comment by sindresorhus** [comment]
https://github.com/chalk/chalk#chalksupportscolor
