### ISSUE TITLE
Remove some color types

### ISSUE THREAD

**Issue by Qix-** [chalk/chalk#360]
HCG was added after `color-convert` was added to ansi-styles. We should officially support it in `ansi-styles` and document its support here. It's similar to HSL and is (slowly) increasing in popularity.

**Comment by sindresorhus** [comment]
I would honestly rather remove some colors than add more. In hindsight, we should IMHO, only have added `rgb`, `hex`, and `hsl`. Everything else is just bloat that very few use. Each added color space adds mental overhead for the user, noisy auto-complete, etc. So no, I don't think we should add a color space that almost no one uses. We can reconsider if it gets added to the CSS spec. That's usually a good sign of it becoming mainstream.

**Comment by sindresorhus** [comment]
@Qix- 👍
