### ISSUE TITLE
types(and rest of files) on the master branch do not represent latest version (2.4.2)

### ISSUE THREAD

**Issue by dkuida** [chalk/chalk#362]
Hello

master branch is up to date with version 2.4.1 which has different types and in fact even a tad different interface

```
chalk.supportsColor = false
```

for example, is an invalid assignment - and does not really do anything.

is it an oversight - or there is a reasoning behind it

**Comment by sindresorhus** [comment]
This is explained in the release notes: https://github.com/chalk/chalk/releases/tag/v2.4.2
