### ISSUE TITLE
ts-jest users cannot use Level (const enum) when isolatedModules is enabled and diagnostic is disabled

### ISSUE THREAD

**Issue by KSXGitHub** [chalk/chalk#363]
## Problem

Let's say we have a TS file:

```typescript
// index.ts
import { Level } from 'chalk'
console.log(Level.Basic)
```

Use `tsc` to try compile it with `--isolatedModules`:

```sh
tsc --isolatedModules --module commonjs --esModuleInterop --target es2018 index.ts
```

This should print an error:

```
error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.
```

However, when using `ts-jest` with `diagnostic: false` (ignore all TS errors), it emits a JavaScript code equivalent to:

```javascript
const { Level } = __importDefault(require('chalk')) // Level = undefined
console.log(Level.Basic) // TypeError: Cannot read property 'Basic' of undefined
```

## Suggestions

This can be fixed by doing either:

### 1. Replace the [`const enum LevelEnum`](https://github.com/chalk/chalk/blob/6b4d20683f7490195e51f80829f3d465b9835de1/index.d.ts#L1) with a combination of type union and namespace

```typescript
type Level = 0 | 1 | 2 | 3
```

This would be a **breaking change** as TS users would no longer be able to use `Level.Basic` in place of `1` like they used to.

### 2. Preserve the const enum, and add `Level` object to the JavaScript file.

```javascript
module.exports.Level = {
  None: 0,
  Basic: 1,
  Ansi256: 2,
  TrueColor: 3
}
```

This would **not** be a breaking change.

**Comment by KSXGitHub** [comment]
@sindresorhus Please do one of 2 proposal instead. See https://github.com/chalk/chalk/commit/066c38a685b98ca64e7da5c10bc29120375ee16e#commitcomment-35182661 for reasons.

**Comment by sindresorhus** [comment]
Alright. Let's go with `2` then.
