### ISSUE TITLE
Simplify output for nested chalk tags

### ISSUE THREAD

**Issue by ExE-Boss** [chalk/chalk#365]
Currently, nested chalk tags in a template reset and re‑specify everything, instead of just what needs to be modified for that level of nesting.

## Code
```js
chalk`{red  red {bold  red & bold } red again }`
```

## Expected result:
```
\e[31m red \e[1m red & bold \e[22m red again \e[39m
```

## Actual result:
```
\e[31m red \e[39m\e[31m\e[1m red & bold \e[22m\e[39m\e[31m red again \e[39m
```

## See also:
- https://github.com/mdn/browser-compat-data/pull/4265

**Comment by sindresorhus** [comment]
Yes, that would be ideal, but it's not a big problem as the visual output is still correct.

**Comment by Qix-** [comment]
There's somewhat a reason for this; dim and bold have the same exit code and thus added some complexity to the implementation IIRC.

Be careful that this doesn't slow everything down.

**Comment by Qix-** [comment]
There's somewhat a reason for this; dim and bold have the same exit code and thus added some complexity to the implementation IIRC.

Be careful that this doesn't slow everything down.

**Comment by zerefwayne** [comment]
@sindresorhus Is the issue still open?

**Comment by sindresorhus** [comment]
⬇️ 

<img width="77" alt="Screenshot 2020-03-23 at 19 09 06" src="https://user-images.githubusercontent.com/170270/77310736-c68e4f00-6d39-11ea-9450-66d09a121f7d.png">

⬆️

**Comment by Qix-** [comment]
I think this should be closed. Across all the terminal emulators that exist, with all of the different IDEs and whatnot that also try to implement this (jetbrains software, vscode, etc.) I think trying to be clever about this stuff is only going to hurt performance and break more people.

Further, I've yet to come across a case where the extra few bytes were really detrimental to performance or even on-the-wire sizes (and where completely disabling styled output wasn't also an option).

Thoughts @sindresorhus?

**Comment by sindresorhus** [comment]
I agree. It's simply not worth the added complexity and risk of breakage.
