### ISSUE TITLE
Chalk v3 beta feedback

### ISSUE THREAD

**Issue by sindresorhus** [chalk/chalk#366]
This issue is for discussing the upcoming Chalk v3 version which is now in beta.

Beta 1: https://github.com/chalk/chalk/releases/tag/v3.0.0-beta.1

Let us know if you encounter any issues with upgrading or if anything is unclear in the release notes.

**Comment by Berkmann18** [comment]
It seems like it breaks @Qix-'s code on https://github.com/Berkmann18/nclr/pull/109#issuecomment-505652869.
I'm not familiar with the code and what changed since he posted the work-around so other than the `chalk.constructor.prototype` -> `chalk.Instance.prototype`, I'm unsure how to go about it.

**Comment by pbelbin** [comment]
Hey there.

I *believe* this is also a problem in 2.x.x code, but, I'm currently using the 3.0.0.beta.2, and 
I have found that with macOS 10.15, using Node.js 'child_process.spawn()` that the child process is determining that there is no color support, so things are looking pretty 'bland' as a result.

However, if I create a new chalk instance (as documented) with `const ctx = new chalk.Instance({level: 3})` then the result is very colorful (as expected).

It would be really good if the spawned child process would detect that color is available all by itself.

Keep up the good work!

**Comment by sindresorhus** [comment]
Chalk 3 final is now out: https://twitter.com/sindresorhus/status/1193065505780727808
