### ISSUE TITLE
Not working when I using the "bin" command to run my script.

### ISSUE THREAD

**Issue by Nick-Hopps** [chalk/chalk#371]
When I run the `index.js` directly, the `chalk.supportsColor` shows like `{ level: 3, hasBasic: true, has256: true, has16m: true }` and everything's fine. 

Because I want to use it as a normal command, I add

```json
"bin": {
    "rename": "index.js"
  },
```

in my `package.json` and run `npm link`. Now I can use `rename` directly but `chalk.supportsColor` returns `false`. Why is that and how to fix it?

**Comment by Nick-Hopps** [comment]
I have two files, `index.js` and `package.json`

in `index.js`, i just use chalk to output some console, and the code works fine.

and my `package.json` is 

```json
{
  "name": "@nickhopps/rename",
  "version": "2.0.0",
  "description": "A command-line util for renaming",
  "bin": {
    "rename": "index.js"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "NickHopps",
  "license": "MIT",
  "dependencies": {
    "chalk": "^2.4.2",
    "commander": "^2.20.3"
  },
  "private": true
}
```

when i run `index.js` directly, it is fine
![图片](https://user-images.githubusercontent.com/16911282/67009769-ea13f480-f11e-11e9-8c0d-86cb5b51847c.png)

and when i try to use `rename` which is defined in my `package.json` as above, it's not working
![图片](https://user-images.githubusercontent.com/16911282/67009878-2cd5cc80-f11f-11e9-97e4-fc12d405b91d.png)

**Comment by Qix-** [comment]
Yeab because `bin` is probably creating a stub script. Can you do `cat $(which rename)` and show the output?

**Comment by Nick-Hopps** [comment]
```bash
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/@nickhopps/rename/index.js" "$@"
  ret=$?
else
  node  "$basedir/node_modules/@nickhopps/rename/index.js" "$@"
  ret=$?
fi
exit $ret
```

**Comment by Nick-Hopps** [comment]
yes, it creates another script, how to make chalk work in such situation?

**Comment by Qix-** [comment]
In cygwin, there isn't a perfect way. You have to set `FORCE_COLOR=1` to get color output. This is a limitation in terminal emulators and scripting environments, not chalk.

**Comment by Qix-** [comment]
You can just set it as an environment variable. If you want to force colors in your program automatically, you have to set the Chalk level to 1 or above (see the readme). Otherwise, you need to `chmod +x index.js`, add `#!/usr/bin/env node` to the top of the script and `ln -s /usr/bin/rename $(pwd)/index.js` yourself manually.

**Comment by Qix-** [comment]
Glad it worked :)
