### ISSUE TITLE
gulp build fails with chalk version : 3.0.0

### ISSUE THREAD

**Issue by RichaJha1119** [chalk/chalk#374]
Hi,

Got the below issue after the chalk version updated from 2.4.2 to 3.0.0. The gulp build fails resulting in production build failure.

--- frontend-maven-plugin:1.0:gulp (gulp build) @ vcedpa ---
[INFO] Running 'gulp.js build' in /auto/builds/idpa/main/640037/vcedpa-war/../ui
[ERROR] /auto/builds/idpa/main/640037/ui/node_modules/run-sequence/node_modules/chalk/source/index.js:3
[ERROR] const {stdout: stdoutColor, stderr: stderrColor} = require('supports-color');
[ERROR]       ^
[ERROR] 
[ERROR] SyntaxError: Unexpected token {
[ERROR]     at exports.runInThisContext (vm.js:53:16)
[ERROR]     at Module._compile (module.js:373:25)
[ERROR]     at Object.Module._extensions..js (module.js:416:10)
[ERROR]     at Module.load (module.js:343:32)
[ERROR]     at Function.Module._load (module.js:300:12)
[ERROR]     at Module.require (module.js:353:17)
[ERROR]     at require (internal/module.js:12:17)
[ERROR]     at Object.<anonymous> (/auto/builds/idpa/main/640037/ui/node_modules/run-sequence/index.js:5:14)
[ERROR]     at Module._compile (module.js:409:26)
[ERROR]     at Object.Module._extensions..js (module.js:416:10)

Immediate answer will be much appreciated.

**Comment by sindresorhus** [comment]
This is not the place to ask unrelated build questions. It looks like you're on a too old Node.js version.

**Comment by TheRealKraytonian** [comment]
did you ever figure it out?

**Comment by TheRealKraytonian** [comment]
i need help with that two

**Comment by RichaJha1119** [comment]
Yeah.
I have made change in the dependency "run-sequence".I have updated the version from "1.2.2" to "2.2.1".

**Comment by RichaJha1119** [comment]
You can post your error here. I can help you out.
