### ISSUE TITLE
Windows: chalk.magenta() doesn't work in Powershell

### ISSUE THREAD

**Issue by ot-tony-archer** [chalk/chalk#377]
Much to my surprise, the chalk.magenta() function yields invisible text in a Powershell console!  I discovered this when my poor Windows-using friend installed my CLI and it yielded odd missing text

**Comment by Qix-** [comment]
Nothing we can do about that (though I've never heard of this being the case). Might want to open a ticket with [the WSL group](https://github.com/microsoft/WSL).

Sorry 😞
