### ISSUE TITLE
Thanks for Chalk 3.0.0! Here are a couple workaround for people upgrading:

### ISSUE THREAD

**Issue by mceachen** [chalk/chalk#378]
For your TypeScript users that are upgrading to v3.0.0, they'll see error `TS1259: Module X can only be default-imported using the 'esModuleInterop' flag`. They'll need to change their import line from
 
```ts
import chalk from "chalk"
```

to

```ts
import * as chalk from "chalk"
```

Also, I saw the PR that dropped the `enabled` field and replaced it with setting `level` to 0 (for disabled) or >0 (for enabled). With TypeScript 3.7.2 and Chalk 3.0.0, that field is marked readonly (even though [the type seems correct to me](https://github.com/chalk/chalk/blob/master/index.d.ts#L166)) and results in `error TS2540: Cannot assign to 'level' because it is a read-only property` if you try to set it. 

A workaround for now is to use a chalk instance.

**Comment by sindresorhus** [comment]
> For your TypeScript users that are upgrading to v3.0.0, they'll see error TS1259: Module X can only be default-imported using the 'esModuleInterop' flag.

I've updated the release notes to clarify this.

> With TypeScript 3.7.2 and Chalk 3.0.0, that field is marked readonly (even though the type seems correct to me ) and results in error TS2540: Cannot assign to 'level' because it is a read-only property if you try to set it.

Most likely a TS bug. I don't see anything wrong with our types. Try searching the TypeScript issue tracker for this issue.
