### ISSUE TITLE
Getting error when using chalk

### ISSUE THREAD

**Issue by Relms12345** [chalk/chalk#386]
So I am using chalk with Typescript. The thing is I can't seem to get it working.

I keep on getting `TypeError: chalk.bold is not a function` when using this line of code.
```ts
console.log(`Created new ${chalk.bold("document")} in ${chalk.bold.green("guildSettings")} for ${message.guild.name}!`)
```
I am using chalk version 3.0.0.

**Comment by Relms12345** [comment]
Update: When using version 2.4.2, it works fine for some reason

**Comment by sindresorhus** [comment]
You’re probably importing Chalk incorrectly.

**Comment by Qix-** [comment]
Yes, please show the import code you use for Chalk. Nothing we can do to help you otherwise.

**Comment by Relms12345** [comment]
i am using 
```js
import * as chalk from 'chalk'
```

**Comment by sylvainar** [comment]
```javascript
import chalk from 'chalk';
```
works fine

**Comment by Relms12345** [comment]
@sylvainar Yup I tried that and it works. Thanks

**Comment by Syaamilmaulana256** [comment]
can't use require()?

**Comment by Qix-** [comment]
No, and this has been covered quite a bit in issues. `require()` is no longer officially supported as of Chalk 5. You'll need to use imports.

Locking this since there's no additional conversation that could be had that changes this decision; it's 2025, there's nothing more to be said.
