### ISSUE TITLE
Failed to compile chalk/index.js

### ISSUE THREAD

**Issue by Odlir** [chalk/chalk#391]
Hi, im getting this issue with chalk since yesterday that i deleted node_modules folder and reinstalled it again, im using yarn and im getting this

```
Failed to compile.

./node_modules/chalk/index.js
Module not found: Can't resolve '/home/rgomez/odlirApp/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/createForOfIteratorHelper' in '/home/rgomez/odlirApp/node_modules/chalk'
```

any idea why this could be happening?

**Comment by Qix-** [comment]
Your babel configuration/installation is messed up. This has nothing to do with Chalk (other than that Chalk is using some Javascript features Babel chooses to transform).

Try re-installing node_modules or take the issue to the appropriate Babel support hubs.
