### ISSUE TITLE
chalk.blue() is displaying an orange color

### ISSUE THREAD

**Issue by dillionmegida** [chalk/chalk#395]
I did console.log(chalk.blue('hello')) in my NodeJS project and was surprised to see an orange-looking color logged to the console. Here's the image preview.

![chalk-issue](https://user-images.githubusercontent.com/42855542/79169480-7a887480-7de4-11ea-82cd-bfaa813a3268.png)

Thanks for considering this : )

**Comment by sindresorhus** [comment]
The named colors depend on your terminal theme. Your terminal theme seems to use orange for the blue color.
