### ISSUE TITLE
Support object

### ISSUE THREAD

**Issue by Johannesklint** [chalk/chalk#397]
Chalk doesn't today support passing in an object as an argument

```jsx
console.log(chalk.yellow.bold({ hello: 'hello' }));
// output: [object Object]
```

It would be nice to see a proper output like so:
```jsx
console.log(chalk.yellow.bold({ hello: 'hello' }));
// output: { hello: 'hello' }
```

**Comment by sindresorhus** [comment]
That’s outside the scope of Chalk. You can use `util.inspect` for that.
