### ISSUE TITLE
3.0.0 Release notes seems to be incorrect

### ISSUE THREAD

**Issue by ArchangelX360** [chalk/chalk#399]
In https://github.com/chalk/chalk/releases/tag/v3.0.0 section "Minor breaking", it is mentioned that, when using `esModuleInterop` TS compiler option, we should use:
- `import * as chalk from 'chalk';`
instead of 
- `import chalk from 'chalk';`

It seems to be incorrect, I have:
- error `chalk.red is not a function` trying with `import * as chalk from 'chalk';`+ `esModuleInterop: true`
- no error with `import chalk from 'chalk';` + `esModuleInterop: true`

Am I missing something?

**Comment by sindresorhus** [comment]
This was actually changed because of https://github.com/chalk/chalk/issues/378. I'm just gonna remove that part from the release notes.
