### ISSUE TITLE
.visible() text isn't visible when piped

### ISSUE THREAD

**Issue by alxndrsn** [chalk/chalk#401]
Chalk version: 4.0.0
Node version: 10.16.0
Bash version: 4.4.20

-----

# Observed

When text is run through `chalk.visible()`, it is *not visible* when output is redirected.

With this test script, `print-test.js`:

```
const chalk = require('chalk');

const HI = 'Hello, World!';

console.log('Normal string:', HI);
console.log('With chalk.visible:', chalk.visible(HI));
console.log('With chalk.green:', chalk.green(HI));
```

When run directly in the terminal:
![Screenshot_2020-05-18_09-41-20](https://user-images.githubusercontent.com/191496/82181774-d1a1cd80-98eb-11ea-8e71-b347a917027e.png)

This is as expected.

When this is piped through `grep`:
![Screenshot_2020-05-18_09-42-45](https://user-images.githubusercontent.com/191496/82181835-f433e680-98eb-11ea-808f-a8961c5bd8cf.png)

To double check, here is the same output hilighted - there is no invisible text:
![Screenshot_2020-05-18_09-46-16](https://user-images.githubusercontent.com/191496/82182154-791f0000-98ec-11ea-914c-066ba191c40c.png)

Redirecting the output to a file has the same effect:
![Screenshot_2020-05-18_09-46-26](https://user-images.githubusercontent.com/191496/82182166-7d4b1d80-98ec-11ea-824e-e56a6e2c2dfa.png)

# Expected

I would expect either:

1. a string returned from `chalk.visible()` to be printed exactly the same as a string which hadn't been wrapped with `chalk.visible()`, or
2. a string returned from `chalk.green()` would not be printed if the string returned from `chalk.visible()` were not printed.

I suspect I have misunderstood the point of `.visible()` though.

**Comment by alxndrsn** [comment]
I guess this is a misunderstanding on my part on what `visible()` is meant to do.  It definitely isn't the opposite of `hidden()`:
```
$ node print-test.js > output; cat output
Normal string: Hello, World!
With chalk.visible: 
With chalk.hidden: Hello, World!
With chalk.green: Hello, World!
```

:slightly_smiling_face:

**Comment by alxndrsn** [comment]
I've just tested this in a terminal with colours disabled (started with `xterm -cm`), and get the following:
![Screenshot_2020-05-18_10-20-48](https://user-images.githubusercontent.com/191496/82185074-53482a00-98f1-11ea-85fa-81960658f0c8.png)

So I guess this is working to spec, but I wonder if calling this out in the docs would be helpful.

**Comment by Qix-** [comment]
> Prints the text only when Chalk has a color level > 0. Can be useful for things that are purely cosmetic.

I don't think there's any better way of explaining this, honestly. It's just a matter of reading the Readme. Thanks for the suggestion, however :)
