### ISSUE TITLE
TypeError: Cannot read property '0' of undefined when using bright colours in "chalk.keyword()"

### ISSUE THREAD

**Issue by pubmikeb** [chalk/chalk#402]
Chalk 4.0.0

I'm trying to set a theme for info-messages:
```js
const info = chalk.keyword("blueBright");
```
But when I execute the code I get:
> UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.keyword (\node_modules\chalk\node_modules\ansi-styles\index.js:15:39)
    at Chalk.<anonymous> (\node_modules\chalk\source\index.js:83:77)

At the same time, when I use `blueBright` colour without theme:
```js
console.log(chalk.blueBright("info"));
```
everything is working OK.

I tried several bright colours from a [list](https://www.npmjs.com/package/chalk#colors), none of them is working inside of `chalk.keyword()`.

**Comment by Qix-** [comment]
`.keyword()` accepts CSS keyword names. The list you refer to are methods. Your second example is correct; the method names don't work with the keyword function.
