### ISSUE TITLE
.hex color with level 3 and hexa not colored properly

### ISSUE THREAD

**Issue by C0ZEN** [chalk/chalk#403]
I use chalk `4.0.0` in [this open source repository](https://github.com/Sonia-corporation/il-est-midi-discord).

When running the local server with `npm run start` inside the Windows 10 default terminal through WebStorm, the chalk level given by [supports-color](https://github.com/chalk/supports-color) is 3.
I did not overrided it (using `new chalk.Instance()`).
Using chalk directly from the import gives the same result.
3 is indicated as "Truecolor 16 million colors support" which then covers the 16,777,216 hexadecimal existing.
Yet, using most colors do not works as if the real level is 1 and the fallback to the 16 colors is enabled (or maybe the ANSI ones).
But even that seems strange because for example the `#F7D794` color is display as white (which seems from my eyes more close to yellow but anyway my eyes are pretty fucked up).
Using for example `#778BEB` is display as blue but I am not sure that this is the real decimal display or the fallback for the blue.

As a side note, the problem is also visible through Cmder for example but slightly different.
The level is still 3 but the colors are not the same.
The `#F7D794` color is no longer white but more like a deep-pink.

**Code example:**

```typescript
import chalk from "chalk";

const CHALK_INSTANCE: chalk.Chalk = new chalk.Instance();

console.log(CHALK_INSTANCE.hex(`#F7D794`)(`Hello Chalk`));
```

Is this an issue with my configuration, with chalk or with supports-color?
Thank you!

**Comment by sindresorhus** [comment]
You can check what color level is being used in with `console.log(chalk.level);`.

Try with the https://github.com/microsoft/terminal. If it works correctly there, the problem is most likely with your setup.

**Comment by C0ZEN** [comment]
@sindresorhus thank you for the response.
Indeed this is working fine with [microsoft/terminal](https://github.com/microsoft/terminal).
However I do not understand then how could it be a problem with my setup.
This is the same project and the only difference here is that the problem is within the default Windows terminal (which also indicate that the level is 3).

**Comment by sindresorhus** [comment]
Most likely it's the WebStorm terminal providing the wrong information so the detection done by https://github.com/chalk/supports-color is incorrect.

**Comment by C0ZEN** [comment]
@sindresorhus ok thank you. I will reach WebStorm about this issue.

**Comment by C0ZEN** [comment]
See the WebStorm issue I opened.
https://youtrack.jetbrains.com/issue/WEB-47143
