### ISSUE TITLE
Typescript ambient definitions doesnt work in node unless

### ISSUE THREAD

**Issue by alesmenzel** [chalk/chalk#404]
unless you require it as an "ecmascript module"

```js
const { default: chalk } = require('chalk') // this will work and typescript is happy
```

The following provides incorrect types:

```js
const chalk = require('chalk') // this work but typescript will shows errors with incorrect types
```

Would it be possible to fix the `index.d.ts` so it provides correct types for commonjs (node) environment?

**Comment by papb** [comment]
Have you tried `import chalk from 'chalk'`?

**Comment by alesmenzel** [comment]
I cannot use import/export in NodeJS. That syntax is supported only in later version of node.

**Comment by Qix-** [comment]
Either you're using Typescript and their `import` semantics or you're using Node.js and its CommonJS `require()` semantics. Both are supported by Chalk.

**Comment by papb** [comment]
@alesmenzel Oops, sorry about that, for some reason I thought you were using TypeScript.

**Comment by alesmenzel** [comment]
> Either you're using Typescript and their `import` semantics or you're using Node.js and its CommonJS `require()` semantics. Both are supported by Chalk.

I am using plain node v12 but have Typescript intellisense running on those ja files. And it is showing an error on chalk. I can workaround this by using the "default" key in the commonjs require. I believe this is a bug in Chalk's type definitions.

**Comment by papb** [comment]
Unable to reproduce...

![image](https://user-images.githubusercontent.com/20914054/83343777-33433e00-a2d5-11ea-9f9f-10256a5ed924.png)

Can you be more specific in what's wrong?

**Comment by Qix-** [comment]
> I am using plain node v12 but have Typescript intellisense running on those js files. 

This doesn't make much sense to be honest. JS is too dynamic to have great intellisense. I didn't even know IDEs would cross the typescript/javascript boundary when doing code hinting.

Sounds like an issue specifically with your IDE as our typings haven't caused any issues before.

**Comment by alesmenzel** [comment]
You were right, sorry for bothering. It was a misconfiguration in my project... Again, I am sorry and thanks for all answers. Still it is weird it was working with the `const {default: chalk} = require('chalk')` import.
