### ISSUE TITLE
Question: change background for a complete terminal line

### ISSUE THREAD

**Issue by StfBauer** [chalk/chalk#407]
When I console.log a text like this:

```javascript
console.log(chalk.bgWhite.black('hello world'));
```

It creates the following output:
<img width="368" alt="Screenshot 2020-06-16 at 09 35 25" src="https://user-images.githubusercontent.com/5503835/84745367-be4e5480-afb4-11ea-81f0-5b8e28bd7752.png">

Is there any way that I can format the while line other than just then encapsulated words.

**Comment by Qix-** [comment]
Kind of a hack, but try this:

```javascript
const padConsoleWidth = (s, stream = process.stdout) => s + ' '.repeat(stream.columns - s.length);
console.log(chalk.bgWhite.black(padConsoleWidth('Hello, World!')));
```

This won't work in all cases but should work in _most_ of them.

**Comment by StfBauer** [comment]
Thank you I will give it a try.

**Comment by Qix-** [comment]
Unfortunately not; some terminal emulators will color the rest of the line if you insert the newline before the render mode reset but that's inconsistent behavior at best.

This is the most "correct" way (keeping in mind that all ANSI escape/TTY stuff is horribly archaic).

Hope that helps :)

**Comment by StfBauer** [comment]
@Qix-  At least it gave me a new idea. Currently used chalk for syntax highlighting with PrismJS with console.log in NodeJS.
Some themes there have some strange colouring.
Details: https://t.co/1gyFTTVEm6?amp=1
