### ISSUE TITLE
Compatibility with Yarn 2

### ISSUE THREAD

**Issue by altrugon** [chalk/chalk#410]
Hi there,

Trying to use Chalk with Yarn 2 I ran into the following issue:

`Error: Your application tried to access chalk, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.`

Following Yarn 2 Troubleshooting documentation [A package is trying to access another package [...]](https://github.com/chalk/chalk/issues?q=is%3Aissue+yarn+2) I did apply the temporary solution as follow:

**.yarnrc.yml**

```
yarnPath: .yarn/releases/yarn-2.1.1.cjs
packageExtensions:
  "my-app@*":
    dependencies:
      "chalk": "*"
```

Then I run `yarn cache clean && yarn install` and the error disappeared. However the documentation recommends to  open a PR on the upstream repository, so here it is.

Thank you so much guys for the hard work.

**Comment by Qix-** [comment]
Do you have `chalk` in your application's dependencies?

**Comment by sindresorhus** [comment]
Use the Yarn support channels for Yarn support. Chalk installs fine with npm.

**Comment by altrugon** [comment]
@Qix- 🤦‍♂️ Sorry man, one of those long days. I previously had a webpack-cli throwing  the same problem, and I just went with the same fix. Fixed after running `yarn add -D chalk`.

Thanks for the quick reply.
