### ISSUE TITLE
Windows and Linux ANSI colors differ?

### ISSUE THREAD

**Issue by basickarl** [chalk/chalk#411]
Hi! Sorry if this is the wrong place but it was via Chalk I found this issue.

I ran the following code:

```
const chalk = require('chalk');

console.log('\[34mundefined\[39m');
console.log(chalk.blue(undefined));
```

Linux:
![color_chalk_linux](https://user-images.githubusercontent.com/10507098/89648629-d1e4b000-d8bf-11ea-8563-2d8c1ac02fc3.png)
Windows:
![color_chalk_windows](https://user-images.githubusercontent.com/10507098/89648636-d27d4680-d8bf-11ea-91e6-50fdd32d63be.png)

It appears chalk uses different ANSI codes for blue depending on if it's Linux or Windows? As you can see the Windows colors differ, but not the Linux ones.

**Comment by Qix-** [comment]
Hi - which version of chalk? We used to change the blue to blueBright on windows because cmd.exe's default blue was nearly unreadable against the black background. It appears the latest version does not have this "fix" anymore, so updating might resolve the issue for you.
