### ISSUE TITLE
(v2) mutates ansi-style exports

### ISSUE THREAD

**Issue by kumavis** [chalk/chalk#412]
version 2.x mutates exports on `ansi-styles`

I'm working on [LavaMoat](https://github.com/lavamoat/lavamoat), a set of tooling to help prevent software supplychain attacks and protect the javascript commons

part of the protections LavaMoat provides involve identifying and preventing mutations to a module's exports across package boundaries. Can you help me understand why this mutation is done? is it a "monkey-patch" of the dependency? or an intentional feature?

v2 is still widely used, here is a random example from a small project
```
=> Found "chalk@2.4.2"
info Has been hoisted to "chalk"
info Reasons this module exists
   - Hoisted from "patch-package#chalk"
   - Hoisted from "concurrently#chalk"
   - Hoisted from "standard#eslint#chalk"
   - Hoisted from "standard#eslint#@babel#code-frame#@babel#highlight#chalk"
   - Hoisted from "allow-scripts#libnpm#lock-verify#@iarna#cli#update-notifier#chalk"
   - Hoisted from "allow-scripts#libnpm#lock-verify#@iarna#cli#update-notifier#boxen#chalk"
```

thanks for your time and attention/

**Comment by kumavis** [comment]
mutations happen in a few different places but this is one example https://github.com/chalk/chalk/blob/9776a2ae5b5b1712ccf16416b55f47e575a81fb9/index.js#L56

**Comment by sindresorhus** [comment]
I think the mutation was just accidental as we didn't consider that the `ansi-styles` package returned a shared object reference instead of a new object on each import. It's not feasible to get this fixed in v2, unfortunately.
