### ISSUE TITLE
feature-request: Removing styles from text / getting the length of unstyled text

### ISSUE THREAD

**Issue by geoffreyTools** [chalk/chalk#413]
I sometimes need to get the length of a string for layout reasons (typically centering text, wrapping lines, adding thematic breaks).

When mixed chalk styles are applied to a string, getting the original length is not exactly straightforward.

I didn't want to parse the thing, so I came up with this in order to maintain two strings and diff the lengths
```javascript
const [styled, unstyled] = magicFunction(
    [chalk.green, x => x, chalk.red],
    ['green text', ' white text', 'red text']
);
/* output [
  '\x1B[32mgreen\x1B[39m white \x1B[31mred\x1B[39m',
  'green white red'
] */
```
It is not ideal but I think that time should not be spent improving this solution on the user end. 
Maybe chalk should solve this problem?

**Comment by sindresorhus** [comment]
You could use https://github.com/chalk/strip-ansi and then measure.

https://github.com/sindresorhus/string-length

**Comment by geoffreyTools** [comment]
Oh! Perfect!
