### ISSUE TITLE
The 'hidden' modifier is not hiding the text

### ISSUE THREAD

**Issue by kretschmannj** [chalk/chalk#418]
I'm trying to use the 'hidden' modifier but the text is still displaying in the console output ...

`console.log(chalk.hidden('Hello world!'))`

Running NodeJS in Visual Studio Code.

**Comment by sindresorhus** [comment]
Do you get any color if you do `chalk.red`? If not, the problem is not with Chalk, but rather VSCode not being TTY.

**Comment by kretschmannj** [comment]
yes, chalk.red will return red text.  It just seems that 'hidden' doesn't work.

**Comment by sindresorhus** [comment]
Then I would open an issue on VSCode. They probably just don't support the "hidden" ANSI escape in their terminal.

**Comment by Qix-** [comment]
FWIW hidden isn't really recommended to be used anymore. It's not "secret" and definitely not secure, so beyond any sort of usecase like that, it's probably best just not to use it. There is a reason why most emulators don't (correctly, or at all) support it - there's not a lot of practical use for it.

**Comment by papb** [comment]
I can see that being used to trick users to select text in the terminal and copy-paste perhaps unexpectedly bringing together a malicious payload...

**Comment by Qix-** [comment]
Not sure how often that's happened but yes, that's the kind of mindset that's important :)
