### ISSUE TITLE
Build issue for Nest.js in production

### ISSUE THREAD

**Issue by Manasav1510** [chalk/chalk#422]
I am facing the below issue in production whiel building nest.js app.

/app/node_modules/cli-highlight/node_modules/chalk/source/index.js:103

        ...styles,
        ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/cli-highlight/dist/theme.js:10:28)

chalk version from package.json
"cli-highlight": {
      "version": "2.1.4",
      "resolved": "https://registry.npmjs.org/cli-highlight/-/cli-highlight-2.1.4.tgz",
      "integrity": "sha512-s7Zofobm20qriqDoU9sXptQx0t2R9PEgac92mENNm7xaEe1hn71IIMsXMK+6encA6WRCWWxIGQbipr3q998tlQ==",
      "requires": {
        "chalk": "^3.0.0",
        "highlight.js": "^9.6.0",
        "mz": "^2.4.0",
        "parse5": "^5.1.1",
        "parse5-htmlparser2-tree-adapter": "^5.1.1",
        "yargs": "^15.0.0"
      }

node.js version - v12.14.1
npm version - 6.14.8
nest version - 7.5.1
typeorm - "version": "0.2.26"
 "cli-highlight": "^2.0.0"

I saw some similar issue raised .But couldn't come to a conclusion on which is better way to fix this issue.
Could you please help with this issue.

**Comment by sindresorhus** [comment]
That error happens when you're using an older Node.js version.

---

> node.js version - v12.14.1

This is not the Node.js version being used when the error happens.

---

Closing as this is not an issue with Chalk.
