### ISSUE TITLE
Support browser and online demo

### ISSUE THREAD

**Issue by jcubic** [chalk/chalk#424]
I was able to make browser version of the chalk. Using browserify and npm link with force of supports-color package. If you're interested in updating the docs and that this is possible I can write something maybe tutorial or update README or other docs.

I know that chalk is suppose to be terminal node based library, but it can be used in browser, example is my jQuery Terminal that support ANSI escape codes. If you're interested I can create a demo how those two libraries work together.

Nice thing about my library is that you can showcase your library with **online demo**. I can create demo like that if you want (demo that will be nice example for my library).

Here is example demo I've created for ervy (node based library that renders Charts) https://www.chunqiuyiyu.com/ervy/ I can create something similar, or if you want something different let me know, but I  would like to use terminal. I can write JavaScript interpreter with chalk loaded so users will be able to use directly your API.

**Comment by jcubic** [comment]
Here is example how this would look like: https://codepen.io/jcubic/full/VwKrbzJ I can add option of tab completion for chalk methods so it will be easier to type.

**Comment by Qix-** [comment]
There's nothing that really prohibits the use in the browser. It's just not written for it. There are many non-terminal projects successfully using Chalk in web-like environments. All we do is generate strings with special escapes in them, and supports-color can be reasonably spoofed in cases where it's necessary.

As it stands I don't think there's anything actionable here, but thank you :)

**Comment by jcubic** [comment]
Can you name the web project like that? I was told the other day that there is no way for supports-colors to work in the browser because it's terminal based, when I was trying to play with it in the browser. Here is example that is not true, that's why I've created this issue.

**Comment by Qix-** [comment]
That's why I said "supports-color can be spoofed". You can replace the calls to supports-color if you want.

**Comment by jcubic** [comment]
Too bad my first reply was "go away" + close, instead of pointing that you can spoof the package with npm and use it in browser,
I may use this project earlier, instead of abandoning it as of no use to me.

**Comment by Qix-** [comment]
I didn't say "go away", but that there isn't really anything for us to do here with this issue. I apologize if I upset you.
