### ISSUE TITLE
Would like colour Type exported for integrating with typescript

### ISSUE THREAD

**Issue by inspiraller** [chalk/chalk#425]
Currently I have to copy the colours from chalk node_modules folder:
```
ForegroundColor =
	| 'black'
	| 'red'
	| 'green'
	| 'yellow'
	| 'blue'
	| 'magenta'
	| 'cyan'
	| 'white'
	| 'gray'
	| 'grey'
	| 'blackBright'
	| 'redBright'
	| 'greenBright'
	| 'yellowBright'
	| 'blueBright'
	| 'magentaBright'
	| 'cyanBright'
	| 'whiteBright';

```

I would like to import them to save duplication and out of sync colours.
Same with background colours, modifiers etc...

**Comment by sindresorhus** [comment]
They are already exposed. See the type tests.

**Comment by lazarljubenovic** [comment]
Indeed, they're exported both as `ForegroundColor`, `BackgroundColor` and `Color` which is all of it together.
