### ISSUE TITLE
Please support objects

### ISSUE THREAD

**Issue by johannb75** [chalk/chalk#427]
I've just discovered chalk. I was using colors before
But it seems that you don't support objects:
```js
console.log(chalk.green('hi! your infos are:', {
  name: "John",
  surname: "Doe",
  age: 26
}));
```
This outputs:
> hi! your infos are: [object Object]

I really don't have any idea on how you could implement this.
I don't seem to be the only one having this problem: [#397](https://github.com/chalk/chalk/issues/397)
I don't think that’s outside the scope of Chalk because colors supports it.

**Comment by Qix-** [comment]
Node has something built in for this, maybe it'll interest you:

```javascript
const {inspect} = require ('util');
console.log(inspect(obj, {colors: true}));
```

**Comment by sindresorhus** [comment]
No plans to add this. You can use `until.inspect`.

**Comment by sahilrajput03** [comment]
Try using it like this:

```js
let logger = {
	success: (...args) => printer(args, chalk.bgGreen.yellow.bold),
}
// all below cases should work good now: 
 logger.success('my object', {car: 10})
 logger.success('my array', ['bar', 20])
 logger.success('my string', 'foo is bar')

const printer = (args, chalkify) => {
	if (args.length === 0) throw '::::::error::::: no argument supplied to logger'
	args.forEach((element) => {
		if (typeof element === 'object') {
			const {inspect} = require('util') // src: https://stackoverflow.com/a/6157569/10012446
			process.stdout.write(chalkify(inspect(element)))
		} else {
			process.stdout.write(chalkify(element))
		}
		process.stdout.write(' ')
	})
	process.stdout.write('\n') // print new line after printing each element in the log i.e., logger.success(elem1, elem2, elem3, ...)
}
```

**Output:**

![image](https://user-images.githubusercontent.com/31458531/174423263-a284049a-f1da-4892-bb18-29343a435b27.png)


I was worrying about this feature from a long time and I advice this would be great feature from chalkjs directly.
