### ISSUE TITLE
`escape()` has deparcated

### ISSUE THREAD

**Issue by raklaptudirm** [chalk/chalk#430]
`escape()` has deprecated in Javascript 1.5. Use `encodeURI()` or `encodeURIComponent()` instead.

**Comment by Qix-** [comment]
Where in the codebase are you referring to? I don't see anything called `escape`.

**Comment by raklaptudirm** [comment]
Sorry it is `unescape()`. at `template.js:

**Comment by Qix-** [comment]
We define that function and shadow the built-in, so there's nothing deprecated here.
