### ISSUE TITLE
Chalk v5

### ISSUE THREAD

**Issue by sindresorhus** [chalk/chalk#431]
- [x] ESM (https://github.com/chalk/chalk/commit/fa16f4ec37c1c25bda6ca1864bf53ecd3ea3d3c9)
- [x] Remove some color types, per https://github.com/chalk/ansi-styles/commit/9150f611ced8afc843741050dfb05f48aad1d0dc
- [x] Make `chalk.stderr` a named export instead? `import {chalkStderr} from 'chalk';`
- [x] Make `chalk.supportsColor` a named export instead? `import {supportsColor} from 'chalk';`.
- [x] Make `chalk.Instance` a named export instead? `import {Chalk} from 'chalk';`.
- [x] Move template functionality to [`chalk-template`](https://github.com/chalk/chalk-template).
- [x] Clean up the type definition. Improve the type names. Add more docs.

What else do we want to do for v5?

---

/// @Qix- @Richienb

**Comment by Richienb** [comment]
TypeScript rewrite would be nice

**Comment by Qix-** [comment]
This all sounds good to me. There isn't anything else pressing that I can think of.

I'm :-1: on the typescript rewrite. I don't see what benefits that would bring.

**Comment by Richienb** [comment]
All the benefits of rewriting in TypeScript are maintainer facing.

It allows us to automatically type check our code and generate typings for distribution.

**Comment by sindresorhus** [comment]
I don't think we want TypeScript for Chalk. Chalk is just doing too much weird stuff that is hard to type. It would also slightly bloat Chalk installation-wise.

**Comment by Richienb** [comment]
Would it make sense to use symbols instead of underscored properties?

https://github.com/chalk/chalk/blob/d798222a5a3ff208782ce81f5fbd3babb286b3e3/source/index.js#L149-L151

**Comment by sindresorhus** [comment]
Yes, I think that's a good idea.

But if you want to contribute more, "Remove some color types, per chalk/ansi-styles@9150f61" is a higher priority.

**Comment by fregante** [comment]
This? https://github.com/chalk/chalk/issues/300#issuecomment-730972576

**Comment by Qix-** [comment]
As much as it pains me to suggest this since it's my baby...

Perhaps we move the template code into `chalk-template` or something similar (if @smollweide would allow for that, since the existing package seems to have gone untouched for a while). While I still assert it's incredibly useful functionality, I haven't seen a lot of people use it and it would reduce install times and extra init costs even more.

It would still be an official chalk package until the `chalk` org but would otherwise be the same functionality, just separated.

Thoughts?

**Comment by sindresorhus** [comment]
@Qix- Yeah, let's do it. @smollweide was nice enough to give us the name. I have created a skeleton repo with the initial code, but someone still needs to make it runnable and add docs, and then remove it from Chalk.

https://github.com/chalk/chalk-template

**Comment by Qix-** [comment]
Thank you very much @smollweide <3

**Comment by smollweide** [comment]
You are welcome. Thank you for your work on this Project 🙏

**Comment by canonic-epicure** [comment]
Just curious what is the reason for removal of the keyword support and other color schemas?

**Comment by Richienb** [comment]
> Everything else is just bloat that very few use. Each added color space adds mental overhead for the user, noisy auto-complete, etc.

https://github.com/chalk/chalk/issues/360#issuecomment-525253344

**Comment by canonic-epicure** [comment]
I see. I was a happy user of the "keyword" color space :)

**Comment by Qix-** [comment]
Yeah I used keywords from time to time as well. There's been a large effort to reduce Chalk's code size and footprint since it's so commonly used.

The new way is to use color convert directly. If it were me, I'd abuse some template literals to do my bidding.

```javascript
const colorConvert = require('color-convert');
const chalk = require('chalk');

const K = name => colorConvert.keyword.rgb(name[0]);

console.log(chalk.rgb(K`lightseagreen`)('Hello!'));
```

![image](https://user-images.githubusercontent.com/885648/115735057-75acb800-a38a-11eb-8871-9b9454d22dc4.png)

**Comment by canonic-epicure** [comment]
I see.. Thanks for the explanations, just a user's nitpick, as usual - "What?? **I**'ll have to change **my** code??" 

As a developer I of course understand that you want to keep the codebase lean. Worth adding a note about the new, `color-convert` way of doing things to the docs I guess.

**Comment by Qix-** [comment]
@canonic-epicure you can certainly stay on the major release you're using, you're not obligated to upgrade if there's a large overhead. Chalk isn't known for introducing security regressions and the like, so unless you care about the smaller footprint and aren't affected by the dropped models, then you can choose not to upgrade.

There isn't much in the way of innovation from Chalk between major releases like a lot of packages have - a lot of it is updating code to match the current "industry standards" (e.g. pure ESM vs. CJS) or reducing footprint as a response to how we determine people use chalk (e.g. removing under-utilized conversion methods, or moving the template parser into its own module).

**Comment by canonic-epicure** [comment]
@Qix- I see. 

Btw, just FYI, I made a quick&dirty port of the current state in master branch to Deno: https://deno.land/x/chalk_deno@v4.1.1-deno
(I need a coloring for my app and built-in Deno colorizer does not seem to handle the multiline strings)

**Comment by Richienb** [comment]
What sort of changes were needed to be made to support Deno? If there are minute, they could be applied to `chalk` itself.

**Comment by canonic-epicure** [comment]
You can see the full list of changes [here](https://github.com/chalk/chalk/compare/main...canonic-epicure:main)

I've "inlined" the dependencies (included their sources directly in "chalk") and translated Node.js idioms to Deno's (like, `process.argv.slice(2)` -> `Deno.args`, `process.env` -> `Deno.env.toObject()`

In theory should be possible to have a single code base for node/deno - would need to have a dynamic environment check in every such place. Would need to get rid of the import from Deno std in such case though: https://github.com/chalk/chalk/compare/main...canonic-epicure:main#diff-1e2e3faa47d2dcd5f218c97e6a93eb79d9d4fc301601f5698eed372e40b04e4eR3

Also could not find a Deno equivalent of `os.release`, just commented: https://github.com/chalk/chalk/compare/main...canonic-epicure:main#diff-1e2e3faa47d2dcd5f218c97e6a93eb79d9d4fc301601f5698eed372e40b04e4eR81

**Comment by rayfoss** [comment]
Please switch to spaces Read Me is full of __tabs__.

Ps if you get the following error, you're on the NPM version using main branch instructions
'only refers to a type, but is being used as a value here'

Use this instead.
```
import Chalk from 'chalk'
const chalk = new Chalk.Instance({ level: 2 })
```

Versioning right now is a bit confusing... npm has 4.1.1, but gitlab's main is 4.1.0

**Comment by Qix-** [comment]
> Please switch to spaces Read Me is full of tabs.

We prefer tabs.

> Also, console on chrome looks nothing like you would expect...

That's a chrome issue, please file with them. We work primarily with ANSI escapes; chrome just happens to support them, but how they are rendered is not up to us.

> Ps if you get the following error . . .

If you think there's a bug, please file a ticket. I'm not sure what you're asking here.

> gitlab's main is 4.1.0

We don't maintain Gitlab repositories to my knowledge (@sindresorhus?). Whatever you're seeing isn't maintained by us.

**Comment by Qix-** [comment]
> Didn't think in the Typescript/Javascript/Node.js community Tabs were a thing anymore

Sindre had 33% of the total NPM downloads and most (all?) of his modules use XO, which has dictated tabs since its inception. Not sure where code style was generally agreed upon but I guarantee you it's not.

> Converting ANSI color to DevTools Console compatible argument CSS pairs turns out to be a little tricky

Yes, that's why this library doesn't do it. Like I said before, Chrome doing it is entirely of their own volition.

**Comment by cwistedt** [comment]
I dont know if this is the right place to leave this info but anyway:

The use of:
process.env.TERM 
process.platform

I think is not valid in Webpack5 which Angular12 uses to build. For my project the tests failed because of that. 

Created this issue in jasmine-test-cases lib that i use for testing which use chalk and that breaks testing Angular12.

https://github.com/tonto7973/jasmine-test-cases/issues/15

**Comment by Richienb** [comment]
The `process` global is not available in the browser and is no longer polyfilled as of Webpack 5: https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

If you are able to add custom webpack config, try adding [`node-polyfill-webpack-plugin`](https://github.com/Richienb/node-polyfill-webpack-plugin#readme) to get it back.

**Comment by Richienb** [comment]
@sindresorhus What's the metric for cleaning up the type definition? Are there specific things that need to be done?

**Comment by sindresorhus** [comment]
I don't remember what I was thinking of. I guess we are good on that point, unless you can see any ways to improve them.

**Comment by Richienb** [comment]
I think the last thing to do it move the types for `ColorSupportLevel` into https://github.com/chalk/supports-color and import them from there.

**Comment by sindresorhus** [comment]
Yes, that would be a good improvement.

**Comment by Richienb** [comment]
@sindresorhus Chalk should be ready for release now.

https://github.com/chalk/chalk/issues/519 Seems to have been fixed in a meta tweak that has happened since the issue was opened and https://github.com/chalk/chalk/issues/513 is just a mixup of documentation.

**Comment by sindresorhus** [comment]
It's now out: https://github.com/chalk/chalk/releases/tag/v5.0.0

Please let me know if I missed anything in the release notes.

**Comment by shellscape** [comment]
_very_ late to the party here, because I've been using the older CJS version for a very long time, but I'm curious what the reasons were for moving the template support into a new package. I've searched and can't find much discussion about why it was done. I've been using the template approach pretty much exclusively since the early days, so I'm surprised to see that it's considered not widely used.

**Comment by Richienb** [comment]
@shellscape [While it's incredibly useful, it is not often used, and removing it would reduce install time and init cost.](https://github.com/chalk/chalk/issues/431#issuecomment-824062669)

**Comment by shellscape** [comment]
@Richienb thanks, but that doesn't really add to what's already here, and my followup above.

**Comment by Richienb** [comment]
@shellscape Sorry that there isn't anything else to add, but I hope that it was useful to hear some confirmation on reasons why.

**Comment by shellscape** [comment]
No disrespect intended; it's wasn't particularly useful, because I had already read the reply you linked to in this issue. It does reinforce my observation that there isn't much discussion elsewhere to explain or justify the separation. Again, not being snarky or disrespectful.

**Comment by Qix-** [comment]
We had a concerted effort a while back to reduce Chalk's size as the vast majority of people use the basic colors and not much else.

My `color-convert` package was quite large in comparison, for example. We cut it out and moved the most relevant functions directly into chalk.

Same thing with the other auxiliary functions (re-exports of e.g  the ANSI regex module, etc). Existing users of chalk saw a reduction in install times and bundle sizes across the board as a result.

Glad to see people using the template system though, I poured some soul into that :) Hopefully the change isn't too much of a burden!

**Comment by shellscape** [comment]
Thanks for the additional info. Were there metrics on use of the template literal function? If there were I'm authentically curious about how those were collected from a technical standpoint.

**Comment by Qix-** [comment]
No there weren't, we just cut out everything that wasn't very core to the library.
