### ISSUE TITLE
No matching version found for chalk@4.1.1

### ISSUE THREAD

**Issue by JotSinghChawla** [chalk/chalk#435]
I was installing a react-router-dom package And it shows an error stating 
`No matching version found for chalk@4.1.1 in react router dom`

**Comment by Qix-** [comment]
It was published an hour ago, my knee-jerk reaction would be caching.

Could you expand on the error itself? Not a lot of information to go off of.

**Comment by sindresorhus** [comment]
This is not the place to ask for npm support: https://www.npmjs.com/support

**Comment by JotSinghChawla** [comment]
I was just installing react router dom package in my New React Project and it was the first thing I installed. So idk why I am getting this error. Also I check the chalk version with npm view chalk. And it show latest version is 4.1.0

**Comment by Qix-** [comment]
Yep, this is a problem with npm - please contact them. https://npmjs.org/package/chalk shows, correctly, `4.1.1` being the latest released.
