### ISSUE TITLE
Disable colors when when node launched as Upstart daemon

### ISSUE THREAD

**Issue by mahnunchik** [chalk/chalk#48]
Chalk uses colors when node launched as Upstart daemon http://upstart.ubuntu.com/cookbook/#console-log

**Comment by mderazon** [comment]
Is this currently disabled for upstart ?

What's the reason it should be disabled for upstart?
I use upstart and pipe the logs to an external service ([papertrail](papertrailapp.com/)), would love to see colors there as well

**Comment by sindresorhus** [comment]
@mderazon Please follow the issue trail: https://github.com/sindresorhus/supports-color/issues/14
