### ISSUE TITLE
project won't start due to error on line 106 in source/index.js

### ISSUE THREAD

**Issue by jayKeegan** [chalk/chalk#495]
Error: `/var/www/website-backend/node_modules/chalk/source/index.js:106
        ...styles,
        ^^^
SyntaxError: Unexpected token ...`
FYI I am using strapi if that makes debugging any easier.

**Comment by sindresorhus** [comment]
The JS engine/parser you're using doesn't support the syntax. This has nothing to do with Chalk. Open an issue on Strapi instead.
