### ISSUE TITLE
Colors disappeared when used with xtermjs and nginx as reverse proxy

### ISSUE THREAD

**Issue by anatoly314** [chalk/chalk#496]
I use this library (thank you for it) with xtermjs. When I run it locally it works fine, when I run it in the cloud (NodeJS app <=> Nginx configured as reverse proxy <=> browser connected by using socket.io) the colors codes disappearing. I think that they are "eaten" by Nginx. Maybe someone has the same configuration (I don't think it's unique) and can share it with me? 

A more detailed explanation posted here: https://stackoverflow.com/questions/68262540/nginx-removes-ansi-escape-codes-when-used-as-reverse-proxy

Thank you!

**Comment by Qix-** [comment]
Why would nginx be receiving chalk output? I'm confused as to how you're using chalk.

**Comment by anatoly314** [comment]
@Qix- , I made a detailed explanation in the attached link. 
But in general, I have an Xtermjs client which connected to my server. My server is Nginx configured to be a reverse proxy for my Nodejs app where strings are encoded by using chalk.js. When I run locally, i.e. browser connected directly to Nodejs app, everything is working. When I run it in the cloud, i.e. there's Nginx between browser and Nodejs app it stopped working.

**Comment by Qix-** [comment]
Hey, we get this question a lot - so much so that I created [a wiki page](https://github.com/chalk/chalk/wiki/Where-did-my-colored-output-go%3F) with the answer; hopefully it helps.

However this doesn't appear to be a problem with Chalk, so I'm going to close this for now.
