### ISSUE TITLE
Found extraneous } in Chalk template literal should not swallow message

### ISSUE THREAD

**Issue by fyyyyy** [chalk/chalk#498]
We're using chalk to format error messages in our logger.
`formatted = template(chalk, message);`
However error messages can be complex and it so happens that chalk is throwing _"Found extraneous } in Chalk template literal"_ if the error i.e. contains json.

Chalk should not swallow the user message when throwing the error, we suggest adding
`console.log(temporary)` before throwing the error.
https://github.com/chalk/chalk/blob/b68c8b5102f04fb80bfdf83319d143aedff68bcb/source/templates.js#L114

**Comment by fyyyyy** [comment]
Our current workaround is to move
`template(chalk, message);`
in a try catch block

**Comment by sindresorhus** [comment]
We could make the error include more context, sure. But I think you're trying to fix this in the wrong place. If you use Chalk template for logging, you should ensure to escape the input if you're not using interpolation (which does the escaping for you).

---

> we suggest adding
console.log(temporary) before throwing the error.

Reusable packages should not output logging with `console.log`.

**Comment by fyyyyy** [comment]
Ok thanks escaping makes sense

**Comment by Qix-** [comment]
Super confused, how are you using templates anyway? this error should not happen If you're using interpolation...

**Comment by fyyyyy** [comment]
We're using chalk to log JS errors in a cli

**Comment by Qix-** [comment]
Yes I figured. I mean can you show an example of code that uses templates?

**Comment by fyyyyy** [comment]
// App.ts
try {
something
} catch (e) {
   logger.error(e)
}


// Logger.ts
error(message) {
   template(chalk, message);
}

**Comment by Qix-** [comment]
That's not how you should be using the templates; it's certainly not supported.

```javascript
console.log(chalk`{red This} {bold {green is.}}`)
```

![image](https://user-images.githubusercontent.com/885648/125160826-623a0d80-e17f-11eb-892e-78fb2fee9d5b.png)

**Comment by fyyyyy** [comment]
ok thanks for clarifying
