### ISSUE TITLE
Missing `types` field in package.json

### ISSUE THREAD

**Issue by dagerikhl** [chalk/chalk#500]
Hello! Great work on this library, I love using it.

I've come across a bug that prevents type completion for the library, at least in my IntelliJ editor.

The library now serves its own `index.d.ts` typings file, which is superb, but it's not pointed to in package.json, which prevents editors (and possibly TS itself, unsure about that) from recognizing that those are the types for chalk.

The issue may be limited to IntelliJ, but I suspect the `types` attribute in package.json should be specified for any library shipping its own types.

# To reproduce

1. Install chalk in a clean and simple node JS project.
2. Try to write e.g.:
  ```
  const chalk = require("chalk");
  chalk.blue("I am blue, and if I was green I would die");
  ```

# Expected behaviour

1. `chalk.blue` (and all other colors, converters, etc.) are autocompleted and possible to navigate to typings for.

# Actual behaviour

- `chalk` only presents three possible members: `.template, .stderr, .supportsColor` (in addition to the standard function members).

What seems to happen is that the types are resolved by the `main` field in package.json instead, and the types exported there are not parsable in full. Ref. resolution order described here: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html#editing-the-packagejson

# Findings

Ref. the resolution order above (`types` field > `main` field > index.d.ts in root), the `main` takes precedence and source/index.ts is chosen as the types root.

### Remove `main` field from package.json

This fixes the issue, and the types fall back to index.d.ts in root of the project.

Now, obviously, I don't think this is a valid solution, `main` should remain. But included this just to illuminate the resolution order.

### Add `types` field to package.json

Adding `types: "index.d.ts"` to package.json (I tried by editing chalk's package.json directly in node_modules) fixes the issue.

My editor then resolves types for chalk to the typings file, instead of directly on index.js.

I don't see any issues by adding this field, but I might be blind to some other concerns.

Hope this is something that can get addressed, and that I've provided enough information :)

**Comment by sindresorhus** [comment]
TS doesn't require it if there is a index.d.ts file at the root, which Chalk had. But I agree, it's better to be explicit. This will be fixed in Chalk 5.

**Comment by dagerikhl** [comment]
Superb! Thank you, looking forward to v5, keep up the good work! 😀
