### ISSUE TITLE
TypeError: Chalk is not a constructor

### ISSUE THREAD

**Issue by slinkardbrandon** [chalk/chalk#513]
# Issue

I tried to instantiate a chalk instance so I could alter the `level` based on [this example in the docs](https://github.com/chalk/chalk#chalklevel) and received unexpected errors.

# Code

![image](https://user-images.githubusercontent.com/13923457/134191200-1d9ee894-5c63-403f-8c2c-60c46302eab8.png)

```js
// main.js
const { Chalk } = require('chalk');
const { yellow }  = new Chalk({ level: 0 });
```

The above code throws type error `TypeError: Chalk is not a constructor`. I was able to figure out a way to instantiate the instance but it wasn't quite one to one with how the docs suggested it.

# Workaround

I was able to instantiate a chalk instance with the following code:

```js
  const Chalk = require('chalk');
  const { red, yellow, green, white } = new Chalk.Instance({ level: 0 });
```

# Notes
* Chalk version `4.1.2`
* Not sure if this is an actual bug or just docs that might not be fully flushed out
* happy to help with a PR if needed

**Comment by sindresorhus** [comment]
The readme reflects the latest development changes, not necessarily the latest version. Make sure you read the docs for the correct version.
