### ISSUE TITLE
4.1.2 has mis-configured Typescript definition

### ISSUE THREAD

**Issue by rayfoss** [chalk/chalk#519]
Chalks types are not next to the main entrypoint file and thus TSC fails to compile them.

```
$ tsc
src/index.ts(3,19): error TS2307: Cannot find module 'chalk' or its corresponding type declarations.
```

https://codesandbox.io/s/ts-http-chalk-bug-lq2qz?file=/src/index.ts
https://unpkg.com/browse/chalk@4.1.2/package.json

## Workarounds from bad to worse

- Run this after the npm install hook, i.e. the install or prepare script:
```
#!/bin/bash
set -euo pipefail
sed -i '8s/"source",/"\.\/source\/index\.js",\n"types": "\.\/index\.d\.ts",/' node_modules/chalk/package.json
```

- Maybe: Manually reference chalk's types in an ambient declaration...
    - I can't get this to work in practice with a triple-slash directive
- Ambient type `declare module 'chalk'`. Treats chalk as if it has no types.
- move the node_modules/chalk/index.d.ts to node_modules/chalk/source/
- modify node_modules/chalk/package.json with `"types": "index.d.ts"`

**Comment by Qix-** [comment]
I see something has changed since that release. We already do what you're asking - it just hasn't been published yet.

@sindresorhus are we safe to cut a release?

**Comment by sindresorhus** [comment]
@Qix- There are still some unresolved things for v5: https://github.com/chalk/chalk/issues/431

**Comment by sindresorhus** [comment]
This really sounds like a TypeScript bug. `types` in package.json is optional if the file is `index.d.ts`.

**Comment by sindresorhus** [comment]
> Maybe we just do a patchfix branch and consider v4 frozen?

👍

**Comment by sindresorhus** [comment]
Will be fixed in v5.
