### ISSUE TITLE
inquirer.ui.BottomBar() cannot be registered to outputStream

### ISSUE THREAD

**Issue by sawamotokai** [chalk/chalk#522]
I was trying to use the bottom bar printing, but when I try to register `inquirer.ui.BottomBar()` my node process finishes there. Here's my code.
```javascript
const inquirer = require('inquirer')
const ui = new inquirer.ui.BottomBar()
console.log(ui)
outputStream.pipe(ui.log)
...
```
It immediately exits on line 4

**Comment by sindresorhus** [comment]
Wrong repo
