### ISSUE TITLE
Outdated package.json since 4.1.1

### ISSUE THREAD

**Issue by alopix** [chalk/chalk#523]
4.1.1 was supposed to add ESM support and require NodeJS 12, but looking at the published package contents on NPM, this does not show up in code anymore:

https://www.npmjs.com/package/chalk/v/4.1.1
https://www.npmjs.com/package/chalk/v/4.1.2

See the explore tab or download the files from NPM. If you compare them, they are not the same as checked into this repo.

**Comment by sindresorhus** [comment]
> 4.1.1 was supposed to add ESM support and require NodeJS 12

No it was not. What's in the main branch is supposed to do that, but it's not done yet. What's in the main branch is not necessarily always what's published. This is how most repos on GitHub works.

**Comment by alopix** [comment]
Actually cross-referenced release dates and main branch to make sure this could have been released yet. Which is how repos on GitHub usually work, but fine, if you have a different strategy.

**Comment by Qix-** [comment]
You're mistaken. 4.1.1 was published from branch `meta-tweaks` which is 2 commits diverged from `main`. The common ancestral commit is the 4.1.0, release which sported [this `package.json`](https://github.com/chalk/chalk/blob/4c3df8847256f9f2471f0af74100b21afc12949f/package.json#L10) which clearly targets Node >= 10.0 and is not ESM. 4.1.1 did not change that as can be seen [here](https://github.com/chalk/chalk/blob/89e9e3a5b0601f4eda4c3a92acd887ec836d0175/package.json#L10).

Dates mean nothing, look at the content please. Master/main are always to be considered bleeding edge. I'm not really sure where the confusion is - Chalk doesn't do anything weird or unusual here w.r.t. git repositories.

Nothing actionable and I see this conversation getting less civil moving forward so going to pre-emptively lock.
