### ISSUE TITLE
App not compatible with buildpack: https://github.com/chalk/chalk.git

### ISSUE THREAD

**Issue by NapalfIzon** [chalk/chalk#525]
I tried to install chalk in my Heroku app, but I receive this message:

-----> App not compatible with buildpack: https://github.com/chalk/chalk.git
       bash: /tmp/codon/tmp/buildpacks/05a9106f78527464f6cefe8428c7a32a337f0c59/bin/detect: No such file or directory
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed

I think it will be some incompatibility with this new version 😞

**Comment by Qix-** [comment]
Take it up with Buildpack, whatever that is. There's nothing for us to do here - we're not doing anything special or non-standard.
