### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/circleci/project/node_modules/chalk/source/index.js from /home/circleci/project/index.js not supported.

### ISSUE THREAD

**Issue by ItzMiracleOwO** [chalk/chalk#528]
https://app.circleci.com/pipelines/github/RadishTeam/RadishBot/33/workflows/905f695c-fd3a-4bba-9e29-bdd1111ed8a7/jobs/66?invite=true#step-105-20

**Comment by ItzMiracleOwO** [comment]
any fixes?

**Comment by shkvoretz** [comment]
having same issue here

**Comment by Qix-** [comment]
This is by design. Chalk 5 is ESM only. Please read the release notes.
