### ISSUE TITLE
Missing audit in the actions workflow

### ISSUE THREAD

**Issue by ivanblazevic** [chalk/chalk#530]
Can you introduce `npm audit` in the actions workflow which would eventually resolve following problem I have because of the chalk lib? 

<img width="911" alt="Screenshot 2022-01-05 at 11 45 22" src="https://user-images.githubusercontent.com/2737184/148205074-904cc173-5a8f-4d8c-8e82-b5753fb06419.png">

**Comment by sindresorhus** [comment]
Chalk does not depend on `ansi-regex` and it has not done it for years. So it sound like the project you're using needs to upgrade Chalk.

**Comment by ivanblazevic** [comment]
@sindresorhus would like to upgrade but looks like chalk does not support node 12:
<img width="907" alt="Screenshot 2022-01-14 at 23 24 53" src="https://user-images.githubusercontent.com/2737184/149593129-14d32663-3d0c-47df-b96b-45ba7b352ef1.png">

**Comment by sindresorhus** [comment]
Chalk supports Node.js 12 fine. The problem is your TypeScript types. Make sure you're using the latest Node.js types and latest TS version.

Also read: https://github.com/chalk/chalk/releases/tag/v5.0.0
