### ISSUE TITLE
jest-resolve cannot find module #ansi-styles

### ISSUE THREAD

**Issue by davcd** [chalk/chalk#532]
When using the following configuration.

chalk - 5.0.0
jest - 27.4.7
npm - 6.14.15
node - v14.18.2
system - Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
ESM

And importing a file that is using chalk for testing it

``` javascript
// file.js
import chalk from 'chalk'
....

//file.test.js
import * as file from "./file.js"

test('Just a test',() => {
  expect(true).toStrictEqual(true)
})
```

I get the following output:

``` bash
Test suite failed to run
Cannot find module '#ansi-styles' from 'node_modules/chalk/source/index.js'
at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
```

It's necessary to add the '#' after the modules at ```chalk/source/index.js```?

Workaround:

Using "moduleNameMapper" in your jest configuration will make test-resolve work as expected

``` json
"jest": {
  "moduleNameMapper": {
    "#(.*)": "<rootDir>/node_modules/$1"
  }
}
```

**Comment by sindresorhus** [comment]
This is a problem with Jest, not this package. Open an issue on Jest instead.

---

https://github.com/chalk/chalk/releases/tag/v5.0.0

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by jakub-bao** [comment]
Having the same issue. Thanks @davcd for the solution!

> Using "moduleNameMapper" in your jest configuration will make test-resolve work as expected

In package.json:
```
"jest": {
  "moduleNameMapper": {
    "#(.*)": "<rootDir>/node_modules/$1"
  }
}
```
