### ISSUE TITLE
Cannot find module 'chalk' on macOS

### ISSUE THREAD

**Issue by programVeins** [chalk/chalk#533]
Trying to use latest release of chalk on my project but this error pops up when I try to import chalk.
<img width="1534" alt="Screenshot_2022-01-14_at_3_44_36_PM" src="https://user-images.githubusercontent.com/25583875/149502624-161d9551-133a-4c63-b16c-4a02216a32d0.png">

However I saw that a friend of mine had used chalk in a similar context (chalk v4.1.1) so I decided to uninstall and reinstall chalk as `npm install chalk@^4.1.1` and the error is no longer triggered.

Using macOS 12.1 Monterey running on Apple M1.
Node v17.0.1

**Comment by sindresorhus** [comment]
https://github.com/chalk/chalk/releases/tag/v5.0.0

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
