### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by xiongemi** [chalk/chalk#534]
After upgrade from 4.1.2 to 5.0.0, I got this error:

Must use import to load ES Module: /Users/emilyxiong/Code/nx/node_modules/chalk/source/index.js
require() of ES modules is not supported.

Any idea on how to fix this?

**Comment by webdiscus** [comment]
Hello @xiongemi,

try to use the alternate [ansis](https://github.com/webdiscus/ansis).
This lib support ES Module and CommonJS.
This lib support chalk API and is faster.

**Comment by sindresorhus** [comment]
https://github.com/chalk/chalk/releases/tag/v5.0.0

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by davetapley** [comment]
Last version with `require` support:

```
npm i chalk@v4.1.2
```
