### ISSUE TITLE
Chalk with ESLint & Airbnb Base

### ISSUE THREAD

**Issue by jmcombs** [chalk/chalk#536]
I am using the latest version of Chalk and using ESLint with the Airbnb Base. Unfortunately, when I import chalk, am getting the following linting error: **Unable to resolve path to module 'chalk'. eslint([import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.25.4/docs/rules/no-unresolved.md]))**

The module loads and works fine but it is throwing that linting error and it is driving me nuts.

`package.json` for DevDependencies and ESLint config:
```json
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.13.0",
    "@typescript-eslint/parser": "^5.13.0",
    "eslint": "^8.10.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-prettier": "^4.0.0",
    "nodemon": "^2.0.15",
    "prettier": "^2.5.1",
    "typescript": "^4.6.2"
  },
  "eslintConfig": {
    "extends": [
      "airbnb-base",
      "plugin:@typescript-eslint/recommended",
      "plugin:prettier/recommended"
    ],
    "env": {
      "node": true
    }
  },
```

`app.js` where I call Chalk:

```js
import express, { json, urlencoded } from 'express';
import helmet, { contentSecurityPolicy } from 'helmet';
import morgan from 'morgan';
import Debug from 'debug';
import chalk from 'chalk';

console.log(`${chalk.red('Hello!'});
```

I could use some guidance as to why it's throwing this for Chalk. I am not getting that error for my other Packages. Thanks!

**Comment by Qix-** [comment]
Chalk isn't in your dependencies...?

**Comment by jmcombs** [comment]
@Qix Chalk is in my dependencies. I only posted my devdependencies. Happy to post my dependencies but chalk is in there. As I said, chalk works when I run my app, for whatever reason ESLint is throwing the error above.

**Comment by Qix-** [comment]
You should open an issue with ESLint then, not sure what we could even do to fix that.

**Comment by jmcombs** [comment]
@Qix- it looks like the issue is because `"main": "./source/index.js",` is missing from `package.json`.

```json
	"repository": "chalk/chalk",
	"funding": "https://github.com/chalk/chalk?sponsor=1",
	"type": "module",
	"main": "./source/index.js",
	"exports": "./source/index.js",
```

Once `main` is added to `package.json` linting passes. 

The linting error pops up due to package [import-js/eslint-plugin-import](https://github.com/import-js/eslint-plugin-import). There is an open issue [Rule import/no-unresolved raise false positive when there is no main field in the package.json #2132](https://github.com/import-js/eslint-plugin-import/issues/2132) but the maintainer of that package is adamant that proper etiquette is to include both `main` and `exports` in `package.json`. [Main entry point export](https://nodejs.org/api/packages.html#packages_main_entry_point_export) has also been referenced as justification for this requirement from the NodeJS website.

Is this something you would be willing to add or would you prefer me to submit a PR with a fix? (I am new to this)

**Comment by Qix-** [comment]
@sindresorhus knows more about this. package.json is a mess to be honest, he's more up to date about what should go in it. I'll defer to him.

**Comment by sindresorhus** [comment]
`main` can be useful when you have backwards compatibility with CommonJS. Chalk does not support CommonJS, so it makes no sense to specify it when `exports` is the proper way to define entry points. I don't plan to add `main` just because the maintainer of the `import` ESLint plugin is difficult (he usually is).

**Comment by sindresorhus** [comment]
> but the maintainer of that package is adamant that proper etiquette is to include both main and exports in package.json

That argument is irrelevant as `eslint-plugin-import` must support the `exports` field regardless as that field has many more capabilities that `main` cannot reflect.

**Comment by ljharb** [comment]
@sindresorhus i don't think the personal attack is called for nor appropriate.

**Comment by sindresorhus** [comment]
@ljharb This is not productive. I simply said you're being difficult, which you are. You chose to spend the whole thread at `eslin-plugin-import` bad-mouthing my work and choices instead of just saying that `exports` will be supported at some point.

**Comment by sindresorhus** [comment]
But fine, I will add the `main` field to help users.

**Comment by sindresorhus** [comment]
https://github.com/chalk/chalk/releases/tag/v5.0.1
