### ISSUE TITLE
Git Submodules for vendoring modules

### ISSUE THREAD

**Issue by Richienb** [chalk/chalk#545]
If the repositories of the two vendored modules are each added as [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules), would it make it easier to synchronise?

**Comment by Qix-** [comment]
![](https://media2.giphy.com/media/pUeXcg80cO8I8/giphy.gif?cid=ecf05e47hojcverk8ecvvrdewipqeqif807oze2mphqa4ze4&rid=giphy.gif&ct=g)

Opening a can of worms this morning, I see. :D

I'm all for it, but I know many people don't like them because they don't understand how to use them properly. I use submodules often so I'm in support.

**Comment by sindresorhus** [comment]
I don't want to deal with Git submodules. These two packages don't change very often anyway. It's easy enough to just copy-paste over the files.

**Comment by Qix-** [comment]
Curious @sindresorhus what's the sucky UX you face with them? By contrast I haven't had issues with them for almost 6 years of using them extensively in the C/C++ world.

**Comment by sindresorhus** [comment]
Having submodules doesn't just affect us, but any potential contributor. You are forcing everyone wanting to contribute to learn all the weird behavior of submodules.

https://medium.com/@uttamkini/sharing-code-and-why-git-submodules-is-a-bad-idea-1efd24eb645d

**Comment by Qix-** [comment]
1. Author is editing in submodules. Don't do that. That's not what they're made for.
2. See 1
3. This is a feature, not a poor design. Submodules are treated as part of the commit snapshot. They'd be worthless if they didn't do this.

You can misuse every feature of every program. The author of that article clearly doesn't understand the intended use case. They want a monorepo. Not submodules.

**Comment by sindresorhus** [comment]
You say "don't do that", but in the end, we are the ones that have to deal with contributors support when the contributor "does" do that.

**Comment by sindresorhus** [comment]
> I use submodules in almost every c/c++ project I write. Never really have issues with them.

Because it's common to use them in this ecosystem, so contributors for C++ are generally more familiar with it. That is not the case with JS.

**Comment by Qix-** [comment]
Fair enough. I disagree with the assertion that they're bad though, and I don't think we should judge merits based on how newbie coders misuse software.

By contrast we have a worse case scenario now anyway; manually vendoring is much more work than submodules are.
