### ISSUE TITLE
is way to pass color to chalk?

### ISSUE THREAD

**Issue by geetee24** [chalk/chalk#546]
is there a way to do:  chalk [ myvar]     where myvar can be set to 'red'

Thank you

**Comment by Qix-** [comment]
```javascript
const myColor = chalk.red;
console.log(myColor('hi'));
```

Doesn't work?

**Comment by geetee24** [comment]
thats not what I want to do.

I want:

var myvar= red;

console.log ( chalk [ myvar] ( 'i am text in red' );

**Comment by Qix-** [comment]
```javascript
car myvar = 'red';
```

**Comment by geetee24** [comment]
what is 'car'

**Comment by Qix-** [comment]
A typo, I'm on mobile, apologies.
