### ISSUE TITLE
something error please help 

### ISSUE THREAD

**Issue by getsettalk** [chalk/chalk#549]
const chalk = require('chalk');
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module D:\nodejs\importExport\node_modules\chalk\source\index.js from D:\nodejs\importExport\import.js not supported.
Instead change the require of index.js in D:\nodejs\importExport\import.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\nodejs\importExport\import.js:1:15) {
  code: 'ERR_REQUIRE_ESM'
}

`showing above type error `

**Comment by tendal-lox** [comment]
you have to install the last version of it, v4

**Comment by sindresorhus** [comment]
Duplicate of #549

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
