### ISSUE TITLE
chalk tried to access #ansi-styles, but it isn't declared in its dependencies

### ISSUE THREAD

**Issue by meglio** [chalk/chalk#553]
Just trying to use chalk `5.0.1` by running a script through yarn (zero-installs mode):

`yarn node my-script.mjs`

The script imports chalk as a ES6 module:

`import chalk from 'chalk';`

An error is reported:

> Error: chalk tried to access #ansi-styles, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

> Required package: #ansi-styles (via "#ansi-styles/package.json")
Required by: chalk@npm:5.0.1 (via /.yarn/cache/chalk-npm-5.0.1-6afcb94227-7b45300372.zip/node_modules/chalk/source/index.js)

**NB: Rolling back to 4.1.2 makes the same script work just fine.**

**Comment by sindresorhus** [comment]
This is a problem with Yarn: https://github.com/yarnpkg/berry/issues/3843

**Comment by mrienstra** [comment]
Update: the fix that adds support for the `package.json` `includes` field is also in the [Yarn `3.2.4` release](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F3.2.4).
