### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by YaYaPao** [chalk/chalk#557]
I found chalk can't work fine on Node.js runtime with Rollup.

Environment:
Node.js v16.16.0
chalk: ^5.0.1
rollup v2.77.0

Here is steps to reproduce the issue:

1. Create a `src/test.ts`
```ts
import chalk from 'chalk'

async function testChalk() {
  console.log(chalk.cyanBright('Hello World!'))
}

export default testChalk
```
2. Config `rollup.config.js`
```js
import typescript from '@rollup/plugin-typescript'
import commonjs from '@rollup/plugin-commonjs'
import resolve from '@rollup/plugin-node-resolve'
import path from 'node:path'
import { defineConfig } from 'rollup'

const defaultOptions = defineConfig({
  input: path.resolve(__dirname, 'src/test.ts'),
  output: {
    dir: path.resolve(__dirname, 'dist'),
    format: 'esm',
  },
  plugins: [typescript(), resolve(), commonjs()],
})

export default () => {
  return defineConfig([defaultOptions])
}
```
3. Test  `node testChalk.mjs`
```js
import testChalk from '../dist/testEnvinfo.mjs'
testChalk()
```

And throw an Error like below:

```
file:///[execute file path]/testChalk.mjs:221
const isBlinkBasedBrowser = /\b(Chrome|Chromium)\//.test(navigator.userAgent);
                                                         ^

ReferenceError: navigator is not defined
```

**Comment by Qix-** [comment]
Seems like a bug in Rollup, please open an issue with them.

It's choosing to bundle the `default` vendor import rather than the `node` import.

https://github.com/chalk/chalk/blob/main/package.json#L14

**Comment by Aiden-FE** [comment]
This is not Rollup problem.

**Comment by Aiden-FE** [comment]
> Seems like a bug in Rollup, please open an issue with them.
> 
> It's choosing to bundle the `default` vendor import rather than the `node` import.
> 
> https://github.com/chalk/chalk/blob/main/package.json#L14

@Qix- @YaYaPao

**Comment by Qix-** [comment]
The point was more "this is not a chalk problem". Glad you got it working though :+1:.

**Comment by fabien** [comment]
@Aiden-FE I just ran into this same issue - however, I cannot simply disable `@rollup/plugin-node-resolve` because I have other dependencies. Is there anything else to try, perhaps?

**Comment by YaYaPao** [comment]
> @Aiden-FE I just ran into this same issue - however, I cannot simply disable `@rollup/plugin-node-resolve` because I have other dependencies. Is there anything else to try, perhaps?

Maybe [picocolor](https://github.com/alexeyraspopov/picocolors) can solve your problem. Or just config `external: ['chalk']` in rollup.config.js.

**Comment by Aiden-FE** [comment]
> @Aiden-FE I just ran into this same issue - however, I cannot simply disable `@rollup/plugin-node-resolve` because I have other dependencies. Is there anything else to try, perhaps?

I'm also looking for a better way.

**Comment by fabien** [comment]
I found this answer to be working for me: https://github.com/SBoudrias/Inquirer.js/issues/1153#issuecomment-1212827810

**Comment by Aiden-FE** [comment]
> I found this answer to be working for me: [SBoudrias/Inquirer.js#1153 (comment)](https://github.com/SBoudrias/Inquirer.js/issues/1153#issuecomment-1212827810)

It can solve my problem,thank you very much for shared.

**Comment by Qix-** [comment]
I'm sorry but **this isn't a chalk problem**. This is Rollup selecting the incorrect source file based on package.json contents. There's nothing we can do, **you need to open relevant issues with the rollup folks**.
