### ISSUE TITLE
require not support

### ISSUE THREAD

**Issue by chtheitmmmmm** [chalk/chalk#560]
Today I use this package in typescript, I encounter an error when run its compiled file, which is descriped "require() is not support". Are there any lower version or a resolution to this problem? Thanks.

**Comment by Aiden-FE** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by Qix-** [comment]
This has been covered so many times in the issue tracker that I can't imagine you even attempted to search for anything related to this.
