### ISSUE TITLE
build cli error 

### ISSUE THREAD

**Issue by coder-fang** [chalk/chalk#561]
There is a error when I want to build a cli for the fronted project and I want to tell you that error is "require() of ES modules is not supported.  change the requiring code to use import(), or remove 'type': 'module' " when I use "require('chalk')" or "chalk.cyan is not a function" when I use "import('chalk')"  so that I don't know how to import this outside module for my cli if I need to import the chalk.

**Comment by Qix-** [comment]
Perhaps if you had searched, you'd have found an answer quicker.

https://github.com/chalk/chalk/issues/534#issuecomment-1013617867
