### ISSUE TITLE
Can I translate your 'README' into Korean?

### ISSUE THREAD

**Issue by po4tion** [chalk/chalk#577]
Hello, I am a Korean and a developer who loves 'chalk'. Developer experience has increased using 'chalk' now.
Thank you for your efforts.
I would like to introduce this awesome 'chalk' to Korea more and share the experience that more developers use it and the developer experience is further enhanced. If you allow me, I would like to proceed with the translation of readme into Korean.
I apologize if you find this question offensive. I hope you have a great day today!

**Comment by sindresorhus** [comment]
I appreciate the kind offer, but we don't have any plans to provide localized docs. It's just too much work to keep it updated (I have tried it on other projects in the past).
