### ISSUE TITLE
(Windows) chalk.gray.dim not visible

### ISSUE THREAD

**Issue by Semigradsky** [chalk/chalk#58]
Only when highlight in cmder.

In cmd:

|Normal|Highlight|
|---|---|
|![image](https://cloud.githubusercontent.com/assets/1198848/6571406/2894d8e4-c719-11e4-8f19-67335593a46d.png)|![image](https://cloud.githubusercontent.com/assets/1198848/6571411/2ecaecf8-c719-11e4-963d-d4df7b4b8bfd.png)|

In cmder:

|Normal|Highlight|
|---|---|
|![image](https://cloud.githubusercontent.com/assets/1198848/6571416/3c084730-c719-11e4-91ba-c968d443ae20.png)|![image](https://cloud.githubusercontent.com/assets/1198848/6571422/47eb3062-c719-11e4-8e2a-1c0df86ac90d.png)|

**Comment by sindresorhus** [comment]
Confirmed. Why am I not even a little bit surprised...

To be totally clear though. This is a Windows bug.

I guess we can make `dim` a no-op on `gray` on Windows ;) @jbnicolai thoughts?

![windows-fail-nyan](https://cloud.githubusercontent.com/assets/170270/6573232/edc48e68-c753-11e4-8a94-2cbf7bb363e0.gif)

**Comment by jbnicolai** [comment]
@sindresorhus I guess we'll have to :disappointed:

**Comment by arthurvr** [comment]
> I guess we can make dim a no-op on gray on Windows ;) @jbnicolai thoughts?

Sounds good :cry:

**Comment by jbnicolai** [comment]
@arthurvr @Semigradsky how about this? #72
