### ISSUE TITLE
The latest chalk does not support the CommonJS specification

### ISSUE THREAD

**Issue by CasualMing** [chalk/chalk#593]
version:
 - chalk：5.2.0
 - webacpk: 5.74.0
 - node: 14+
 
When I want to use it in webpack, it prompts me that ES modules are not supported

**Comment by shankiflang** [comment]
Same problem for me !

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
