### ISSUE TITLE
DISABLE_CHALK environment variable

### ISSUE THREAD

**Issue by andrewshawcare** [chalk/chalk#597]
In some contexts I would like to remove all colors and formatting and have plain output.

There are some libraries that use chalk and the formatting characters end up in logging systems that cannot support terminal presentation. In contexts where this occurs, it would be beneficial to not only suppress colors, but all control characters.

This could resort to either no presentational treatment or equivalent Markdown representation (i.e. `**lorem ipsum**` for ```chalk`{bold lorem ipsum}` ```.

Help here would be greatly appreciated. :)

**Comment by Qix-** [comment]
Does [`FORCE_COLOR=0`](https://github.com/chalk/supports-color#info) not work?

**Comment by Qix-** [comment]
Going to close as there is a clear solution here. Let me know if that doesn't work for you for some reason!
