### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by ostli** [chalk/chalk#598]
Use in electron main process, has above error
<img width="708" alt="image" src="https://user-images.githubusercontent.com/17735161/232950775-f97b57de-300f-453d-aa5a-5d9b4b65591b.png">

**Comment by sindresorhus** [comment]
This is not a problem with this package. Seems like you have the wrong config in your bundler and it's picking up the browser version of Chalk.

**Comment by jamiehaywood** [comment]
### For anyone that hits this issue in the future and is using `rollup` and `@rollup/plugin-node-resolve`:

Chalk's subpath import for `"#supports-color"` in the `package.json` has a `node` and `default` key - [see here](https://github.com/chalk/chalk/blob/main/package.json#L13C3-L16C4). 

Bizarrely, `plugin-node-resolve` [resolves subpath imports to the `default` key](https://github.com/rollup/plugins/tree/master/packages/node-resolve#exportconditions), which in this case points at the browser entry for `supports-color`.

To fix this, I added `{ exportConditions: ['node'] }` key to my `plugin-node-resolve`, which resolved `supports-color` to the node version.

**Comment by TanjimAnim** [comment]
@jamiehaywood I am using nextJS and it is using webpack as bundler. So, I am experiencing the same problem. But in webpack. And I am no expert in webpack. 
Is there any workaround for webpack for this particular problem. 
For context, I am gettting the same error in nextJS middleware.

**Comment by rharkor** [comment]
> @jamiehaywood I am using nextJS and it is using webpack as bundler. So, I am experiencing the same problem. But in webpack. And I am no expert in webpack. Is there any workaround for webpack for this particular problem. For context, I am gettting the same error in nextJS middleware.

Hi,
Any update on this ?

**Comment by TanjimAnim** [comment]
Sorry I forgot about this issue. I may have found a workaround or didn't use navigator.

**Comment by 1aron** [comment]
For `rollup.config.js`, this works for me:
```js
import { nodeResolve } from '@rollup/plugin-node-resolve'

export default {
    plugins: [
        nodeResolve({
            exportConditions: ['node', 'import', 'require', 'default']
        })
    ],
}
