### ISSUE TITLE
Add more colors

### ISSUE THREAD

**Issue by sadik3311** [chalk/chalk#601]
It'd be great if it has more color. Such as: Powder Blue, Powder Pink, Orange, and more

**Comment by sindresorhus** [comment]
The named colors are defined by terminals. We do support 16 million (unnmaed) colors for many terminals.

**Comment by Qix-** [comment]
FWIW we used to have this functionality but decided against including the dependency. You can use `color-convert` to get RGB colors from [CSS keywords](https://developer.mozilla.org/en-US/docs/Web/CSS/named-color) with `require('color-convert').keyword.rgb('orange')`.
