### ISSUE TITLE
Chalk is not working in Jenkins multibranch pipeline 

### ISSUE THREAD

**Issue by akash-jivani** [chalk/chalk#602]
I have created on function in typescript file and use chalk as a warning and error log as below

import chalk from "chalk";
console.warn(chalk.bgRed.underline("[WARN] Error while "))

In my windows system cmd it is showing color code but in jenkins it is not showing the color.

In Jenkins I have use ansiColor('xterm') but still I can't see the color code output in my jenkins console log

**Comment by sindresorhus** [comment]
You can force the color. See the docs. Whether the color shows depends on many factors.

https://github.com/chalk/supports-color
