### ISSUE TITLE
Cannot find module 'chalk'. Did you mean to set the 'moduleResolution' option to 'nodenext', or to add aliases to the 'paths' option?

### ISSUE THREAD

**Issue by gufee1998** [chalk/chalk#606]
When I use esm to import chalk in my ts project, vscode warn this issue title above. I've installed chalk@5.3.0, and have set the package.json's 'type' attribute to 'module'. My tsconfig.json like this:
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "dist",
    "strict": true,
    "target": "ES5",
    "module": "ES6",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "paths": {
      "@/*": [
        "src/*"
      ]
    }
  },
  "include": [
    "src/**/*.ts",
  ],
  "exclude": [
    "node_modules/**/*",
    "public/**/*",
    "dist/**/*"
  ],
  "ts-node": {
    "esm": true,
  }
}
```
I've tried to declare a module named 'chalk' in the global.d.ts, the vscode warn disappered, but still resolve failed when launch my project by the ts-node, throw an error as this issue title mentioned. 
Then I tried to set the 'moduleResolution' option to 'nodenext', vscode warning "When "--moduleResolution" is "node16" or "nodenext", the relative import path requires an explicit file extension in the EcmaScript import". 
So I add file extension , the vscode warning with another problem: "An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled"...Jesus... I set the tsconfig's properties "allowImportingTsExtensions" and "noEmit" to true. These are not my expected result, I don't want to add file extension, in addition, I'd like get the compiled code by tsc compiler. 
Please help me figure out what the problem is.

**Comment by sindresorhus** [comment]
See: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm

**Comment by gufee1998** [comment]
> See: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm

I see, thank you
