### ISSUE TITLE
chalk not suppported??

### ISSUE THREAD

**Issue by KevinASaputra** [chalk/chalk#608]
is chalk not supported by terminal windows? I am using windows terminal and hyper terminal is getting error : `Error [ERR_REQUIRE_ESM]: require() of ES Module D:\code\belajar-nodejs\learn-modules-npm\node_modules\chalk\source\index.js from D:\code\belajar-nodejs\learn-modules-npm\app.js not supported.`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by KevinASaputra** [comment]
thanks bro
