### ISSUE TITLE
Is it possible to apply a style conditionally?

### ISSUE THREAD

**Issue by JorensM** [chalk/chalk#614]
Hello, I have a case where a user can optionally pass `color` and `bgColor`, and if one of these values is passed, I want to render the text with chalk according to the passed color. But the user can omit these options, in which case I would like to render the terminal's default colors.

```
const printText = (str: string, color: string | undefined, bgColor: string | undefined) => {
    console.log(chalk.bgHex(bgColor).hex(color)(str))
}
```

The code above throws an error if either `color` or `bgColor` are undefined. How can I conditionally omit a style in case if the value passed is `undefined`?

Thanks.

**Comment by JorensM** [comment]
For now I'm doing this: 

```
const chalkBg = bgColor ? chalk.bgHex(bgColor) : chalk
const chalkColor = color ? chalk.hex(color) : chalk

console.log(chalkBg(chalkColor(str)))
```

Which I extracted into an all-purpose function: 

```
//You can use conditionalChalk() to use any of the chalk's builders conditonally
const conditionalChalk = (value: any, chalkBuilder: (value: any) => chalk.Chalk) => 
    value ? chalkBuilder.call(chalk, value) : chalk
const conditionalBg = (color: string | undefined | null) => conditionalChalk(color, chalk.bgHex)
const conditionalColor = (color: string | undefined | null) => conditionalChalk(color, chalk.hex)

console.log(conditionalBg(bgColor)(conditinalColor(color)(str)))
```

But I'm wondering if there's a more elegant solution, or perhaps some built-in way how to accomplish this?

**Comment by JorensM** [comment]
I guess ideally chalk just wouldn't throw an error when undefined is passed to the builder, and just skip the styling for that. Perhaps add an option for that?

**Comment by Qix-** [comment]
Does this work?

```javascript
let color = chalk;
color = fg ? chalk[fg] : color;
color = bg ? chalk[bg] : color;
color("whatever")
```

**Comment by JorensM** [comment]
@Qix- Thanks, you can see here https://github.com/chalk/chalk/issues/614#issuecomment-1731181525 that I did something similar.

I'm wondering if I should keep this issue open to see if there are more people who need this in which case it could be considered to build this into Chalk

**Comment by Qix-** [comment]
Unfortunately there's no chance this would be in scope for the project as it's highly project-specific. I'll close for now, but I appreciate the issue :)
