### ISSUE TITLE
Remove README.md from bundle

### ISSUE THREAD

**Issue by H4ad** [chalk/chalk#617]
The package is 44.7kb, and the README alone is 11.3kb.

~If you just remove the README from the bundle, you can save \~25% in bundle size, which could save 3TB (279,859,270 * 11.3kb) each week.~

We cannot remove but if we put a placeholder, we can save ~631GB/week (3,7×228240517÷1024÷1024) of bandwidth (13.3kB to 10.4kB).

**Comment by H4ad** [comment]
From what I saw, is impossible to remove Readme, but maybe you can rename/remove before packing or try reduce the size of the readme.

**Comment by sindresorhus** [comment]
You are trying to fix this in the wrong place. You should open an issue on npm instead. Lots of users use the npm page for docs, so we cannot truncate it in any way.
