### ISSUE TITLE
is support require('chalk')?

### ISSUE THREAD

**Issue by zhumenglonge** [chalk/chalk#620]
Error [ERR_REQUIRE_ESM]: require() of ES Module

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by IPRIT** [comment]
`chalk 4` now is the most popular version. No one using 5+ version of the package.

**Comment by Qix-** [comment]
Every latest major version has a disproportionate amount of downloads due to npm and other package managers defaulting to upgrading to the latest minor.patch semver version.

Not that that really matters.
