### ISSUE TITLE
Chalk italic modifier is not applied in Windows Git Bash terminal.

### ISSUE THREAD

**Issue by KAYounes** [chalk/chalk#621]
#### chalk version 4.1.2
I am using Windows terminal with a git bash profile.

I have a custom git prompt and I have used italic text and it dose work.

![image](https://github.com/chalk/chalk/assets/67270781/8ab23114-a745-4471-8a9d-971bef5ef30d)

However, using `chalk.italic(...)` dose not output italic text in git bash; however, it dose output italic text in Windows PowerShell, and yes both use the same font.

I have not tested this in later versions; however, I have read the patch notes of each subsequent versions but nothin mentioned a fix.

**Comment by Qix-** [comment]
Nothing we can do about this, sorry. You need to open an issue with Microsoft.
