### ISSUE TITLE
New Windows fluent emoji font - color is wrong

### ISSUE THREAD

**Issue by ocombe** [chalk/chalk#625]
Last week Microsoft released the new emoji fluent font (see: https://medium.com/microsoft-design/bringing-new-emoji-to-windows-11-02a4a488c38b), and it seems like chalk doesn't color it correctly.

This is how the check mark colored in green looks like in my terminal now:
![image](https://github.com/chalk/chalk/assets/265378/231839af-30ee-4334-af65-17ccb8edcf89)

It was a nice green before, since we use `chalk.green('✔')`. But now it's purple, and it's ugly. Any chance you could look into that and fix the display to use the monochrome version that you would color to green normally? Not sure if it's possible... (I have no idea how chalk works 😅)

**Comment by sindresorhus** [comment]
Chalk (and any other color library) cannot color emojis. You could try to force it to not render as an emoji: https://itecnote.com/tecnote/javascript-how-to-prevent-unicode-characters-from-rendering-as-emoji-in-html-from-javascript/
