### ISSUE TITLE
【suggestion】support commonjs version

### ISSUE THREAD

**Issue by weidehai** [chalk/chalk#627]
it seem that chalk does not support commonjs syntax，is there consider to implement it？
compile commonjs version and specific commonjs requier path use exports field in package.json，like
"exports": {
  ".": {
    "require": "./commonjs-version-path/index.js",
    "import": "./src/index.js"
  },
}
If needed, I am willing to make a pr

**Comment by sindresorhus** [comment]
This is not going to happen.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
