### ISSUE TITLE
win32 specific override polluting other consumers

### ISSUE THREAD

**Issue by stefanpenner** [chalk/chalk#63]
https://github.com/sindresorhus/chalk/blob/master/index.js#L15-L17

Although this may be a default chalk prefers, it pollutes `blue` for others who consume this module (depending on the NPM topology).

It might be a better idea if `chalk` merely wrapped ansi color, and delegated `blue` to `brightblue`

**Comment by sindresorhus** [comment]
> Although this may be a default chalk prefers, it pollutes blue for others who consume this module (depending on the NPM topology).

Why is this a problem? It's done for a very good reason, as `blue` on Windows CMD is completely illegible and I've gotten so many issues about using `blue` on various repos the past year.

> It might be a better idea if chalk merely wrapped ansi color, and delegated blue to brightblue

How is that different from how it works now?

**Comment by stefanpenner** [comment]
Because it is overriding code from the ansi-color module, if that module happens to be de-dupped, this polution will affect other libraries consuming It.

**Comment by SBoudrias** [comment]
Basically cloning ansi-color definition before modifying it: https://github.com/sindresorhus/chalk/blob/master/index.js#L16

**Comment by sindresorhus** [comment]
I didn't think of that scenario. I guess we're going to see a LOT of similar problems when npm@3 comes out. In hindsight exporting `ansi-styles` as an object was not the best idea...

Changing `ansi-styles` to export a function that returns a fresh object might be better, as others might also fall into this trap.

**Comment by shinnn** [comment]
> Changing `ansi-styles` to export a function that returns a fresh object

:+1: Sounds good to me.

**Comment by stefanpenner** [comment]
Yes. Although ansi-color providing a fresh clone seems unrelated. Mutating foreign modules should be considered poor practice. Relying on a foreign module to clone itself seems error prone, unless it becomes a tested and official part of the public api.

**Comment by jbnicolai** [comment]
Awaits discussion in https://github.com/chalk/ansi-styles/pull/10

After that: bump the `ansi-styles` version and switch to `.create`.
