### ISSUE TITLE
Browser Sync problem

### ISSUE THREAD

**Issue by Spadhouse** [chalk/chalk#631]
Hello, please do not ask me to many, its my first day of HTML5 course and I can't download browser Sync, I use Terminal and enter the code "npm install -g browser-sync" and it doesn't work, 
t's my first day of HTML5 course and I can't download browser Sync, I use Terminal and enter the code "npm install -g browser-sync" I press enter and it doesn't work, it appears
changed 147 packages in 4s

8 packages are looking for funding
  run `npm fund` for details

please, help and thanks in advance

**Comment by Qix-** [comment]
This has nothing to do with this package, we cannot help you with this. Best of luck on your course.
