### ISSUE TITLE
Chalk Causes Report Generation Failure: TypeError - import_chalk.default.gray is not a function

### ISSUE THREAD

**Issue by sumit91221** [chalk/chalk#638]
Chalk is installed as below in project:

├─┬ @wdio/cli@9.4.3
│ ├─┬ @wdio/globals@9.4.3
│ │ └─┬ expect-webdriverio@5.0.5
│ │   ├─┬ expect@29.7.0
│ │   │ ├─┬ jest-message-util@29.7.0
│ │   │ │ ├─┬ @jest/types@29.6.3
│ │   │ │ │ └── chalk@4.1.2
│ │   │ │ └── chalk@4.1.2
│ │   │ └─┬ jest-util@29.7.0
│ │   │   └── chalk@4.1.2
│ │   └─┬ jest-matcher-utils@29.7.0
│ │     ├── chalk@4.1.2
│ │     └─┬ jest-diff@29.7.0
│ │       └── chalk@4.1.2
│ ├─┬ @wdio/logger@9.1.3
│ │ └── chalk@5.3.0 deduped
│ ├─┬ @wdio/utils@9.4.3
│ │ └─┬ wait-port@1.1.0
│ │   └── chalk@4.1.2
│ ├── chalk@5.3.0
│ └─┬ ejs@3.1.10
│   └─┬ jake@10.9.2
│     └── chalk@4.1.2
├─┬ @wdio/mocha-framework@9.4.3
│ └─┬ mocha@10.8.2
│   └─┬ log-symbols@4.1.0
│     └── chalk@4.1.2
└─┬ @wdio/spec-reporter@9.4.3
  └── chalk@5.3.0 deduped
  

Getting Error : Report Generation Failed: TypeError - import_chalk.default.gray is not a function, while generating the report using ReportAggregator from wdio-html-nice-reporter

**Comment by sindresorhus** [comment]
This is unrelated to Chalk. You need to open this on wdio-html-nice-reporter
