### ISSUE TITLE
Remove `has-ansi` and `strip-ansi` dependencies

### ISSUE THREAD

**Issue by sindresorhus** [chalk/chalk#70]
I never use them and in hindsight it was a mistake to bundle them. They're only useful in some instances and then you can just require them directly.

**Comment by sindresorhus** [comment]
@jbnicolai Maybe we should `require('util').deprecate` them in a minor release? Or is that too annoying for users?

**Comment by kevva** [comment]
That's probably annoying, depending on how many are making use of them.

**Comment by arthurvr** [comment]
Yea, kinda annoying.

**Comment by sindresorhus** [comment]
Ok, it will be a major release anyways, so let's just drop doing that.

**Comment by jbnicolai** [comment]
Yeah, let's go with a major for that. Seems nicer towards the users
