### ISSUE TITLE
Where does 37/39 come from?

### ISSUE THREAD

**Issue by step1step2** [chalk/chalk#75]
![I1](http://i.imgur.com/m72WubV.png)
.replace(/\[/g, chalk.white('['))
![2](http://i.imgur.com/e2F6DnW.png)

**Comment by jbnicolai** [comment]
See [color codes](https://en.wikipedia.org/wiki/ANSI_escape_code#colors). `[3` `[0-9]` `m` is for setting/resetting the colors.

7 is white
9 is reset.
