### ISSUE TITLE
Show example usage with ES2015 template string in readme

### ISSUE THREAD

**Issue by sindresorhus** [chalk/chalk#77]
Eg https://github.com/studio-b12/keyword-popularity/blob/d82a032af87259248997e6d99c360e634909db54/module/bin/help/examples.js

**Comment by Qix-** [comment]
Confused; what do you mean here?

**Comment by kevva** [comment]
How to use it with template strings https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings ;P.

**Comment by Qix-** [comment]
Do we really need this? Doesn't this require `--harmony`?

**Comment by kevva** [comment]
Yeah, just an example in the readme.

**Comment by sindresorhus** [comment]
Many people are using ES2015 with Babel these days. Just useful to show how much nicer Chalk usage will be with template strings.
