### ISSUE TITLE
reset attributes

### ISSUE THREAD

**Issue by tmx976** [chalk/chalk#78]
We are talking about windows OS..
If I send to console
```javascript
console.log(chalk.red("ERROR"), 5);
```
it works as espected, so the string is red and the number is white. 
If I send the same through socket, a telnet client show in red all the line.
This means that ESC[39m; doesn't work..

I tryed to change the index.js in ansi-style module, replacing the 39 with '0;39' (and the same for 40 -> '0;49'), and work well on console and socket..

I'm new to ansi, and I don't know if it's a support problem of telnet client, or i'm missing something else, but if i'm right.. this way may be good.

**Comment by Qix-** [comment]
Could you show us the code you're using to send data through the socket?

**Comment by tmx976** [comment]
I simply send a string formatted with chalk
```javascript
		var t='';
		t+=chalk.black(' black ');
		t+=chalk.red(' red ');
		t+=chalk.green(' green ');
		t+=chalk.yellow(' yellow ');
		t+=chalk.blue(' blue ');
		t+=chalk.magenta(' magenta ');
		t+=chalk.cyan(' cyan ');
		t+=chalk.white(' white ');
		t+="\n";
		t+=chalk.bold.black(' black ');
		t+=chalk.bold.red(' red ');
		t+=chalk.bold.green(' green ');
		t+=chalk.bold.yellow(' yellow ');
		t+=chalk.bold.blue(' blue ');
		t+=chalk.bold.magenta(' magenta ');
		t+=chalk.bold.cyan(' cyan ');
		t+=chalk.bold.white(' white ');
		t+="\n";
		t+=chalk.bold.bgBlack(' black ');
		t+=chalk.bold.bgRed(' red ');
		t+=chalk.bold.bgGreen(' green ');
		t+=chalk.bold.bgYellow(' yellow ');
		t+=chalk.bold.bgBlue(' blue ');
		t+=chalk.bold.bgMagenta(' magenta ');
		t+=chalk.bold.bgCyan(' cyan ');
		t+=chalk.bold.bgWhite(' white ');
		t+="\n";
		t+=chalk.bold.bbgBlack(' black ');
		t+=chalk.bold.bbgRed(' red ');
		t+=chalk.bold.bbgGreen(' green ');
		t+=chalk.bold.bbgYellow(' yellow ');
		t+=chalk.bold.bbgBlue(' blue ');
		t+=chalk.bold.bbgMagenta(' magenta ');
		t+=chalk.bold.bbgCyan(' cyan ');
		t+=chalk.bold.bbgWhite(' white ');
		console.log(t);
```
I hooked the process.stdout to redirect also to each client connected.
in the console the output is:

![console](https://cloud.githubusercontent.com/assets/13355520/9112289/0f90ffee-3c4e-11e5-9125-ec9b1e3dec6e.png)


in the windows telnet client is:

![telnet](https://cloud.githubusercontent.com/assets/13355520/9112305/2b5c8efa-3c4e-11e5-8712-cd626f24747e.png)


the last line has black background because the telnet console does not support the high intensity background (100m - 107m)
(I also remove the anti-blue hack, justo to see)

For clarity, if i replace the \u001b with a #, the output is the same as the telnet:

![telnetnoesc](https://cloud.githubusercontent.com/assets/13355520/9112346/57df36c6-3c4e-11e5-92ec-d7698a3a38df.png)

this is right.. no problem.. **BUT**..
if I send a

```javascript
console.log(chalk.bold.red("TEST"), 'DOH!');
```
and hack the output function to print also the #-version

```javascript
string=string + '---' +string.replace(/\u001b/g, '#');
```
i got in the console:

![consoleok0](https://cloud.githubusercontent.com/assets/13355520/9112387/91241104-3c4e-11e5-943c-34892ae41369.png)

and in the telnet:

![telnetok0](https://cloud.githubusercontent.com/assets/13355520/9112394/9a5eddb2-3c4e-11e5-98a6-f754c01de930.png)

but if I remove the '0;' preceding the 39m

i got in the console:

![consoleok](https://cloud.githubusercontent.com/assets/13355520/9112402/a1a2f3ec-3c4e-11e5-8acd-fb25de630cd5.png)

and in the telnet:

![telnetko](https://cloud.githubusercontent.com/assets/13355520/9112404/a5cafa64-3c4e-11e5-90d4-62a86f0e7a27.png)

the red color is still there after the 39m! (the 22m do its job removing the bold attribute)

**Comment by Qix-** [comment]
This does seem like buggy functionality. @sindresorhus might have more insight.

However, why are you removing `0;`?

**Comment by tmx976** [comment]
I added myself the `0;` to the module ansi-style, so I remove it to show the module functionality out of the box, as it is provided.

may the buggy thing be the windows telnet console? I need to try with a linux telnet.. or other windows telnet implementation..

**Comment by Qix-** [comment]
Yeah this seems weird. Have you tested another telnet client?

**Comment by tmx976** [comment]
No, I'm sorry.. I haven't tested yet..

**Comment by sindresorhus** [comment]
Doesn't look like an issue with Chalk. We're just using normal ansi escape codes. It's either an issue with telnet, cmd.exe or libuv.
