### ISSUE TITLE
Colors in docker container

### ISSUE THREAD

**Issue by Martodox** [chalk/chalk#79]
Hi.
I am using gulp in my docker container (which depends on chalk)
It uses, by default, chalk.red, etc. 
It works fine except for the fact, colors don't work in docker container. All logs come out B&W.
The work around for that is usage of chalk.styles.color.open and ... .end syntax.

Is there a way to make all default functions use ansi coloring?

**Comment by Qix-** [comment]
Try setting the environment variable `FORCE_COLOR=1`. If that doesn't work (it should), try running the command with `--colors` as a flag.

**Comment by Qix-** [comment]
Hey @Martodox, I'm going to assume this worked for you. If you have any other issues let us know!

**Comment by Toub** [comment]
FORCE_COLOR=1 worked for me, thanks!
