### ISSUE TITLE
Using chalk affects length property

### ISSUE THREAD

**Issue by gajus** [chalk/chalk#83]
```sh
curiosity:table gajus$ node -e "console.log(require('chalk').red('test').length);"
14
```

**Comment by shinnn** [comment]
Yes, because chalk wraps a given string with [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors_and_Styles). [string-length](https://github.com/sindresorhus/string-length) helps you in this case.
