### ISSUE TITLE
Using chalk breaks slice method

### ISSUE THREAD

**Issue by gajus** [chalk/chalk#84]
```js
let subject;

subject = chalk.red('foobar');

console.log('subject', subject, subject.slice(0, 3), subject.slice(3, 0));
```

I cannot even paste the output because it messes up the terminal output.

**Comment by shinnn** [comment]
Same reason: https://github.com/chalk/chalk/issues/83#issuecomment-139891373

> chalk wraps a given string with ANSI escape codes.

Call `subject.slice` before applying `chalk.red` to the string.

**Comment by sindresorhus** [comment]
https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by gajus** [comment]
@shinnn I have written a utility for slicing text that has ANSI escape codes. Please consider mentioning [`ansi-slice`](https://github.com/gajus/ansi-slice) in the documentation. It has been tested to work with `chalk`.

**Comment by Qix-** [comment]
The thing is, though, is that when writing code with Chalk, you usually render the code *after* you've split it however you need to. I don't know of a use-case with `ansi-slice` and chalk that couldn't otherwise be a side effect of writing some weird and probably wrong code.

**Comment by gajus** [comment]
@Qix- I can explain the use case. I am writing a tool to display data in a text table, think a variation of https://www.npmjs.com/package/text-table. User will want to provide whatever data using whatever styling to the table, e.g.

```js
import table from 'table';
import chalk from 'chalk';
import loremIpsum from 'lorem-ipsum';

table([
    [
        chalk.red(loremIpsum())
    ]
]);
```

In the above example, table will need to slice the input to enforce column max-width constraints. This cannot be done before passing data to the table.

**Comment by Qix-** [comment]
Hmm. Not how I would do things personally, but I see your point. Including `ansi-slice` will be up to @sindresorhus.
