### ISSUE TITLE
How to create orange

### ISSUE THREAD

**Issue by mikeerickson** [chalk/chalk#87]
I am looking to display console message in orange, but I am having difficulty finding orange?

**Comment by sindresorhus** [comment]
Currently `chalk` only supports the basic ANSI colors (as those are the ones most terminals supports), which doesn't include orange. We are discussing how to bring in support for 256 colors and true color which will get you orange and lots of other colors: https://github.com/chalk/chalk/issues/73

**Comment by Qix-** [comment]
When #140 is merged, you'll be able to use `chalk.keyword('orange')`.
