### ISSUE TITLE
No output at all, but no error either

### ISSUE THREAD

**Issue by cfjedimaster** [chalk/chalk#89]
I've got Chalk in a pretty simple Node app and when I run it, nothing is output. I don't get an error and chalk.supportsColor reports true.

**Comment by dthree** [comment]
Can you give some sample code?

**Comment by cfjedimaster** [comment]
It's pretty literal. Here is a new file I just made:

var chalk = require('chalk');
console.log('wtf1 ',chalk.supportsColor);
chalk.red('hello');
console.log('wtf2');

I get: 
wtf1 true
wtf2

and nothing in between.

**Comment by dthree** [comment]
Thanks.

Chalk itself isn't a logging statement. It wraps text with ANSI codes that represent colors. This is what you should do:

```js
console.log(chalk.red('hello'));
```

Does that help?

**Comment by cfjedimaster** [comment]
Wow. Absolutely. But why do most of the docs on the home page not show this?

For example, the very first demo:

chalk.blue('Hello world!');

would do absolutely nothing, right, since it isn't assigning the
result to a variable or logging it.



On Wed, Nov 4, 2015 at 4:45 PM, dc <notifications@github.com> wrote:

> Thanks.
>
> Chalk itself isn't a logging statement. It wraps text with ANSI codes that
> represent colors. This is what you should do:
>
> console.log(chalk.red('hello'));
>
> Does that help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chalk/chalk/issues/89#issuecomment-153893755>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by dthree** [comment]
I think @sindresorhus did that for clarity's sake. Filling up a viewer's first introduction to chalk with `console.log` wrappers can make it seem a little complex at first glance, and a logging example appears in the next code blog. I do see where you're coming from, though.

Don't know if Sindre's going to change that, it's up to him.

**Comment by cfjedimaster** [comment]
Fair enough. Thanks again.

On Wed, Nov 4, 2015 at 4:50 PM, dc <notifications@github.com> wrote:

> Closed #89 <https://github.com/chalk/chalk/issues/89>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chalk/chalk/issues/89#event-455102209>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by dthree** [comment]
Yeah no problem.

**Comment by Qix-** [comment]
> Filling up a viewer's first introduction to chalk with `console.log` wrappers can make it seem a little complex at first glance

Pretty sure this is exactly why :dance: Good observation though @cfjedimaster.

@sindresorhus perhaps we could be more clear about this in the readme?

Thanks @dthree for clearing it up :)

**Comment by sindresorhus** [comment]
I've clarified the readme.

**Comment by dthree** [comment]
:+1:

**Comment by cfjedimaster** [comment]
Perfect - thank you!

On Thu, Nov 5, 2015 at 12:47 AM, dc <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chalk/chalk/issues/89#issuecomment-153971845>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
