### ISSUE TITLE
Add support for color replacement themes 

### ISSUE THREAD

**Issue by martinheidegger** [chalk/chalk#90]
The default colors in _some_ terminals are resulting in unreadable content. It would be awesome if there was a way to change the output of the colors depending on a "theme" that replaces the way the default colors are written - preferably it should be a theme that automatically falls back from 16m to 256 colors to 16 colors to b/w.

**Comment by sindresorhus** [comment]
> The default colors in some terminals are resulting in unreadable content.

What terminal and what color? Screenshot please ;)

We already fix the stupid blue color in cmd.exe: https://github.com/chalk/chalk/blob/83615f2ed655486641ac13814cd21b36bd9cdfd3/index.js#L15-L18

**Comment by martinheidegger** [comment]
I started to prepare a tool called 'sysenv' and asked some people for screenshots https://github.com/workshopper/learnyounode/issues/381

**Comment by sindresorhus** [comment]
@martinheidegger Chalk needs to be updated: https://github.com/workshopper/learnyounode/blob/6fe4e39721b140845b100215d24e8f983b030c20/package.json#L55

**Comment by AntoniosHadji** [comment]
I'm seeing this error with solarized color scheme on gnome-terminal in Ubuntu.

**Comment by martinheidegger** [comment]
Note that in learnyounode I have now two color schemes which I tested in a few terminals and default settings and that kind-of work okay. The amount of colors used is greatly reduced: https://github.com/firede/msee/blob/master/lib/msee.js#L28
