### ISSUE TITLE
Orange Foreground

### ISSUE THREAD

**Issue by mikeerickson** [chalk/chalk#94]
Hey gang

Trying to figure out how to use Chalk and create a foreground orange color?   I cant seem to locate a table, etc. of how to generate various colors, thus I am asking here.

If anybody has used Chalk to provide an orange foreground color, please share :-)

**Comment by Qix-** [comment]
Hi! Unfortunately the closest you'll get with the 16 color palette is dark yellow. There is no orange color in the ANSI palette.

Once 256 color support is added to chalk, this will be a different story.

**Comment by mikeerickson** [comment]
@Qix- Well, thats a bummer.  I supposed I could just install and use `colors` for orange ?

Has there been talk about extending chalk to support 256 colors?

**Comment by mikeerickson** [comment]
@Qix So, based on your reply, I just did a little hack to get orange output

var orange = "\033[38;5;214m";
console.log(orange('Hello World!'));

Note:  This 'hack' wont work in strict mode, so make sure you dont have "use strict" were this is used

I have done very limited testing, but it works on OSX, Ubuntu, CentOS and Windows

**Comment by Qix-** [comment]
> Has there been talk about extending chalk to support 256 colors?

Yep, in #73 and chalk/ansi-styles#13 and chalk/ansi-styles#11. It's taking a bit because we're trying to figure out the best route for the API.

> I just did a little hack to get orange output

That works!

**Comment by mikeerickson** [comment]
Ya, it will suffice for now until chalk has official support.  Thx for discussing, most appreciated

**Comment by Qix-** [comment]
No problem!
