### ISSUE TITLE
Support ANSI Codes in new Windows 10

### ISSUE THREAD

**Issue by LPGhatguy** [chalk/chalk#98]
It appears that [ANSI color codes have arrived in Windows 10](https://twitter.com/shanselman/status/695738082209853440) in the fast ring insider builds.

Would it be possible to target these new builds with ANSI codes? Would it be useful?

[Detection of support should just be a flag](https://twitter.com/shanselman/status/695771659215572993).

**Comment by Qix-** [comment]
Not a Chalk thing, but this is super exciting to see. Thanks for letting me (us) know. I knew they were going to get around to it, but it was just a matter of time.

This is going to be something to inquire about over at [libuv](/libuv/libuv). :+1:

**Comment by LPGhatguy** [comment]
Cool, thanks for letting me know where to file; I wasn't sure what level colors were implemented at.

**Comment by Qix-** [comment]
Yeah, the way it works is LibUV proxies output on windows in `win/tty.c` and provides a fake ANSI render state that gets translated to the appropriate `ConsoleWriteInfo` (or whatever) API calls. On *nix platforms they're just forwarded. They'll probably turn off that proxy layer on windows 10 whenever it becomes stable.

Chalk just outputs the escape sequences and lets Node handle their actual behavior.
