### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by SpencerCDixon** [chalk/chalk#99]
I'm trying to figure out how to make test assertions that my methods are applying chalk coloring to text.  I've tried using sinon.js to do something like: `sinon.spy(chalk, 'green')` but it doesn't seem to be working.  Any recommendations for how people make assertions with chalk other then `hasColor` which just tests that A color exists?  I'd like to assert a specific color is present

**Comment by Qix-** [comment]
Not entirely sure what you mean. What are you trying to assert/test for?

**Comment by SpencerCDixon** [comment]
correct.  I just want an assertion that my function is returning text that is colored green or red or whatever

**Comment by Qix-** [comment]
Interesting that sinon isn't working. Maybe @sindresorhus has an idea why it isn't.

If you're wanting to ensure a string contains green, you could either do

```js
assert.equals(chalk.green('Some string'), someString);
```

if you know the expected string's contents. If you don't and just want to make sure it contains, say, green:

```js
assert(someString.includes(chalk.styles.green.open));
```

**Comment by SpencerCDixon** [comment]
Awesome got it working!  Thank you sir!

**Comment by Qix-** [comment]
No problem! :dancer:
